// src/lib/decoyFakeData.ts
//
// Fabricated-but-plausible dataset returned by AppContext when authMode === "decoy".
// Must be inert: no real features enabled, no real config exposed, no secrets.
// All data is statically constructed — no backend calls, no writes.
//
// KT: typed against the real interfaces so tsc validates the shape on every build.

import type { AppSettings, AppInventorySnapshot } from "../types/settings";
import type { ModuleConfig } from "../types/modules";
import pkg from "../../package.json";

// KT: per-session random device ID — stable within one decoy session but never
// a hardcoded constant shared across installs, which would be trivially linkable.
const DECOY_DEVICE_ID = crypto.randomUUID();

// A convincing-looking but entirely fabricated hostname for the decoy session.
const DECOY_HOSTNAME = "DESKTOP-K7MN3PR";

const DECOY_MODULES: ModuleConfig = {
  network:      true,
  tweaks:       true,
  apps:         true,
  privacy:      false,
  privacyShield: false,
  cleanup:      false,
  vault:        false,
  mesh:         false,
  productivity: false,
  serverApps:   false,
  searchFiles:  false,
  flows:        false,
};

// Realistic-looking app inventory — ordinary consumer software, no updates pending.
export const DECOY_INVENTORY: AppInventorySnapshot = {
  lastScanAt: "2026-06-20T09:14:03.000Z",
  scanDurationMs: 8340,
  manifestApps: [
    {
      id: "7zip.7zip",
      name: "7-Zip",
      description: "File archiver with high compression ratio",
      category: "Utilities",
      installed: true,
      installedVersion: "24.08",
      latestVersion: "24.08",
      updateAvailable: false,
    },
    {
      id: "VideoLAN.VLC",
      name: "VLC media player",
      description: "Open source cross-platform multimedia player",
      category: "Media",
      installed: true,
      installedVersion: "3.0.21",
      latestVersion: "3.0.21",
      updateAvailable: false,
    },
    {
      id: "Google.Chrome",
      name: "Google Chrome",
      description: "Fast, secure web browser from Google",
      category: "Browsers",
      installed: true,
      installedVersion: "126.0.6478.63",
      latestVersion: "126.0.6478.63",
      updateAvailable: false,
    },
    {
      id: "Mozilla.Firefox",
      name: "Mozilla Firefox",
      description: "Fast, private and safe web browser",
      category: "Browsers",
      installed: false,
      installedVersion: null,
      latestVersion: "127.0",
      updateAvailable: false,
    },
    {
      id: "Notepad++.Notepad++",
      name: "Notepad++",
      description: "A free source code editor and Notepad replacement",
      category: "Editors",
      installed: true,
      installedVersion: "8.6.8",
      latestVersion: "8.6.8",
      updateAvailable: false,
    },
  ],
  otherApps: [
    {
      id: "Microsoft.Office.OneNote_8wekyb3d8bbwe",
      name: "Microsoft OneNote",
      installedVersion: "16.0.17531.20152",
      latestVersion: null,
      updateAvailable: false,
    },
    {
      id: "Microsoft.WindowsCalculator_8wekyb3d8bbwe",
      name: "Windows Calculator",
      installedVersion: "11.2401.25.0",
      latestVersion: null,
      updateAvailable: false,
    },
    {
      id: "Spotify.Spotify",
      name: "Spotify",
      installedVersion: "1.2.40.274",
      latestVersion: "1.2.40.274",
      updateAvailable: false,
    },
  ],
  pendingUpdates: [],
  essentials: {
    meshVpn:          { installed: false, version: null, connected: null },
    productivityEngine: { installed: false, running: null },
    winget:           { installed: true, version: "1.8.1911" },
  },
  summary: {
    totalInstalled:     8,
    manifestInstalled:  4,
    manifestTotal:      5,
    manifestMissing:    1,
    otherInstalled:     3,
    updatesAvailable:   0,
    essentialsOk:       false,
  },
};

// Fabricated AppSettings that looks like a lightly-used Windows PC.
// Security/privacy toggles are off — it's meant to look unmodified.
// CRITICAL: decoyMode.enabled is false so no real decoy config leaks.
export const DECOY_APP_SETTINGS: AppSettings = {
  settingsVersion: 2,
  // KT: always matches the running binary — avoids version mismatch tells.
  appVersion: pkg.version,
  // KT: per-session UUID, not a hardcoded constant, so it can't be fingerprinted
  // across multiple decoy sessions or compared against a seized settings.json.
  deviceId: DECOY_DEVICE_ID,
  lastSeenAt: "2026-06-20T09:14:05.000Z",
  createdAt: "2025-11-12T14:32:00.000Z",
  app: {
    theme: "light",
    firstRunComplete: true,
    hasSeenMandatoryTour: true,
    autoUpdate: true,
    startMinimized: false,
    contextMenuEnabled: false,
    scrubContextMenuEnabled: false,
    safeCopyContextMenuEnabled: false,
    sidebarCollapsed: false,
    lastPanel: "dashboard",
    dashboardViewMode: "default",
    dashboardOpenCards: ["system"],
    ignoredFindingIds: [],
    dismissedNeedsAttentionIds: [],
    experienceLevel: "standard",
    privacyCleanEnabled: false,
    panicHotkey: "",
    searchHotkey: "",
    rdpNodes: [],
    selectedRdpNodeId: null,
    notifications: { position: "bottom-right", timeout: 4000 },
    vault: { defaultMountLetter: null, recentPaths: [] },
    firstRun: { selectedBlocklists: [] },
    shortcuts: {},
    sounds: { enabled: true },
    flows: [],
    contingency: {
      identities: {},
      myIndex: 0,
      signalTransport: "taildrop",
      hmacKey: "",
      serverTailscaleIP: "",
      usbKeyDeviceId: null,
      usbGateEnabled: false,
      webhookPort: 47821,
    },
    modules: DECOY_MODULES,
    advisor: { model: "qwen3.5:4b" },
    loggingEnabled: false,
    autoHeal: false,
    disableUpdates: false,
    hideAdvisor: true,
    hideEnginesSection: true,
    // KT: panels reading app.decoyMode must see a well-shaped object, not undefined.
    // enabled=false here is load-bearing: this is the fake settings layer, not the
    // real one — the real decoy-mode flag lives in the Rust-protected settings.json.
    decoyMode: { enabled: false, displayName: '' },
  },
  ideal: {
    device: {
      cpu: null,
      ramGb: null,
      gpu: null,
      disks: [],
      macAddresses: [],
      serialNumber: null,
      biosVersion: null,
      osBuild: null,
      domain: null,
      timeZone: "Eastern Standard Time",
      systemLocale: "en-US",
      users: [],
      runtimes: null,
      windowsActivated: null,
      bitlockerStatus: [],
      lastUpdateAt: null,
      pendingUpdatesCount: null,
      hostname: DECOY_HOSTNAME,
    },
    privacy: {
      telemetry: {
        windowsDisabled: false,
        officeDisabled: null,
        powershell7Disabled: null,
        copilotDisabled: null,
        activityHistoryDisabled: null,
        locationTrackingDisabled: null,
        windowsSuggestionsDisabled: null,
      },
      clipboard: {
        historyDisabled: null,
        cloudSyncDisabled: null,
        pasteMonitorEnabled: null,
        pasteMonitorCategories: null,
        pasteMonitorCryptoSwapEnabled: null,
        pasteMonitorAutoClearEnabled: null,
        pasteMonitorAutoClearSeconds: null,
      },
      tracking: {
        recentFilesDisabled: null,
        jumpListsDisabled: null,
        thumbnailCacheDisabled: null,
        pagefileDisabled: null,
        recallSnapshotsDisabled: null,
        typingInsightsDisabled: null,
        advertisingIdDisabled: null,
        tailoredExperiencesDisabled: null,
        officeLoggingDisabled: null,
        diagnosticEventTracingDisabled: null,
        rdpIdleDisconnectEnabled: null,
        rdpIdleDisconnectTimeout: null,
        rdpClearCacheOnDisconnect: null,
        rdpRemoveCredsOnDisconnect: null,
        rdpSaveLog: null,
        quickAccessRecentDisabled: null,
        quickAccessFrequentDisabled: null,
        runMruDisabled: null,
        searchHistoryDisabled: null,
        terminalHistoryDisabled: null,
      },
      lockscreen: { privacyDisabled: null },
      appCapabilities: {
        webcam: "Allow",
        microphone: "Allow",
        location: "Allow",
        contacts: "Allow",
        calendar: "Allow",
        callHistory: "Allow",
        phoneCall: "Allow",
        email: "Allow",
        messaging: "Allow",
        radios: "Allow",
        bluetoothSync: "Allow",
        appDiagnostics: "Allow",
        documents: "Allow",
        pictures: "Allow",
        videos: "Allow",
        fileSystem: "Allow",
        notifications: "Allow",
        gazeInput: "Allow",
        userAccountInformation: "Allow",
      },
      decoyMonitor: { enabled: false, enrolledPaths: [] },
      ransomwareMonitor: { enabled: false, threshold: null, windowSeconds: null, customWatchDirs: [] },
      remoteAccessMonitor: { enabled: null },
      screenCapture: { detectionEnabled: null, protectWindow: null },
      coercionPhrase: { enabled: null, phrases: [] },
      selfDestruct: { steps: {} },
      internetCommunication: { restrictedEnabled: null },
      privacyProtectionEnabled: null,
      setupCompletionNagsDisabled: null,
      acquisitionWatchEnabled: null,
      privacyShield: {
        gazeDetectionEnabled: null,
        antiPeepingEnabled: null,
        cameraHunterEnabled: null,
        confidenceThreshold: null,
        wakeDelaySeconds: null,
        blurOpacity: null,
        modelSize: null,
        detectionBufferFrames: null,
        captureOnDevice: null,
        captureOnMultiFace: null,
        captureSpeed: null,
        deviceWakeMultiplier: null,
        multiFaceWakeMultiplier: null,
      },
      prevention: {
        auditReductionDisabled: null,
        bamDisabled: null,
        shimCacheDisabled: null,
        userAssistDisabled: null,
        usbEventLogDisabled: null,
        ssidHistoryDisabled: null,
        storageEventLogDisabled: null,
        recentActivityDisabled: null,
        diagnosticChannelDisabled: null,
        reliabilityMonitorDisabled: null,
        werDisabled: null,
        scriptBlockLoggingDisabled: null,
        telemetryRunnerDisabled: null,
      },
    },
    tweaks: {
      security: {
        defenderDisabled: false,
        windowsUpdateDisabled: false,
        uacDisabled: null,
        usbWriteProtect: null,
        usbStorageLockdown: null,
        consumerFeaturesDisabled: null,
        remoteAssistanceDisabled: null,
        anonymousSamEnumerationBlocked: null,
        vbsDisabled: null,
        bitlockerAutoEncryptDisabled: null,
        wpbtDisabled: null,
        smartScreenDisabled: null,
        oobeBypassEnabled: null,
        gameDvrDisabled: null,
        firefoxHardeningEnabled: null,
        braveHardeningEnabled: null,
        chromeHardeningEnabled: null,
        edgeHardeningEnabled: null,
        universalExtensionsDeployed: null,
        browserAutoUpdateForced: null,
        copilotAiRemoved: null,
        systemRestoreOff: null,
        recallOff: null,
        crashDumpsOff: null,
        clipboardHistoryOff: null,
        requirePwOnResume: null,
        kernelDmaProtect: null,
        shredPasses: null,
        shredMediaAwareEnabled: null,
        shredMftSlackEnabled: null,
        ramSpillControlEnabled: null,
        bitlockerTpmPinEnforce: null,
        acquisitionDriverBlocklist: null,
        forensicToolBlock: null,
        lidClosePowerOff: null,
        depEnabled: null,
        aslrMandatory: null,
        aslrBottomUp: null,
        cfgEnabled: null,
        heapIntegrity: null,
        sehopEnabled: null,
        asrRulesEnabled: null,
        controlledFolderAccessEnabled: null,
        networkProtectionEnabled: null,
      },
      os: {
        superfetchDisabled: null,
        prefetchDisabled: null,
        hibernationDisabled: null,
        fastStartupDisabled: null,
        ntfsOptimizationsEnabled: null,
        detailedBsodEnabled: null,
        memoryCompressionDisabled: null,
        win32PrioritySeparation: null,
        serviceTimeoutsOptimized: null,
        reservedStorageDisabled: null,
        automaticMaintenanceDisabled: null,
        win32LongPathsEnabled: null,
        smbBandwidthThrottlingDisabled: null,
      },
      ui: {
        classicContextMenu: null,
        fileExtensionsVisible: null,
        hiddenFilesVisible: null,
        galleryHomeRemoved: null,
        bingSearchDisabled: null,
        backgroundAppsDisabled: null,
        notificationsDisabled: null,
        endTaskOnTaskbar: null,
        folderTypeDiscoveryDisabled: null,
        shortcutSuffixRemoved: null,
        autoPlayDisabled: null,
        taskbarDebloated: null,
        startRecommendationsDisabled: null,
        lowDiskCheckDisabled: null,
        explorerOpensThisPc: null,
        syncProviderNotificationsHidden: null,
        transparencyDisabled: null,
        fullPathInTitleBar: null,
        desktopIconThisPc: null,
        desktopIconRecycleBin: null,
        desktopIconUserFiles: null,
        desktopIconNetwork: null,
        desktopIconControlPanel: null,
        shortcutArrowRemoved: null,
        snapAssistFlyoutDisabled: null,
        explorerCompactMode: null,
        explorerCheckboxesEnabled: null,
        windowShakeDisabled: null,
        clockSecondsVisible: null,
      },
      bootKernel: {
        tsxEnabled: null,
        firstLogonAnimationDisabled: null,
        startupSoundDisabled: null,
        autoRestartSignonDisabled: null,
        autoRebootOnBsodDisabled: null,
        smallMemoryDumpEnabled: null,
      },
      performance: {
        mmcssGamingProfile: null,
        keyboardLatencyOptimised: null,
        numLockOnBoot: null,
        gpuSchedulingEnabled: null,
        svcHostSplitOptimised: null,
        accessibilityShortcutsDisabled: null,
        instantMenuDelay: null,
        mouseAccelerationDisabled: null,
        autocorrectDisabled: null,
        enthusiastModeEnabled: null,
        wallpaperFullQuality: null,
      },
      gpu: {
        amdUlpsDisabled: null,
        amdPowerGatingDisabled: null,
        amdVideoClockGatingDisabled: null,
        amdAspmDisabled: null,
        nvidiaDynamicPstateDisabled: null,
        nvidiaAsyncPstatesDisabled: null,
        intelAsyncFlipsDisabled: null,
        intelAdaptiveVsyncDisabled: null,
      },
      power: {
        usbSelectiveSuspendDisabled: null,
        cpuThrottlingDisabled: null,
      },
      powerPlan: "balanced",
    },
    network: {
      dns: {
        provider: null,
        ipv4Preference: null,
        swissFirewallConfig: null,
        controlDFilterSlug: null,
        censorshipProtection: null,
      },
      hosts: { enabledBlocklists: [] },
      firewall: { lockdownMode: null, managedRules: [] },
    },
    identity: {
      branding: {
        companyName: null,
        productName: null,
        pcName: null,
        manufacturer: null,
        supportUrl: null,
      },
      stealthModeEnabled: null,
      hideServerApps: null,
      hideWinCommander: null,
      hideWinCommanderHotkey: null,
      flowsEnabled: null,
      advancedToolsEnabled: null,
      riskMatrixEnabled: null,
      moreProductsEnabled: null,
    },
    apps: {
      requiredApps: [],
      blockedApps: [],
      edgeRemoved: null,
      onedriveRemoved: null,
      teamsRemoved: null,
      removedAppx: [],
      deprovisionedAppx: [],
      autoUpdate: false,
      inventory: DECOY_INVENTORY,
    },
    productivity: {
      trackerEnabled: null,
      productivityEngineStealthEnabled: null,
      excludeAfk: null,
      defaultRange: null,
    },
    serverApps: { apps: [] },
    security: {
      drivers: {
        watchEnabled: false,
        watchIntervalSecs: 300,
        scanOnStartup: false,
      },
    },
  },
  current: {
    device: {
      cpu: "Intel Core i5-12400F",
      ramGb: 16,
      gpu: "NVIDIA GeForce GTX 1660 Super",
      disks: [{ model: "Samsung SSD 870 EVO 500GB", sizeGb: 500, diskType: "SSD" }],
      macAddresses: [],
      serialNumber: null,
      biosVersion: null,
      osBuild: "22621.3737",
      domain: null,
      timeZone: "Eastern Standard Time",
      systemLocale: "en-US",
      users: [
        {
          username: "user",
          enabled: true,
          isAdmin: true,
          lastLogon: "2026-06-20T08:55:11.000Z",
          sid: "S-1-5-21-1924681840-3082874592-2931428101-1001",
        },
      ],
      runtimes: null,
      windowsActivated: true,
      bitlockerStatus: [],
      lastUpdateAt: "2026-06-19T04:30:00.000Z",
      pendingUpdatesCount: 0,
      hostname: DECOY_HOSTNAME,
      osName: "Windows 11 Home",
      osVersion: "22H2",
      deviceType: "Desktop",
      ram: "16 GB",
      isAdmin: true,
    },
    privacy: {
      telemetry: {
        windowsDisabled: false,
        officeDisabled: null,
        powershell7Disabled: null,
        copilotDisabled: null,
        activityHistoryDisabled: null,
        locationTrackingDisabled: null,
        windowsSuggestionsDisabled: null,
      },
      clipboard: {
        historyDisabled: null,
        cloudSyncDisabled: null,
        pasteMonitorEnabled: null,
        pasteMonitorCategories: null,
        pasteMonitorCryptoSwapEnabled: null,
        pasteMonitorAutoClearEnabled: null,
        pasteMonitorAutoClearSeconds: null,
      },
      tracking: {
        recentFilesDisabled: null,
        jumpListsDisabled: null,
        thumbnailCacheDisabled: null,
        pagefileDisabled: null,
        recallSnapshotsDisabled: null,
        typingInsightsDisabled: null,
        advertisingIdDisabled: null,
        tailoredExperiencesDisabled: null,
        officeLoggingDisabled: null,
        diagnosticEventTracingDisabled: null,
        rdpIdleDisconnectEnabled: null,
        rdpIdleDisconnectTimeout: null,
        rdpClearCacheOnDisconnect: null,
        rdpRemoveCredsOnDisconnect: null,
        rdpSaveLog: null,
        quickAccessRecentDisabled: null,
        quickAccessFrequentDisabled: null,
        runMruDisabled: null,
        searchHistoryDisabled: null,
        terminalHistoryDisabled: null,
      },
      lockscreen: { privacyDisabled: null },
      appCapabilities: {
        webcam: "Allow",
        microphone: "Allow",
        location: "Allow",
        contacts: "Allow",
        calendar: "Allow",
        callHistory: "Allow",
        phoneCall: "Allow",
        email: "Allow",
        messaging: "Allow",
        radios: "Allow",
        bluetoothSync: "Allow",
        appDiagnostics: "Allow",
        documents: "Allow",
        pictures: "Allow",
        videos: "Allow",
        fileSystem: "Allow",
        notifications: "Allow",
        gazeInput: "Allow",
        userAccountInformation: "Allow",
      },
      decoyMonitor: { enabled: false, enrolledPaths: [] },
      ransomwareMonitor: { enabled: false, threshold: null, windowSeconds: null, customWatchDirs: [] },
      remoteAccessMonitor: { enabled: null },
      screenCapture: { detectionEnabled: null, protectWindow: null },
      coercionPhrase: { enabled: null, phrases: [] },
      selfDestruct: { steps: {} },
      internetCommunication: { restrictedEnabled: null },
      privacyProtectionEnabled: null,
      setupCompletionNagsDisabled: null,
      acquisitionWatchEnabled: null,
      privacyShield: {
        gazeDetectionEnabled: null,
        antiPeepingEnabled: null,
        cameraHunterEnabled: null,
        confidenceThreshold: null,
        wakeDelaySeconds: null,
        blurOpacity: null,
        modelSize: null,
        detectionBufferFrames: null,
        captureOnDevice: null,
        captureOnMultiFace: null,
        captureSpeed: null,
        deviceWakeMultiplier: null,
        multiFaceWakeMultiplier: null,
      },
      prevention: {
        auditReductionDisabled: null,
        bamDisabled: null,
        shimCacheDisabled: null,
        userAssistDisabled: null,
        usbEventLogDisabled: null,
        ssidHistoryDisabled: null,
        storageEventLogDisabled: null,
        recentActivityDisabled: null,
        diagnosticChannelDisabled: null,
        reliabilityMonitorDisabled: null,
        werDisabled: null,
        scriptBlockLoggingDisabled: null,
        telemetryRunnerDisabled: null,
      },
    },
    tweaks: {
      security: {
        defenderDisabled: false,
        windowsUpdateDisabled: false,
        uacDisabled: null,
        usbWriteProtect: null,
        usbStorageLockdown: null,
        consumerFeaturesDisabled: null,
        remoteAssistanceDisabled: null,
        anonymousSamEnumerationBlocked: null,
        vbsDisabled: null,
        bitlockerAutoEncryptDisabled: null,
        wpbtDisabled: null,
        smartScreenDisabled: null,
        oobeBypassEnabled: null,
        gameDvrDisabled: null,
        firefoxHardeningEnabled: null,
        braveHardeningEnabled: null,
        chromeHardeningEnabled: null,
        edgeHardeningEnabled: null,
        universalExtensionsDeployed: null,
        browserAutoUpdateForced: null,
        copilotAiRemoved: null,
        systemRestoreOff: null,
        recallOff: null,
        crashDumpsOff: null,
        clipboardHistoryOff: null,
        requirePwOnResume: null,
        kernelDmaProtect: null,
        shredPasses: null,
        shredMediaAwareEnabled: null,
        shredMftSlackEnabled: null,
        ramSpillControlEnabled: null,
        bitlockerTpmPinEnforce: null,
        acquisitionDriverBlocklist: null,
        forensicToolBlock: null,
        lidClosePowerOff: null,
        depEnabled: null,
        aslrMandatory: null,
        aslrBottomUp: null,
        cfgEnabled: null,
        heapIntegrity: null,
        sehopEnabled: null,
        asrRulesEnabled: null,
        controlledFolderAccessEnabled: null,
        networkProtectionEnabled: null,
      },
      os: {
        superfetchDisabled: null,
        prefetchDisabled: null,
        hibernationDisabled: null,
        fastStartupDisabled: null,
        ntfsOptimizationsEnabled: null,
        detailedBsodEnabled: null,
        memoryCompressionDisabled: null,
        win32PrioritySeparation: null,
        serviceTimeoutsOptimized: null,
        reservedStorageDisabled: null,
        automaticMaintenanceDisabled: null,
        win32LongPathsEnabled: null,
        smbBandwidthThrottlingDisabled: null,
      },
      ui: {
        classicContextMenu: null,
        fileExtensionsVisible: null,
        hiddenFilesVisible: null,
        galleryHomeRemoved: null,
        bingSearchDisabled: null,
        backgroundAppsDisabled: null,
        notificationsDisabled: null,
        endTaskOnTaskbar: null,
        folderTypeDiscoveryDisabled: null,
        shortcutSuffixRemoved: null,
        autoPlayDisabled: null,
        taskbarDebloated: null,
        startRecommendationsDisabled: null,
        lowDiskCheckDisabled: null,
        explorerOpensThisPc: null,
        syncProviderNotificationsHidden: null,
        transparencyDisabled: null,
        fullPathInTitleBar: null,
        desktopIconThisPc: null,
        desktopIconRecycleBin: null,
        desktopIconUserFiles: null,
        desktopIconNetwork: null,
        desktopIconControlPanel: null,
        shortcutArrowRemoved: null,
        snapAssistFlyoutDisabled: null,
        explorerCompactMode: null,
        explorerCheckboxesEnabled: null,
        windowShakeDisabled: null,
        clockSecondsVisible: null,
      },
      bootKernel: {
        tsxEnabled: null,
        firstLogonAnimationDisabled: null,
        startupSoundDisabled: null,
        autoRestartSignonDisabled: null,
        autoRebootOnBsodDisabled: null,
        smallMemoryDumpEnabled: null,
      },
      performance: {
        mmcssGamingProfile: null,
        keyboardLatencyOptimised: null,
        numLockOnBoot: null,
        gpuSchedulingEnabled: null,
        svcHostSplitOptimised: null,
        accessibilityShortcutsDisabled: null,
        instantMenuDelay: null,
        mouseAccelerationDisabled: null,
        autocorrectDisabled: null,
        enthusiastModeEnabled: null,
        wallpaperFullQuality: null,
      },
      gpu: {
        amdUlpsDisabled: null,
        amdPowerGatingDisabled: null,
        amdVideoClockGatingDisabled: null,
        amdAspmDisabled: null,
        nvidiaDynamicPstateDisabled: null,
        nvidiaAsyncPstatesDisabled: null,
        intelAsyncFlipsDisabled: null,
        intelAdaptiveVsyncDisabled: null,
      },
      power: {
        usbSelectiveSuspendDisabled: null,
        cpuThrottlingDisabled: null,
      },
      powerPlan: "balanced",
    },
    network: {
      dns: {
        provider: null,
        ipv4Preference: null,
        swissFirewallConfig: null,
        controlDFilterSlug: null,
        censorshipProtection: null,
      },
      hosts: { enabledBlocklists: [] },
      firewall: { lockdownMode: null, managedRules: [] },
    },
    identity: {
      branding: {
        companyName: null,
        productName: null,
        pcName: null,
        manufacturer: null,
        supportUrl: null,
      },
      stealthModeEnabled: null,
      hideServerApps: null,
      hideWinCommander: null,
      hideWinCommanderHotkey: null,
      flowsEnabled: null,
      advancedToolsEnabled: null,
      riskMatrixEnabled: null,
      moreProductsEnabled: null,
    },
    apps: {
      requiredApps: [],
      blockedApps: [],
      edgeRemoved: null,
      onedriveRemoved: null,
      teamsRemoved: null,
      removedAppx: [],
      deprovisionedAppx: [],
      inventory: DECOY_INVENTORY,
    },
    productivity: {
      trackerEnabled: null,
      productivityEngineStealthEnabled: null,
      excludeAfk: null,
      defaultRange: null,
    },
    serverApps: { apps: [] },
    security: {
      drivers: {
        watchEnabled: false,
        watchIntervalSecs: 300,
        scanOnStartup: false,
      },
    },
  },
  policy: {
    syncMode: "standalone",
    adminServerUrl: null,
    mergeStrategy: "merge",
    lockedPaths: [],
    lastSyncedAt: null,
    masterConfigVersion: null,
    organization: null,
  },
};
