// src/registry/capabilities.toggles.ts
//
// ═══════════════════════════════════════════════════════════════════════
// APP CAPABILITY PRIVACY — Toggle Registry (SINGLE SOURCE OF TRUTH)
// ═══════════════════════════════════════════════════════════════════════
//
// Every app-level capability permission toggle lives here. These use
// Set-AppCapabilityAccess (not regular enable/disable commands) to flip
// Windows CapabilityAccessManager ConsentStore registry keys.
//
// KEY DIFFERENCE from regular toggles:
//   - capabilityKey is set → ToggleSection calls Set-AppCapabilityAccess
//     with { Capability: key, Access: "Deny"|"Allow" } instead of enableCmd/disableCmd.
//   - checkedWhen: "Deny" → settings.json stores "Deny"/"Allow" strings,
//     not booleans. A capability is "active" (blocked) when the value is "Deny".
//   - enableCmd/disableCmd are unused stubs (ToggleSection routes via capabilityKey).
//
// NOTE: The settings.json field names (camelCase) differ from the PS
// capabilityKey names in some cases. The mapping is:
//   capabilityKey      → settings.json field (current.privacy.appCapabilities.X)
//   "webcam"           → webcam
//   "microphone"       → microphone
//   "contacts"         → contacts
//   "appointments"     → calendar
//   "phoneCall"        → phoneCall
//   "phoneCallHistory" → callHistory
//   "chat"             → messaging
//   "userNotificationListener" → notifications
//   "documentsLibrary" → documents
//   "picturesLibrary"  → pictures
//   "videosLibrary"    → videos
//   "broadFileSystemAccess" → fileSystem
//   "gazeInput"        → gazeInput
//   "appDiagnostics"   → appDiagnostics
//   "userAccountInformation" → userAccountInformation
//   "bluetoothSync"    → bluetoothSync

import type { ToggleDef, SectionDef } from "../types/toggles";

function withPrivacyVisibility(toggle: ToggleDef): ToggleDef {
  return {
    ...toggle,
    capability: toggle.capability ?? ["privacy"],
    minDensity:
      toggle.minDensity ??
      (toggle.minExperience === "advanced" ? "expert" : "guided"),
  };
}

// ── Section Definitions ───────────────────────────────────────────────

export const CAPABILITY_SECTIONS: SectionDef[] = [
  { id: "capabilities", title: "App Capability Privacy", icon: "applications", columns: 4 },
];

// ── Toggle Definitions ────────────────────────────────────────────────

const CAPABILITY_TOGGLES_RAW: ToggleDef[] = [
  {
    id: "cap-webcam",
    label: "Disable Camera",
    description: "Block app camera access",
    modeText: {
      simple: { label: "Disable Camera", description: "Stops apps from using the webcam." },
      advanced: { label: "Disable Camera", description: "Block app camera access" },
    },
    impact: "Apps can access webcam without restriction",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "webcam",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.webcam",
    currentPath: "current.privacy.appCapabilities.webcam",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    noNeedsAttention: true,
    icon: "camera",
  },
  {
    id: "cap-microphone",
    label: "Disable Microphone",
    description: "Block app microphone access",
    modeText: {
      simple: { label: "Disable Microphone", description: "Stops apps from using the microphone." },
      advanced: { label: "Disable Microphone", description: "Block app microphone access" },
    },
    impact: "Apps can access microphone without restriction",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "microphone",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.microphone",
    currentPath: "current.privacy.appCapabilities.microphone",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    noNeedsAttention: true,
    icon: "microphone",
  },
  {
    id: "cap-contacts",
    label: "Disable Contacts",
    description: "Block contacts access",
    modeText: {
      simple: { label: "Disable Contacts", description: "Stops apps from reading saved contacts." },
      advanced: { label: "Disable Contacts", description: "Block contacts access" },
    },
    impact: "Apps can read your contacts list",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "contacts",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.contacts",
    currentPath: "current.privacy.appCapabilities.contacts",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "people",
  },
  {
    id: "cap-calendar",
    label: "Disable Calendar",
    description: "Block calendar access",
    modeText: {
      simple: { label: "Disable Calendar", description: "Stops apps from reading calendar events." },
      advanced: { label: "Disable Calendar", description: "Block calendar access" },
    },
    impact: "Apps can read calendar appointments",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "appointments",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.calendar",
    currentPath: "current.privacy.appCapabilities.calendar",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "calendar",
  },
  {
    id: "cap-phoneCall",
    label: "Disable Phone Calls",
    description: "Block call handling APIs",
    modeText: {
      simple: { label: "Disable Phone Calls", description: "Stops apps from using call-related features." },
      advanced: { label: "Disable Phone Calls", description: "Block call handling APIs" },
    },
    impact: "Apps can initiate phone calls",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "phoneCall",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.phoneCall",
    currentPath: "current.privacy.appCapabilities.phoneCall",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "phone",
  },
  {
    id: "cap-callHistory",
    label: "Disable Call History",
    description: "Block call history access",
    modeText: {
      simple: { label: "Disable Call History", description: "Stops apps from reading call history." },
      advanced: { label: "Disable Call History", description: "Block call history access" },
    },
    impact: "Apps can read your call log",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "phoneCallHistory",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.callHistory",
    currentPath: "current.privacy.appCapabilities.callHistory",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "history",
  },
  {
    id: "cap-messaging",
    label: "Disable Messages",
    description: "Block messaging/chat access",
    modeText: {
      simple: { label: "Disable Messages", description: "Stops apps from reading messages and chat data." },
      advanced: { label: "Disable Messages", description: "Block messaging/chat access" },
    },
    impact: "Apps can read SMS and chat messages",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "chat",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.messaging",
    currentPath: "current.privacy.appCapabilities.messaging",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "chat",
  },
  {
    id: "cap-notifications",
    label: "Disable Notifications",
    description: "Block notification read access",
    modeText: {
      simple: { label: "Disable Notifications", description: "Stops apps from reading notifications." },
      advanced: { label: "Disable Notifications", description: "Block notification read access" },
    },
    impact: "Apps can read your notifications",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "userNotificationListener",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.notifications",
    currentPath: "current.privacy.appCapabilities.notifications",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "notifications",
  },
  {
    id: "cap-documents",
    label: "Disable Documents",
    description: "Block documents folder access",
    modeText: {
      simple: { label: "Disable Documents", description: "Stops apps from reading the Documents folder." },
      advanced: { label: "Disable Documents", description: "Block documents folder access" },
    },
    impact: "Apps can access your Documents library",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "documentsLibrary",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.documents",
    currentPath: "current.privacy.appCapabilities.documents",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "folder-open",
  },
  {
    id: "cap-pictures",
    label: "Disable Images",
    description: "Block pictures folder access",
    modeText: {
      simple: { label: "Disable Images", description: "Stops apps from reading the Pictures folder." },
      advanced: { label: "Disable Images", description: "Block pictures folder access" },
    },
    impact: "Apps can access your Pictures library",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "picturesLibrary",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.pictures",
    currentPath: "current.privacy.appCapabilities.pictures",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "media",
  },
  {
    id: "cap-videos",
    label: "Disable Videos",
    description: "Block videos folder access",
    modeText: {
      simple: { label: "Disable Videos", description: "Stops apps from reading the Videos folder." },
      advanced: { label: "Disable Videos", description: "Block videos folder access" },
    },
    impact: "Apps can access your Videos library",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "videosLibrary",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.videos",
    currentPath: "current.privacy.appCapabilities.videos",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "video",
  },
  {
    id: "cap-fileSystem",
    label: "Disable File System",
    description: "Block broad filesystem access",
    modeText: {
      simple: { label: "Disable File System", description: "Stops apps from getting broad access to all files." },
      advanced: { label: "Disable File System", description: "Block broad filesystem access" },
    },
    impact: "Apps can access your entire file system",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "broadFileSystemAccess",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.fileSystem",
    currentPath: "current.privacy.appCapabilities.fileSystem",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "database",
  },
  {
    id: "cap-gazeInput",
    label: "Disable Eye Tracking",
    description: "Block gaze input access",
    modeText: {
      simple: { label: "Disable Eye Tracking", description: "Stops apps from using eye-tracking data." },
      advanced: { label: "Disable Eye Tracking", description: "Block gaze input access" },
    },
    impact: "Apps can track your eye movement",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "gazeInput",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.gazeInput",
    currentPath: "current.privacy.appCapabilities.gazeInput",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "eye-open",
  },
  {
    id: "cap-appDiagnostics",
    label: "Disable App Diagnostics",
    description: "Block diagnostics access",
    modeText: {
      simple: { label: "Disable App Diagnostics", description: "Stops apps from reading diagnostics from other apps." },
      advanced: { label: "Disable App Diagnostics", description: "Block diagnostics access" },
    },
    impact: "Apps can read diagnostic data from other apps",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "appDiagnostics",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.appDiagnostics",
    currentPath: "current.privacy.appCapabilities.appDiagnostics",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "pulse",
  },
  {
    id: "cap-accountInfo",
    label: "Disable Account Info",
    description: "Block account info access",
    modeText: {
      simple: { label: "Disable Account Info", description: "Stops apps from reading account details." },
      advanced: { label: "Disable Account Info", description: "Block account info access" },
    },
    impact: "Apps can read your Microsoft account details",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "userAccountInformation",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.userAccountInformation",
    currentPath: "current.privacy.appCapabilities.userAccountInformation",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "user",
  },
  {
    id: "cap-bluetoothSync",
    label: "Disable Unpaired Devices",
    description: "Block bluetooth sync access",
    modeText: {
      simple: { label: "Disable Unpaired Devices", description: "Stops apps from talking to nearby Bluetooth devices." },
      advanced: { label: "Disable Unpaired Devices", description: "Block bluetooth sync access" },
    },
    impact: "Apps can communicate with unpaired Bluetooth devices",
    section: "capabilities",
    domain: "privacy",
    capabilityKey: "bluetoothSync",
    checkedWhen: "Deny",
    settingsPath: "ideal.privacy.appCapabilities.bluetoothSync",
    currentPath: "current.privacy.appCapabilities.bluetoothSync",
    enableCmd: "Set-AppCapabilityAccess",
    disableCmd: "Set-AppCapabilityAccess",
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    defaultOn: true,
    minExperience: "simple",
    privacyScore: 2,
    privacyScoreCategory: "capabilities",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    icon: "flow-branch",
  },

];

export const CAPABILITY_TOGGLES: ToggleDef[] = CAPABILITY_TOGGLES_RAW.map(withPrivacyVisibility);

