// src/registry/privacy.toggles.ts
//
// ═══════════════════════════════════════════════════════════════════════
// PRIVACY DOMAIN — Toggle Registry (SINGLE SOURCE OF TRUTH)
// ═══════════════════════════════════════════════════════════════════════
//
// Every toggle in the Privacy panel's "Privacy & Tracking" section lives here.
// Each object is a complete definition: UI, backend, scores, radar, setup,
// fleet compliance — everything. No other file needs to know about these.
//
// NOTE: The privacy panel also contains:
//   - Privacy Shield (complex AI-powered feature with sliders, config dialog)
//   - Trace Auditing (action buttons that open dialogs, not on/off toggles)
//   - Deep DFIR (destructive erase actions that open viewer dialogs)
//   - App Capability Privacy (uses capabilityKey mechanism — separate section below)
//
// HOW SCORES WORK:
//   - privacyScore: contributes to Privacy Score (100 pts total, all users)
//   - cleanupScore: contributes to Cleanup Score (100 pts, cleanup mode only)
//   - Both are auto-summed by the registry helpers. No manual wiring.
//
// HOW RADAR WORKS:
//   - radar: true -> toggle appears in dashboard radar scan + Help & Setup scan
//   - When currentPath reads false/null → a finding is emitted with radarCategory/radarSeverity/impact
//
// HOW SETUP WORKS:
//   - defaultOn: true -> toggle is set to true in ideal state during setup (the "ON" in "ON L1")
//   - alwaysApplyOnFirstRun: true -> forced during setup regardless of scan results

import type { ToggleDef, SectionDef } from "../types/toggles";

function withPrivacyVisibility(toggle: ToggleDef): ToggleDef {
  return {
    ...toggle,
    capability: toggle.capability ?? ["privacy"],
    minDensity:
      toggle.minDensity ??
      (toggle.minExperience === "advanced" ? "expert" : "guided"),
  };
}

// ── Section Definitions ───────────────────────────────────────────────

export const PRIVACY_SECTIONS: SectionDef[] = [
  { id: "tracking", title: "Privacy & Tracking", icon: "shield", columns: 2 },
];

// ── Toggle Definitions ────────────────────────────────────────────────

const PRIVACY_TOGGLES_RAW: ToggleDef[] = [
  // ════════════════════════════════════════════════════════════════════
  //  PRIVACY & TRACKING — The main grid of 19 toggles
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "telemetry",
    label: "Block Telemetry",
    description: "Windows + Office telemetry and usage data",
    modeText: {
      simple: { label: "Stop Tracking", description: "Blocks Windows and Office from sending usage data back to Microsoft." },
      advanced: { label: "Block Telemetry", description: "Windows + Office telemetry and usage data" },
    },
    impact: "Microsoft collects usage data, typing patterns, and app activity",
    icon: "satellite",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.telemetry.windowsDisabled",
    currentPath: "current.privacy.telemetry.windowsDisabled",
    enableCmd: "Disable-Telemetry",
    disableCmd: "Enable-Telemetry",
    statusCmd: "Get-TelemetryStatus",
    // Visibility
    defaultOn: true,
    safeDefault: true,
    minExperience: "simple",
    // Radar
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    // Privacy Score
    privacyScore: 9,
    privacyScoreCategory: "telemetry",
    keywords: ["ms", "microsoft", "office", "powershell", "data collection", "phone home"],
    // Fleet
    complianceWeight: "required",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "clipboardHistory",
    label: "Disable Clipboard History",
    description: "No Win+V local history",
    modeText: {
      simple: { label: "Disable Clipboard History", description: "Stops Windows from saving the things you copied." },
      advanced: { label: "Disable Clipboard History", description: "No Win+V local history" },
    },
    icon: "clipboard",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.clipboard.historyDisabled",
    currentPath: "current.privacy.clipboard.historyDisabled",
    enableCmd: "Disable-ClipboardHistory",
    disableCmd: "Enable-ClipboardHistory",
    statusCmd: "Get-ClipboardHistoryStatus",
    minExperience: "standard",
    impact: "Clipboard history log stores everything you've copied",
    radar: true,
    radarRequiresAntiCleanup: true,
    safeDefault: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 3,
    privacyScoreCategory: "surface",
    cleanupScore: 5,
    cleanupScoreCategory: "behavior",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "cloudClipboard",
    label: "Disable Cloud Clipboard Sync",
    description: "Block cross-device clipboard",
    modeText: {
      simple: { label: "Disable Clipboard Sync", description: "Stops copied text from syncing across devices." },
      advanced: { label: "Disable Cloud Clipboard Sync", description: "Block cross-device clipboard" },
    },
    icon: "cloud-upload",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.clipboard.cloudSyncDisabled",
    currentPath: "current.privacy.clipboard.cloudSyncDisabled",
    enableCmd: "Disable-CloudClipboardSync",
    disableCmd: "Enable-CloudClipboardSync",
    defaultOn: true,
    safeDefault: true,
    minExperience: "standard",
    impact: "Clipboard contents sync to other devices via Microsoft servers",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 6,
    privacyScoreCategory: "telemetry",
    complianceWeight: "recommended",
  },
  // ── REMOVED: clipboardSchedule, rdpSchedule, eventLogSchedule ────
  // These three single-purpose toggles have been replaced by the
  // per-card auto-erase picker on the Privacy Clean panel
  // (Set-AutoEraseSchedule with categoryId = 'clipboard' | 'rdpHistory'
  // | 'eventLogs'). Existing scheduled tasks are migrated on first
  // panel mount via Invoke-AutoEraseMigration — see commander/src/
  // panels/cleanup/index.tsx and privacy/cleanup.ps1.
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "recentFiles",
    label: "Disable Recent Files",
    description: "Stop Explorer tracking",
    modeText: {
      simple: { label: "Disable Recent Files", description: "Stops Windows Explorer from showing and remembering recently opened files." },
      advanced: { label: "Disable Recent Files", description: "Stop Explorer Quick Access/MRU tracking" },
    },
    icon: "document",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.recentFilesDisabled",
    currentPath: "current.privacy.tracking.recentFilesDisabled",
    enableCmd: "Disable-RecentFilesTracking",
    disableCmd: "Enable-RecentFilesTracking",
    statusCmd: "Get-PrivacyProtectionStatus",
    defaultOn: true,
    safeDefault: true,
    minExperience: "simple",
    impact: "File Explorer records every recently opened file and folder",
    radar: true,
    radarRequiresAntiCleanup: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 2,
    privacyScoreCategory: "hardening",
    cleanupScore: 7,
    cleanupScoreCategory: "behavior",
    keywords: ["history", "explorer", "tracking", "traces", "files"],
    complianceWeight: "recommended",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "jumpLists",
    label: "Disable Jump Lists",
    description: "No taskbar history",
    modeText: {
      simple: { label: "Stop App History", description: "Stops taskbar and Start menu app history from being saved." },
      advanced: { label: "Disable Jump Lists", description: "No taskbar/Start menu MRU history" },
    },
    icon: "list-detail-view",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.jumpListsDisabled",
    currentPath: "current.privacy.tracking.jumpListsDisabled",
    enableCmd: "Disable-JumpLists",
    disableCmd: "Enable-JumpLists",
    statusCmd: "Get-PrivacyProtectionStatus",
    defaultOn: true,
    minExperience: "standard",
    impact: "Taskbar and Start menu store history of recently used files per app",
    radar: true,
    radarRequiresAntiCleanup: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 4,
    privacyScoreCategory: "surface",
    cleanupScore: 8,
    cleanupScoreCategory: "behavior",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "thumbnailCache",
    label: "Disable Thumbnail Cache",
    description: "No image caching",
    modeText: {
      simple: { label: "Disable Thumbnail Cache", description: "Stops Windows from saving preview images for files and folders." },
      advanced: { label: "Disable Thumbnail Cache", description: "No image/video caching in thumbs.db" },
    },
    icon: "media",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.thumbnailCacheDisabled",
    currentPath: "current.privacy.tracking.thumbnailCacheDisabled",
    enableCmd: "Disable-ThumbnailCache",
    disableCmd: "Enable-ThumbnailCache",
    statusCmd: "Get-PrivacyProtectionStatus",
    minExperience: "standard",
    impact: "Windows caches image previews in thumbs.db — reveals which files were viewed",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "info",
    privacyScore: 2,
    privacyScoreCategory: "surface",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "activity",
    label: "Disable Activity History",
    description: "Stop tracking app usage",
    modeText: {
      simple: { label: "Disable Activity History", description: "Stops Windows from recording which apps, files, and websites were used." },
      advanced: { label: "Disable Activity History", description: "Stop tracking app usage and Timeline data" },
    },
    impact: "Windows records every app, file, and website you open",
    icon: "history",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.telemetry.activityHistoryDisabled",
    currentPath: "current.privacy.telemetry.activityHistoryDisabled",
    enableCmd: "Disable-ActivityHistory",
    disableCmd: "Enable-ActivityHistory",
    statusCmd: "Get-HardeningStatus",
    defaultOn: true,
    safeDefault: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    privacyScore: 8,
    privacyScoreCategory: "telemetry",
    complianceWeight: "required",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "location",
    label: "Disable Location Tracking",
    description: "Block location access",
    modeText: {
      simple: { label: "Disable Location", description: "Stops apps and Windows from using your location." },
      advanced: { label: "Disable Location Tracking", description: "Block system location service access" },
    },
    impact: "Apps and Microsoft track your physical location",
    icon: "map-marker",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.telemetry.locationTrackingDisabled",
    currentPath: "current.privacy.telemetry.locationTrackingDisabled",
    enableCmd: "Disable-LocationTracking",
    disableCmd: "Enable-LocationTracking",
    statusCmd: "Get-HardeningStatus",
    defaultOn: true,
    safeDefault: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    privacyScore: 7,
    privacyScoreCategory: "telemetry",
    complianceWeight: "required",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "suggestions",
    label: "Disable Windows Suggestions",
    description: "Block tips, setup nags, timeline ads",
    modeText: {
      simple: { label: "Turn Off Tips", description: "Removes Windows tips, nudges, ads, and setup prompts." },
      advanced: { label: "Disable Windows Suggestions", description: "Block tips, setup nags, timeline ads" },
    },
    impact: "Microsoft shows tips, ads, and setup nags in the OS",
    icon: "lightbulb",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.telemetry.windowsSuggestionsDisabled",
    currentPath: "current.privacy.telemetry.windowsSuggestionsDisabled",
    enableCmd: "Disable-WindowsSuggestions",
    disableCmd: "Enable-WindowsSuggestions",
    statusCmd: "Get-WindowsSuggestionsStatus",
    defaultOn: true,
    safeDefault: true,
    alwaysApplyOnFirstRun: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 6,
    privacyScoreCategory: "surface",
    complianceWeight: "recommended",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "lockScreenPrivacy",
    label: "Lock Screen Privacy",
    description: "Disable spotlight + lock toast",
    modeText: {
      simple: { label: "Lock Screen Privacy", description: "Removes Spotlight, tips, and noisy content from the lock screen." },
      advanced: { label: "Lock Screen Privacy", description: "Disable Spotlight + lock screen notifications" },
    },
    icon: "lock",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.lockscreen.privacyDisabled",
    currentPath: "current.privacy.lockscreen.privacyDisabled",
    enableCmd: "Disable-LockScreenPrivacy",
    disableCmd: "Enable-LockScreenPrivacy",
    statusCmd: "Get-LockScreenPrivacyStatus",
    defaultOn: true,
    safeDefault: true,
    minExperience: "simple",
    impact: "Lock screen shows Spotlight content and notification previews",
    radar: false,
    radarCategory: "privacy",
    radarSeverity: "info",
    privacyScore: 4,
    privacyScoreCategory: "surface",
    keywords: ["toast", "notifications", "spotlight"],
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "recallSnapshots",
    label: "Disable Recall Snapshots",
    description: "Block Windows AI from taking screen snapshots",
    modeText: {
      simple: { label: "Disable Recall", description: "Stops Windows Recall style screen snapshots from being stored." },
      advanced: { label: "Disable Recall Snapshots", description: "Block AI-powered screen capture history" },
    },
    impact: "Windows takes periodic screenshots of your screen",
    icon: "eye-off",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.recallSnapshotsDisabled",
    currentPath: "current.privacy.tracking.recallSnapshotsDisabled",
    enableCmd: "Disable-RecallSnapshots",
    disableCmd: "Enable-RecallSnapshots",
    defaultOn: true,
    safeDefault: true,
    alwaysApplyOnFirstRun: true,
    minExperience: "standard",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    privacyScore: 3,
    privacyScoreCategory: "telemetry",
    cleanupScore: 10,
    cleanupScoreCategory: "traces",
    complianceWeight: "required",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "typingInsights",
    label: "Disable Typing Insights",
    description: "Stop keyboard input data collection",
    modeText: {
      simple: { label: "Stop Keystroke Tracking", description: "Stops Windows from analyzing typing behavior." },
      advanced: { label: "Disable Typing Insights", description: "Stop keyboard interaction data collection" },
    },
    impact: "Windows analyzes typing patterns (localized keylogger)",
    icon: "key-tab",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.typingInsightsDisabled",
    currentPath: "current.privacy.tracking.typingInsightsDisabled",
    enableCmd: "Disable-TypingInsights",
    disableCmd: "Enable-TypingInsights",
    defaultOn: true,
    safeDefault: true,
    alwaysApplyOnFirstRun: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    privacyScore: 2,
    privacyScoreCategory: "telemetry",
    complianceWeight: "required",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "internetComm",
    label: "Restrict Internet Comms",
    description: "Block 30+ background phone-home features",
    modeText: {
      simple: { label: "Block Background Traffic", description: "Blocks many background Microsoft and Windows online connections." },
      advanced: { label: "Restrict Internet Comms", description: "Block 30+ background phone-home features" },
    },
    icon: "globe-network",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.internetCommunication.restrictedEnabled",
    currentPath: "current.privacy.internetCommunication.restrictedEnabled",
    enableCmd: "Disable-InternetCommunication",
    disableCmd: "Enable-InternetCommunication",
    minExperience: "advanced",
    impact: "30+ Windows background features send data to Microsoft servers",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 5,
    privacyScoreCategory: "surface",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "advertisingId",
    label: "Nuke Advertising ID",
    description: "Delete ad ID + disable via policy",
    modeText: {
      simple: { label: "Remove Ad ID", description: "Deletes the advertising ID used to profile the user across apps." },
      advanced: { label: "Nuke Advertising ID", description: "Delete ad ID + disable via policy" },
    },
    impact: "Unique ID lets advertisers profile and track you across apps",
    icon: "id-number",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.advertisingIdDisabled",
    currentPath: "current.privacy.tracking.advertisingIdDisabled",
    enableCmd: "Disable-AdvertisingID",
    disableCmd: "Enable-AdvertisingID",
    statusCmd: "Get-HardeningStatus",
    defaultOn: true,
    safeDefault: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "critical",
    privacyScore: 4,
    privacyScoreCategory: "surface",
    complianceWeight: "required",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "tailoredExp",
    label: "Disable Tailored Experiences",
    description: "Stop diagnostic data personalization",
    modeText: {
      simple: { label: "Turn Off Personalization", description: "Stops Microsoft from personalizing content using diagnostics data." },
      advanced: { label: "Disable Tailored Experiences", description: "Stop diagnostic data personalization" },
    },
    impact: "Microsoft personalizes ads using your diagnostic data",
    icon: "target",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.tailoredExperiencesDisabled",
    currentPath: "current.privacy.tracking.tailoredExperiencesDisabled",
    enableCmd: "Disable-TailoredExperiences",
    disableCmd: "Enable-TailoredExperiences",
    statusCmd: "Get-HardeningStatus",
    defaultOn: true,
    safeDefault: true,
    minExperience: "standard",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 3,
    privacyScoreCategory: "telemetry",
    complianceWeight: "recommended",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "officeLog",
    label: "Disable Office Logging",
    description: "Kill Office telemetry + Click-to-Run logs",
    modeText: {
      simple: { label: "Reduce Office Tracking", description: "Reduces Microsoft Office usage logging and telemetry." },
      advanced: { label: "Disable Office Logging", description: "Kill Office telemetry + Click-to-Run logs" },
    },
    impact: "Microsoft Office sends detailed usage data to Microsoft",
    icon: "applications",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.officeLoggingDisabled",
    currentPath: "current.privacy.tracking.officeLoggingDisabled",
    enableCmd: "Disable-OfficeLogging",
    disableCmd: "Enable-OfficeLogging",
    statusCmd: "Get-HardeningStatus",
    defaultOn: true,
    minExperience: "standard",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
  },
  {
    // Diagnostic Tracing is opt-in for SETUP — disabling ETW (SleepStudy,
    // Power, WiFi sessions) measurably impacts perf diagnostics and several
    // Windows troubleshooters, so setup must NOT preselect it (defaultOn:false).
    // The radar DOES surface it in "Needs Attention" when OFF so advanced users
    // who want it disabled get the nudge; it stays a manual, deliberate choice.
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "diagTracing",
    label: "Disable Diagnostic Tracing",
    description: "Stop Windows background diagnostic recording",
    modeText: {
      simple: { label: "Disable System Traces", description: "Stops detailed Windows diagnostic event traces from being stored." },
      advanced: { label: "Disable Diagnostic Tracing", description: "Stop Windows background diagnostic recording" },
    },
    impact: "Windows background diagnostics log detailed system activity",
    icon: "diagnosis",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.diagnosticEventTracingDisabled",
    currentPath: "current.privacy.tracking.diagnosticEventTracingDisabled",
    enableCmd: "Disable-DiagnosticEventTracing",
    disableCmd: "Enable-DiagnosticEventTracing",
    statusCmd: "Get-HardeningStatus",
    defaultOn: false,
    minExperience: "advanced",
    radar: true,
    cleanupScore: 8,
    cleanupScoreCategory: "traces",
  },

  // ════════════════════════════════════════════════════════════════════
  //  Phase E — hide-recent toggles (HKCU writes, no admin required)
  // ════════════════════════════════════════════════════════════════════
  // Slot under the existing "tracking" section alongside recentFiles +
  // jumpLists + clipboardHistory. Each one disables a specific MRU
  // surface that recentFiles / jumpLists don't already cover.

  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "hideQuickAccessRecent",
    label: "Hide Recent Files in Quick Access",
    description: "Stop File Explorer Home from listing recent files",
    impact: "File Explorer Home shows everything you've recently opened",
    icon: "history",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.quickAccessRecentDisabled",
    currentPath: "current.privacy.tracking.quickAccessRecentDisabled",
    enableCmd: "Disable-QuickAccessRecent",
    disableCmd: "Enable-QuickAccessRecent",
    statusCmd: "Get-QuickAccessRecentStatus",
    minExperience: "simple",
    radar: true,
    radarRequiresAntiCleanup: true,
    safeDefault: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 1,
    privacyScoreCategory: "surface",
    cleanupScore: 2,
    cleanupScoreCategory: "behavior",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "hideQuickAccessFrequent",
    label: "Hide Frequent Folders in Quick Access",
    description: "Stop File Explorer Home from listing frequent folders",
    impact: "File Explorer Home reveals which folders you visit most often",
    icon: "folder-open",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.quickAccessFrequentDisabled",
    currentPath: "current.privacy.tracking.quickAccessFrequentDisabled",
    enableCmd: "Disable-QuickAccessFrequent",
    disableCmd: "Enable-QuickAccessFrequent",
    statusCmd: "Get-QuickAccessFrequentStatus",
    minExperience: "simple",
    radar: true,
    radarRequiresAntiCleanup: true,
    safeDefault: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 1,
    privacyScoreCategory: "surface",
    cleanupScore: 2,
    cleanupScoreCategory: "behavior",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "hideRunMRU",
    label: "Don't Save Run Dialog History",
    description: "Win+R dropdown forgets typed commands; existing entries cleared",
    impact: "Win+R history reveals every command / path you've executed",
    icon: "console",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.runMruDisabled",
    currentPath: "current.privacy.tracking.runMruDisabled",
    enableCmd: "Disable-RunMRU",
    disableCmd: "Enable-RunMRU",
    statusCmd: "Get-RunMRUStatus",
    minExperience: "standard",
    radar: true,
    radarRequiresAntiCleanup: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 2,
    privacyScoreCategory: "surface",
    cleanupScore: 3,
    cleanupScoreCategory: "behavior",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "disableSearchHistory",
    label: "Disable Search Box History",
    description: "Stop Windows Search from saving recent searches",
    impact: "Windows Search box stores every query you type",
    icon: "search",
    section: "tracking",
    domain: "privacy",
    settingsPath: "ideal.privacy.tracking.searchHistoryDisabled",
    currentPath: "current.privacy.tracking.searchHistoryDisabled",
    enableCmd: "Disable-SearchHistory",
    disableCmd: "Enable-SearchHistory",
    statusCmd: "Get-SearchHistoryStatus",
    minExperience: "simple",
    radar: true,
    radarRequiresAntiCleanup: true,
    safeDefault: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 2,
    privacyScoreCategory: "surface",
    cleanupScore: 2,
    cleanupScoreCategory: "behavior",
  },
];

export const PRIVACY_TOGGLES: ToggleDef[] = PRIVACY_TOGGLES_RAW.map(withPrivacyVisibility);
