import type { IconName } from "@/components/ui/bp";
import type { ToggleDef } from "../types/toggles";

// Some established catalog rows predate tile icons. Keep their visual identity
// here rather than duplicating label-based guesses across every panel.
const CATALOG_TOGGLE_ICONS: Readonly<Record<string, IconName>> = {
  classicMenu: "list-detail-view",
  ext: "document",
  hidden: "eye-open",
  endtask: "stop",
  gallery: "media",
  bing: "search",
  notifications: "notifications",
  backgroundApps: "applications",
  folderDisc: "folder-shared",
  shortcutSuffix: "annotation",
  autoplay: "play",
  lowDisk: "hard-drive",
  explorerPC: "desktop",
  syncNotif: "cloud",
  transparency: "sun",
  fullPath: "folder-open",
  taskbarDebloat: "layout-grid",
  startRec: "lightbulb",
  superfetch: "flash",
  hibernation: "moon",
  fastStartup: "rocket-slant",
  ntfsOpt: "wrench",
  pagefile: "database",
  prefetch: "download",
  reservedStorage: "archive",
  automaticMaintenance: "automatic-updates",
  win32LongPaths: "folder-shared-open",
  smbBandwidthThrottling: "data-connection",
  detailedBSOD: "issue",
  tsx: "code",
  firstLogon: "log-in",
  startupSound: "music",
  autoRestartSignon: "repeat",
  autoRebootBsod: "reset",
  smallMemDump: "document-open",
  rdpKeepAlive: "pulse",
  rdpNoTimeouts: "time",
  rdpQosPriority: "timeline-events",
  amdPowerGating: "power",
  amdClockGating: "video",
  amdAspm: "offline",
  nvDynamicPstate: "flash",
  nvAsyncPstates: "random",
  intelAsyncFlips: "shuffle",
  intelAdaptiveVsync: "refresh",
  icoThisPc: "desktop",
  icoRecycle: "trash",
  icoUserFiles: "user",
  icoNetwork: "network",
  icoControl: "cog",
  shortcutArrow: "arrow-right",
  snapFlyout: "layout-grid",
  explorerCompact: "folder-close",
  fileCheckboxes: "selection",
  windowShake: "hand",
  clockSeconds: "stopwatch",
  contextMenuShred: "trash",
  contextMenuScrub: "eraser",
  serverPersistentRdpAnimations: "presentation",
  serverCtrlAltDel: "key-command",
  serverHideLastUser: "user",
  serverConsoleLock: "lock",
  serverShutdownTracker: "document",
  serverManagerLogon: "log-in",
  serverIeEsc: "shield",
  serverWdigest: "fingerprint",
  serverLsaProtection: "shield-check",
  serverLegacyNtlm: "ban-circle",
  serverSmbSigning: "key",
  serverSmb1: "network",
  serverRemoteRegistry: "database",
  acquisitionDriverBlocklist: "shield-alert",
  forensicToolBlock: "hard-drive",
  depEnabled: "shield",
  aslrMandatory: "target",
  aslrBottomUp: "arrow-up",
  cfgEnabled: "flow-branch",
  heapIntegrity: "cube",
  sehopEnabled: "shield-check",
  asrRules: "filter",
  controlledFolderAccess: "folder-close",
  networkProtection: "globe-network",
  "argus-app-usage": "history",
  "argus-dlp": "clipboard",
  "argus-tamper": "shield-alert",
  "argus-print-usb": "print",
};

export function resolveToggleIcon(toggle: ToggleDef): IconName {
  return toggle.icon ?? CATALOG_TOGGLE_ICONS[toggle.id] ?? "help";
}
