// src/registry/tweaks.toggles.ts
//
// ═══════════════════════════════════════════════════════════════════════
// TWEAKS DOMAIN — Toggle Registry (SINGLE SOURCE OF TRUTH)
// ═══════════════════════════════════════════════════════════════════════
//
// Every toggle in the Tweaks panel is defined here as a plain data object.
// One row = one setting. Score, radar, setup, visibility, fleet — all
// auto-derive from these definitions. Zero wiring.
//
// TO ADD A NEW TWEAK: Copy any object below, change the fields, done.
//
// HOW DATA FLOWS:
//   1. ToggleSection reads this array
//   2. For each toggle, it reads `checked` from currentPath in settings.current
//   3. On flip, it calls enableCmd/disableCmd via executeBackendCommand
//   4. The UI updates optimistically (instant), then confirms via next probe

import type { ToggleDef, SectionDef } from "../types/toggles";
import { commandId } from "../lib/commandIds";

// ── Section Definitions ──────────────────────────────────────────────

export const TWEAKS_SECTIONS: SectionDef[] = [
  { id: "ui",          title: "UI Tweaks",              icon: "style",       columns: 2 },
  { id: "security",    title: "Security & Apps",        icon: "shield",      columns: 2 },
  { id: "os",          title: "OS / Hardware Tweaks",   icon: "cog",         columns: 2 },
  { id: "boot",        title: "Boot & Kernel",          icon: "power",       columns: 2 },
  { id: "performance", title: "Performance & Gaming",    icon: "rocket",      columns: 2 },
  { id: "gpu",         title: "GPU Vendor Tweaks",      icon: "desktop",     columns: 2 },
  { id: "power",       title: "Power Management",       icon: "offline",     columns: 2 },
  // NOTE: the tweaks panel references TWEAKS_SECTIONS by numeric index, so new
  // sections MUST be appended here (never inserted mid-array). Exploit Protection
  // is rendered explicitly in src/panels/tweaks/index.tsx (index 7).
  { id: "exploitProtection", title: "Exploit Protection", icon: "shield",   columns: 2 },
];

// ── Toggle Definitions ───────────────────────────────────────────────

export const TWEAKS_TOGGLES: ToggleDef[] = [
  // ════════════════════════════════════════════════════════════════════
  //  UI TWEAKS — Visual / Explorer / Desktop changes
  //  All HKCU writes — tier: "free", needsAdmin: false
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "classicMenu",
    label: "Classic Context Menu",
    description: "Windows 10 style menu",
    modeText: {
      simple: { label: "Classic Right-Click", description: "Restores the old, faster right-click menu." },
      advanced: { label: "Classic Context Menu", description: "Disable Win11 modern context menu" },
    },
    impact: "Win11 hides options behind 'Show more options'",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.classicContextMenu",
    currentPath: "current.tweaks.ui.classicContextMenu",
    enableCmd: "Enable-ClassicContextMenu",
    disableCmd: "Disable-ClassicContextMenu",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    defaultOn: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "annoyance",
    radarSeverity: "info",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "ext",
    label: "Show File Extensions",
    description: "Display .txt, .exe, etc.",
    impact: "Can't distinguish .exe from .pdf — security risk",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.fileExtensionsVisible",
    currentPath: "current.tweaks.ui.fileExtensionsVisible",
    enableCmd: "Show-FileExtensions",
    disableCmd: "Hide-FileExtensions",
    statusCmd: "Get-HardeningStatus",
    defaultOn: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "annoyance",
    radarSeverity: "info",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "hidden",
    label: "Show Hidden Files",
    description: "Display hidden files",
    impact: "Hidden files concealed in Explorer",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.hiddenFilesVisible",
    currentPath: "current.tweaks.ui.hiddenFilesVisible",
    enableCmd: "Show-HiddenFiles",
    disableCmd: "Hide-HiddenFiles",
    statusCmd: "Get-HardeningStatus",
    defaultOn: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "annoyance",
    radarSeverity: "info",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "endtask",
    label: "'End Task' on Taskbar",
    description: "Right-click to kill apps",
    impact: "Cannot kill rogue / hung apps from the taskbar without Task Manager",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.endTaskOnTaskbar",
    currentPath: "current.tweaks.ui.endTaskOnTaskbar",
    enableCmd: "Enable-EndTaskOnTaskbar",
    disableCmd: "Disable-EndTaskOnTaskbar",
    statusCmd: "Get-HardeningStatus",
    minExperience: "simple",
    radar: true,
    radarCategory: "annoyance",
    radarSeverity: "info",
    privacyScore: 1,
    privacyScoreCategory: "hardening",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "gallery",
    label: "Remove Gallery & Home",
    description: "Clean up File Explorer",
    impact: "Gallery + Home pin OneDrive recents, photo previews, and recent files",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.galleryHomeRemoved",
    currentPath: "current.tweaks.ui.galleryHomeRemoved",
    enableCmd: "Enable-RemoveGalleryHome",
    disableCmd: "Disable-RemoveGalleryHome",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    defaultOn: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 2,
    privacyScoreCategory: "hardening",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "bing",
    label: "Disable Bing Search",
    description: "Remove web results from Start",
    modeText: {
      simple: { label: "Disable Start Menu Search", description: "Stops the Start menu from showing web results from Bing." },
      advanced: { label: "Disable Bing Search", description: "Stop Start menu web search integration" },
    },
    impact: "Start Menu queries go through Bing servers",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.bingSearchDisabled",
    currentPath: "current.tweaks.ui.bingSearchDisabled",
    enableCmd: "Disable-BingSearch",
    disableCmd: "Enable-BingSearch",
    statusCmd: "Get-HardeningStatus",
    defaultOn: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 4,
    privacyScoreCategory: "surface",
    complianceWeight: "recommended",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "notifications",
    label: "Disable Notifications",
    description: "Block all desktop notifications",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.notificationsDisabled",
    currentPath: "current.tweaks.ui.notificationsDisabled",
    enableCmd: "Disable-Notifications",
    disableCmd: "Enable-Notifications",
    statusCmd: "Get-HardeningStatus",
    minExperience: "standard",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "backgroundApps",
    label: "Disable Background Apps",
    description: "Stop apps running silently",
    impact: "Apps run silently consuming CPU and RAM",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.backgroundAppsDisabled",
    currentPath: "current.tweaks.ui.backgroundAppsDisabled",
    enableCmd: "Disable-BackgroundApps",
    disableCmd: "Enable-BackgroundApps",
    statusCmd: "Get-HardeningStatus",
    defaultOn: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "performance",
    radarSeverity: "warning",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "folderDisc",
    label: "Disable Folder Discovery",
    description: "Stop auto-detecting folder types",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.folderTypeDiscoveryDisabled",
    currentPath: "current.tweaks.ui.folderTypeDiscoveryDisabled",
    enableCmd: "Disable-FolderTypeDiscovery",
    disableCmd: "Enable-FolderTypeDiscovery",
    minExperience: "standard",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "shortcutSuffix",
    label: "Remove Shortcut Suffix",
    description: "No ' - Shortcut' on new links",
    impact: "New shortcuts always include the ' - Shortcut' suffix",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.shortcutSuffixRemoved",
    currentPath: "current.tweaks.ui.shortcutSuffixRemoved",
    enableCmd: "Remove-ShortcutSuffix",
    disableCmd: "Restore-ShortcutSuffix",
    minExperience: "standard",
    radar: true,
    radarCategory: "annoyance",
    radarSeverity: "info",
    privacyScore: 1,
    privacyScoreCategory: "surface",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "autoplay",
    label: "Disable AutoPlay",
    description: "Block auto-run on USB/media",
    impact: "Inserted USB/media auto-runs executables — classic infection vector",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.autoPlayDisabled",
    currentPath: "current.tweaks.ui.autoPlayDisabled",
    enableCmd: "Disable-AutoPlay",
    disableCmd: "Enable-AutoPlay",
    minExperience: "standard",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 3,
    privacyScoreCategory: "hardening",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "lowDisk",
    label: "Disable Low Disk Check",
    description: "Suppress low disk warnings",
    impact: "Low-disk warning balloons appear periodically",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.lowDiskCheckDisabled",
    currentPath: "current.tweaks.ui.lowDiskCheckDisabled",
    enableCmd: "Disable-LowDiskCheck",
    disableCmd: "Enable-LowDiskCheck",
    minExperience: "standard",
    radar: true,
    radarCategory: "annoyance",
    radarSeverity: "info",
    privacyScore: 1,
    privacyScoreCategory: "surface",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "explorerPC",
    label: "Explorer Opens This PC",
    description: "Open to This PC instead of Quick Access",
    impact: "Quick Access tracks your most-used folders + recent files",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.explorerOpensThisPc",
    currentPath: "current.tweaks.ui.explorerOpensThisPc",
    enableCmd: "Set-ExplorerOpensThisPC",
    disableCmd: "Set-ExplorerOpensQuickAccess",
    minExperience: "standard",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 2,
    privacyScoreCategory: "surface",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "syncNotif",
    label: "Hide Sync Notifications",
    description: "No OneDrive/sync ads in Explorer",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.syncProviderNotificationsHidden",
    currentPath: "current.tweaks.ui.syncProviderNotificationsHidden",
    enableCmd: "Hide-SyncProviderNotifications",
    disableCmd: "Show-SyncProviderNotifications",
    minExperience: "standard",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "transparency",
    label: "Disable Transparency",
    description: "Turn off window transparency effects",
    impact: "Window glass effects consume GPU resources",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.transparencyDisabled",
    currentPath: "current.tweaks.ui.transparencyDisabled",
    enableCmd: "Disable-TransparencyEffects",
    disableCmd: "Enable-TransparencyEffects",
    alwaysApplyOnFirstRun: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "performance",
    radarSeverity: "info",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "fullPath",
    label: "Full Path in Title Bar",
    description: "Show complete path in Explorer",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.fullPathInTitleBar",
    currentPath: "current.tweaks.ui.fullPathInTitleBar",
    enableCmd: "Enable-FullPathInTitleBar",
    disableCmd: "Disable-FullPathInTitleBar",
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "taskbarDebloat",
    label: "Taskbar Debloated",
    description: "Hide Widgets, Search, Chat, Task View, Feeds",
    impact: "Widgets / Search / Chat / News taskbar items phone home and consume RAM",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.taskbarDebloated",
    currentPath: "current.tweaks.ui.taskbarDebloated",
    enableCmd: "Set-TaskbarDebloated",
    disableCmd: "Reset-TaskbarDebloated",
    defaultOn: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 3,
    privacyScoreCategory: "surface",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "startRec",
    label: "Disable Start Recommendations",
    description: "Remove suggested apps from Start menu",
    impact: "Start menu shows Microsoft Store ads + suggested apps",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.startRecommendationsDisabled",
    currentPath: "current.tweaks.ui.startRecommendationsDisabled",
    enableCmd: "Disable-StartRecommendations",
    disableCmd: "Enable-StartRecommendations",
    defaultOn: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 2,
    privacyScoreCategory: "surface",
  },

  // ════════════════════════════════════════════════════════════════════
  //  SECURITY & APPS — Defender, updates, USB lockdown, browser hardening
  //  Mixed tier — defender + usbwp + usbLockdown + bitlockerAuto are paid;
  //  uac/smartscreen/oobe/vbs are also paid (reducesSecurity:true ⇒ paid).
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: true,
    defenderFlagged: true,
    id: "defender",
    label: "Disable Windows Defender",
    description: "Turn off real-time protection",
    icon: "shield",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.defenderDisabled",
    currentPath: "current.tweaks.security.defenderDisabled",
    enableCmd: commandId("Disable-", "Windows", "Defender"),
    disableCmd: "Enable-WindowsDefender",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    minExperience: "advanced",
    privacyScore: 3,
    privacyScoreCategory: "hardening",
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: true,
    defenderFlagged: true,
    id: "updates",
    label: "Pause Updates",
    description: "Indefinitely (up to year 2038)",
    icon: "cloud-download",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.windowsUpdateDisabled",
    currentPath: "current.tweaks.security.windowsUpdateDisabled",
    enableCmd: "Disable-WindowsUpdate",
    disableCmd: "Enable-WindowsUpdate",
    statusCmd: "Get-HardeningStatus",
    minExperience: "standard",
    privacyScore: 4,
    privacyScoreCategory: "hardening",
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: true,
    defenderFlagged: true,
    id: "uac",
    label: "Disable UAC",
    description: "Turn off User Account Control",
    icon: "confirm",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.uacDisabled",
    currentPath: "current.tweaks.security.uacDisabled",
    enableCmd: "Disable-UAC",
    disableCmd: "Enable-UAC",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "usbwp",
    label: "USB Write Protect",
    description: "Prevent USB writing",
    icon: "floppy-disk",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.usbWriteProtect",
    currentPath: "current.tweaks.security.usbWriteProtect",
    enableCmd: "Enable-USBWriteProtect",
    disableCmd: "Disable-USBWriteProtect",
    statusCmd: "Get-HardeningStatus",
    minExperience: "advanced",
    conflictsWith: ["usbLockdown"],
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "usbLockdown",
    label: "USB Storage Lockdown",
    description: "Disable USB drives (reboot required)",
    icon: "drive-time",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.usbStorageLockdown",
    currentPath: "current.tweaks.security.usbStorageLockdown",
    enableCmd: "Enable-USBStorageLockdown",
    disableCmd: "Disable-USBStorageLockdown",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    minExperience: "advanced",
    conflictsWith: ["usbwp"],
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "consumerFeatures",
    label: "Disable Consumer Features",
    description: "Stop Microsoft silently installing suggested apps",
    impact: "Microsoft silently installs suggested apps",
    icon: "shopping-cart",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.consumerFeaturesDisabled",
    currentPath: "current.tweaks.security.consumerFeaturesDisabled",
    enableCmd: "Disable-ConsumerFeatures",
    disableCmd: "Enable-ConsumerFeatures",
    statusCmd: "Get-HardeningStatus",
    defaultOn: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "performance",
    radarSeverity: "warning",
    complianceWeight: "recommended",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "remoteAssistance",
    label: "Disable Remote Assistance",
    description: "Block inbound Remote Assistance invitations",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.remoteAssistanceDisabled",
    currentPath: "current.tweaks.security.remoteAssistanceDisabled",
    enableCmd: "Disable-RemoteAssistance",
    disableCmd: "Enable-RemoteAssistance",
    statusCmd: "Get-HardeningStatus",
    minExperience: "advanced",
    impact: "A remote helper can be invited to view or control this PC",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "info",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "anonymousSam",
    label: "Block Anonymous SAM Enumeration",
    description: "Hide local account names from unauthenticated network users",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.anonymousSamEnumerationBlocked",
    currentPath: "current.tweaks.security.anonymousSamEnumerationBlocked",
    enableCmd: "Block-AnonymousSamEnumeration",
    disableCmd: "Allow-AnonymousSamEnumeration",
    statusCmd: "Get-HardeningStatus",
    minExperience: "advanced",
    impact: "Anonymous callers may enumerate local account names over the network",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "info",
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: true,
    defenderFlagged: true,
    id: "vbs",
    label: "Disable VBS",
    description: "Turn off Virtualization-Based Security",
    icon: "cube",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.vbsDisabled",
    currentPath: "current.tweaks.security.vbsDisabled",
    enableCmd: "Disable-VBS",
    disableCmd: "Enable-VBS",
    minExperience: "advanced",
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "bitlockerAuto",
    label: "Disable BitLocker Auto-Encrypt",
    description: "Prevent automatic device encryption",
    icon: "lock",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.bitlockerAutoEncryptDisabled",
    currentPath: "current.tweaks.security.bitlockerAutoEncryptDisabled",
    enableCmd: "Disable-BitLockerAutoEncrypt",
    disableCmd: "Enable-BitLockerAutoEncrypt",
    minExperience: "advanced",
    impact: "Drive is not encrypted — data is accessible if device is lost or stolen",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
  },
  // Feature 5 — BitLocker TPM+PIN enforcement (reversible, security, free tier)
  // Adds a TPM+PIN protector and removes the bare-TPM protector so BitLocker
  // requires a PIN on every boot — protects against evil-maid/cold-boot attacks
  // where an attacker has physical access but doesn't know the PIN.
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "bitlockerTpmPinEnforce",
    label: "BitLocker TPM+PIN",
    description: "Require a PIN on every boot",
    icon: "lock",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.bitlockerTpmPinEnforce",
    currentPath: "current.tweaks.security.bitlockerTpmPinEnforce",
    enableCmd: "Set-BitLockerTpmPin",
    disableCmd: "Set-BitLockerTpmPin",
    requiresPinOnEnable: true,
    enableParamName: "Enable",
    extraCmdParams: { Drive: "C:" },
    minExperience: "advanced",
    impact: "Without a boot PIN, an attacker with physical access can extract the BitLocker key from TPM at cold-boot",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "wpbt",
    label: "Disable WPBT",
    description: "Block OEM BIOS software injection",
    icon: "warning-sign",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.wpbtDisabled",
    currentPath: "current.tweaks.security.wpbtDisabled",
    enableCmd: "Disable-WPBT",
    disableCmd: "Enable-WPBT",
    minExperience: "advanced",
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: true,
    defenderFlagged: true,
    id: "smartscreen",
    label: "Disable SmartScreen",
    description: "Turn off web content evaluation",
    icon: "filter",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.smartScreenDisabled",
    currentPath: "current.tweaks.security.smartScreenDisabled",
    enableCmd: "Disable-SmartScreen",
    disableCmd: "Enable-SmartScreen",
    minExperience: "advanced",
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: true,
    defenderFlagged: false,
    id: "oobe",
    label: "OOBE Bypass",
    description: "Skip Microsoft account during setup",
    icon: "log-in",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.oobeBypassEnabled",
    currentPath: "current.tweaks.security.oobeBypassEnabled",
    enableCmd: "Set-OOBEBypass",
    disableCmd: "Clear-OOBEBypass",
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "gameDVR",
    label: "Disable Game DVR",
    description: "Turn off Xbox game recording",
    impact: "Game Bar recording can run background capture services and use disk/GPU resources",
    icon: "video",
    section: "performance",
    domain: "security",
    settingsPath: "ideal.tweaks.security.gameDvrDisabled",
    currentPath: "current.tweaks.security.gameDvrDisabled",
    enableCmd: "Disable-GameDVR",
    disableCmd: "Enable-GameDVR",
    defaultOn: true,
    safeDefault: true,
    radar: true,
    radarCategory: "performance",
    radarSeverity: "info",
    minExperience: "standard",
    complianceWeight: "recommended",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "copilotAI",
    label: "Remove Copilot & AI",
    description: "Disable Copilot, Recall, app AI, services, and shell integrations",
    impact: "Copilot and bundled AI features add background services, prompts, local model access, and cloud-connected surfaces",
    icon: "clean",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.copilotAiRemoved",
    currentPath: "current.tweaks.security.copilotAiRemoved",
    enableCmd: "Remove-CopilotAIComponents",
    disableCmd: "Restore-CopilotAIComponents",
    defaultOn: true,
    safeDefault: true,
    alwaysApplyOnFirstRun: true,
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    minExperience: "simple",
    complianceWeight: "recommended",
  },

  // ════════════════════════════════════════════════════════════════════
  //  HOST HARDENING TOGGLES (Feature 4) — needsAdmin, default OFF.
  //  These six toggles harden the host against data leakage and DMA attacks.
  //  systemRestoreOff is paid (reducesSecurity:true, same as the other
  //  Disable-*-security toggles); the remaining five are free.
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: true,
    defenderFlagged: false,
    id: "systemRestoreOff",
    label: "Disable VSS / System Restore",
    description: "Turn off shadow copies and System Restore",
    impact: "Shadow copies are a ransomware-recovery safety net — disabling them removes that protection",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.systemRestoreOff",
    currentPath: "current.tweaks.security.systemRestoreOff",
    enableCmd: "Disable-SystemRestore",
    disableCmd: "Enable-SystemRestore",
    statusCmd: "Get-HardeningStatus",
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "recallOff",
    label: "Disable Windows Recall",
    description: "Block AI snapshot screen recording",
    impact: "Windows Recall continuously screenshots your screen and indexes it with AI",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.recallOff",
    currentPath: "current.tweaks.security.recallOff",
    enableCmd: "Disable-RecallSnapshots",
    disableCmd: "Enable-RecallSnapshots",
    statusCmd: "Get-HardeningStatus",
    defaultOn: false,
    minExperience: "standard",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 4,
    privacyScoreCategory: "hardening",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "crashDumpsOff",
    label: "Disable crash dumps",
    description: "Stop kernel + WER crash dump collection",
    impact: "Crash dumps can expose passwords, encryption keys, and session tokens on disk",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.crashDumpsOff",
    currentPath: "current.tweaks.security.crashDumpsOff",
    enableCmd: "Disable-CrashDumps",
    disableCmd: "Enable-CrashDumps",
    statusCmd: "Get-HardeningStatus",
    minExperience: "standard",
    radar: true,
    radarRequiresAntiCleanup: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    cleanupScore: 8,
    cleanupScoreCategory: "memory",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "clipboardHistoryOff",
    label: "Disable clipboard history",
    description: "Clear and block clipboard history logging",
    impact: "Clipboard history stores copied passwords, secrets, and sensitive text",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.clipboardHistoryOff",
    currentPath: "current.tweaks.security.clipboardHistoryOff",
    enableCmd: "Disable-ClipboardHistory",
    disableCmd: "Enable-ClipboardHistory",
    statusCmd: "Get-HardeningStatus",
    minExperience: "standard",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 3,
    privacyScoreCategory: "surface",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "requirePwOnResume",
    label: "Require password on resume + no sleep",
    description: "Lock screen on screensaver resume; disable AC sleep",
    impact: "Unattended sessions are unlocked after screen saver or sleep",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.requirePwOnResume",
    currentPath: "current.tweaks.security.requirePwOnResume",
    enableCmd: "Disable-SleepPassword",
    disableCmd: "Enable-SleepPassword",
    statusCmd: "Get-HardeningStatus",
    minExperience: "standard",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 3,
    privacyScoreCategory: "hardening",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "kernelDmaProtect",
    label: "Kernel DMA Protection",
    description: "Report status; opportunistic enable (requires firmware IOMMU)",
    impact: "Without DMA Protection, Thunderbolt/PCIe devices can read all RAM directly",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.kernelDmaProtect",
    currentPath: "current.tweaks.security.kernelDmaProtect",
    enableCmd: "Enable-KernelDMAProtection",
    disableCmd: "Disable-KernelDMAProtection",
    statusCmd: "Get-HardeningStatus",
    minExperience: "advanced",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 2,
    privacyScoreCategory: "hardening",
  },

  // ════════════════════════════════════════════════════════════════════
  //  ANTI-ACQUISITION DEFENSES — paid, needsAdmin, harden against forensic
  //  disk/memory acquisition tooling (e.g. winpmem, FTK Imager, KAPE).
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "acquisitionDriverBlocklist",
    label: "Vulnerable Driver Blocklist",
    description: "Enable Microsoft's auto-updated blocklist for known-vulnerable drivers",
    impact: "Vulnerable drivers can be loaded to bypass kernel protections and access raw memory or disk",
    section: "exploitProtection",
    domain: "security",
    settingsPath: "ideal.tweaks.security.acquisitionDriverBlocklist",
    currentPath: "current.tweaks.security.acquisitionDriverBlocklist",
    enableCmd: "Enable-AcquisitionDriverBlocklist",
    disableCmd: "Disable-AcquisitionDriverBlocklist",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    minExperience: "advanced",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 3,
    privacyScoreCategory: "hardening",
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: true,
    id: "forensicToolBlock",
    label: "Block Low-Level Disk/Memory Access Tools",
    description: "Block unapproved low-level disk and memory access tools from launching",
    impact: "Unapproved disk/memory access tools can copy the full disk or memory contents while the device is unlocked",
    section: "exploitProtection",
    domain: "security",
    settingsPath: "ideal.tweaks.security.forensicToolBlock",
    currentPath: "current.tweaks.security.forensicToolBlock",
    enableCmd: "Enable-ForensicToolBlock",
    disableCmd: "Disable-ForensicToolBlock",
    statusCmd: "Get-HardeningStatus",
    minExperience: "advanced",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 3,
    privacyScoreCategory: "hardening",
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "lidClosePowerOff",
    label: "Power Off on Lid Close",
    description: "Lid close fully shuts down the machine instead of sleeping",
    impact: "Sleep keeps the disk-encryption key resident in RAM, where memory-extraction attacks can target it. Shutdown clears the key and re-locks the disk.",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.lidClosePowerOff",
    currentPath: "current.tweaks.security.lidClosePowerOff",
    enableCmd: "Enable-LidClosePowerOff",
    disableCmd: "Disable-LidClosePowerOff",
    statusCmd: "Get-LidClosePowerOffStatus",
    minExperience: "advanced",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    privacyScore: 3,
    privacyScoreCategory: "hardening",
  },

  // ════════════════════════════════════════════════════════════════════
  //  EXPLOIT PROTECTION (Set-ProcessMitigation) — free, needsAdmin, system-
  //  wide process mitigation policy: DEP, ASLR, CFG, heap integrity, SEHOP.
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "depEnabled",
    label: "Data Execution Prevention (DEP)",
    description: "Force DEP for all processes so code cannot run from data pages",
    section: "exploitProtection",
    domain: "security",
    settingsPath: "ideal.tweaks.security.depEnabled",
    currentPath: "current.tweaks.security.depEnabled",
    enableCmd: "Enable-SystemDEP",
    disableCmd: "Disable-SystemDEP",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "aslrMandatory",
    label: "Mandatory ASLR",
    description: "Force address-space randomization for images not built with /DYNAMICBASE",
    section: "exploitProtection",
    domain: "security",
    settingsPath: "ideal.tweaks.security.aslrMandatory",
    currentPath: "current.tweaks.security.aslrMandatory",
    enableCmd: "Enable-MandatoryASLR",
    disableCmd: "Disable-MandatoryASLR",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "aslrBottomUp",
    label: "Bottom-Up ASLR",
    description: "Randomize bottom-up virtual memory allocations with high entropy",
    section: "exploitProtection",
    domain: "security",
    settingsPath: "ideal.tweaks.security.aslrBottomUp",
    currentPath: "current.tweaks.security.aslrBottomUp",
    enableCmd: "Enable-BottomUpASLR",
    disableCmd: "Disable-BottomUpASLR",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "cfgEnabled",
    label: "Control Flow Guard (CFG)",
    description: "Enforce indirect-call integrity system-wide",
    section: "exploitProtection",
    domain: "security",
    settingsPath: "ideal.tweaks.security.cfgEnabled",
    currentPath: "current.tweaks.security.cfgEnabled",
    enableCmd: "Enable-SystemCFG",
    disableCmd: "Disable-SystemCFG",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "heapIntegrity",
    label: "Heap Integrity",
    description: "Terminate a process when heap corruption is detected",
    section: "exploitProtection",
    domain: "security",
    settingsPath: "ideal.tweaks.security.heapIntegrity",
    currentPath: "current.tweaks.security.heapIntegrity",
    enableCmd: "Enable-HeapIntegrity",
    disableCmd: "Disable-HeapIntegrity",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "sehopEnabled",
    label: "SEH Overwrite Protection (SEHOP)",
    description: "Block structured-exception-handler overwrite exploits",
    section: "exploitProtection",
    domain: "security",
    settingsPath: "ideal.tweaks.security.sehopEnabled",
    currentPath: "current.tweaks.security.sehopEnabled",
    enableCmd: "Enable-SEHOP",
    disableCmd: "Disable-SEHOP",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "asrRules",
    label: "Attack Surface Reduction",
    description: "Enable Microsoft Defender ASR rules that block common exploit and malware behaviors",
    section: "exploitProtection",
    domain: "security",
    settingsPath: "ideal.tweaks.security.asrRulesEnabled",
    currentPath: "current.tweaks.security.asrRulesEnabled",
    enableCmd: "Enable-ASRRules",
    disableCmd: "Disable-ASRRules",
    statusCmd: "Get-HardeningStatus",
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "controlledFolderAccess",
    label: "Controlled Folder Access",
    description: "Block unauthorized apps from modifying protected folders (ransomware guard)",
    section: "exploitProtection",
    domain: "security",
    settingsPath: "ideal.tweaks.security.controlledFolderAccessEnabled",
    currentPath: "current.tweaks.security.controlledFolderAccessEnabled",
    enableCmd: "Enable-ControlledFolderAccess",
    disableCmd: "Disable-ControlledFolderAccess",
    statusCmd: "Get-HardeningStatus",
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "networkProtection",
    label: "Network Protection",
    description: "Block outbound connections to known-malicious hosts at the OS level",
    section: "exploitProtection",
    domain: "security",
    settingsPath: "ideal.tweaks.security.networkProtectionEnabled",
    currentPath: "current.tweaks.security.networkProtectionEnabled",
    enableCmd: "Enable-NetworkProtection",
    disableCmd: "Disable-NetworkProtection",
    statusCmd: "Get-HardeningStatus",
    minExperience: "advanced",
  },

  // ════════════════════════════════════════════════════════════════════
  //  RAM-SPILL CONTROL (Feature 3) — hibernation/fast-startup off + pagefile zero
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "ramSpillControl",
    label: "RAM-Spill Control",
    description: "Disable hibernation + fast-startup; zero pagefile on shutdown",
    impact: "Hibernation and fast-startup write RAM contents to disk, leaving recoverable memory artifacts; the pagefile leaks process memory across reboots",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.ramSpillControlEnabled",
    currentPath: "current.tweaks.security.ramSpillControlEnabled",
    enableCmd: "Enable-RamSpillControl",
    disableCmd: "Disable-RamSpillControl",
    statusCmd: "Get-HardeningStatus",
    defaultOn: false,
    minExperience: "standard",
    radar: true,
    radarRequiresAntiCleanup: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    cleanupScore: 12,
    cleanupScoreCategory: "memory",
    privacyScore: 4,
    privacyScoreCategory: "hardening",
  },

  // ════════════════════════════════════════════════════════════════════
  //  SECURE SHRED CONTROLS (Feature 1) — media-aware shred policy
  //  shredPasses + shredMediaAware are free; shredMftSlack is paid.
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "shredMediaAware",
    label: "Media-aware shred (SSD = 1-pass + TRIM)",
    description: "Forces 1-pass on SSD/NVMe — multi-pass adds wear, not security",
    impact: "Multi-pass shred on SSD/NVMe wears flash cells without forensic benefit; the controller FTL may not overwrite the same physical cells regardless",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.shredMediaAwareEnabled",
    currentPath: "current.tweaks.security.shredMediaAwareEnabled",
    enableCmd: "Set-ShredPolicy",
    disableCmd: "Set-ShredPolicy",
    minExperience: "standard",
    defaultOn: false,
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: true,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "shredMftSlack",
    label: "Wipe MFT-resident & file-slack remnants",
    description: "Zero the MFT data attribute of small files + pad cluster slack",
    impact: "Small files stored inline in the MFT and cluster slack can survive a normal delete; this zeroes those regions after shred",
    section: "security",
    domain: "security",
    settingsPath: "ideal.tweaks.security.shredMftSlackEnabled",
    currentPath: "current.tweaks.security.shredMftSlackEnabled",
    enableCmd: commandId("Clear-", "MFTResident", "Slack"),
    disableCmd: commandId("Clear-", "MFTResident", "Slack"),
    minExperience: "advanced",
    defaultOn: false,
  },

  // ════════════════════════════════════════════════════════════════════
  //  OS / HARDWARE TWEAKS — Superfetch, hibernation, prefetch, NTFS
  //  All HKLM / services / powercfg writes — tier: "free", needsAdmin: true
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "superfetch",
    label: "Disable Superfetch",
    description: "Stop preloading apps",
    impact: "Preloads data into RAM — slows SSD systems",
    section: "os",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.superfetchDisabled",
    currentPath: "current.tweaks.os.superfetchDisabled",
    enableCmd: "Disable-Superfetch",
    disableCmd: "Enable-Superfetch",
    statusCmd: "Get-HardeningStatus",
    minExperience: "standard",
    radar: true,
    radarCategory: "performance",
    radarSeverity: "warning",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "hibernation",
    label: "Disable Hibernation",
    description: "Free hiberfil.sys space",
    impact: "Hibernation writes RAM contents to disk, leaving a recoverable memory artifact",
    section: "os",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.hibernationDisabled",
    currentPath: "current.tweaks.os.hibernationDisabled",
    enableCmd: "Disable-Hibernation",
    disableCmd: "Enable-Hibernation",
    statusCmd: "Get-HardeningStatus",
    minExperience: "standard",
    radar: true,
    radarRequiresAntiCleanup: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    cleanupScore: 15,
    cleanupScoreCategory: "memory",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "fastStartup",
    label: "Disable Fast Startup",
    description: "Clean boot every time",
    impact: "Fast Startup preserves shutdown state to disk, leaving extra cleanup residue between boots",
    section: "os",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.fastStartupDisabled",
    currentPath: "current.tweaks.os.fastStartupDisabled",
    enableCmd: "Disable-FastStartup",
    disableCmd: "Enable-FastStartup",
    statusCmd: "Get-HardeningStatus",
    minExperience: "standard",
    radar: true,
    radarRequiresAntiCleanup: true,
    radarCategory: "privacy",
    radarSeverity: "info",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "ntfsOpt",
    label: "NTFS Optimizations",
    description: "Enable NTFS performance tweaks",
    impact: "Filesystem timestamps waste disk I/O",
    section: "os",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.ntfsOptimizationsEnabled",
    currentPath: "current.tweaks.os.ntfsOptimizationsEnabled",
    enableCmd: "Enable-NTFSOptimizations",
    disableCmd: "Disable-NTFSOptimizations",
    statusCmd: "Get-HardeningStatus",
    minExperience: "standard",
    radar: false,
    radarCategory: "performance",
    radarSeverity: "info",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "pagefile",
    label: "Disable Pagefile",
    description: "No RAM swapping (Increases crash risk)",
    section: "os",
    domain: "tweaks",
    settingsPath: "ideal.privacy.tracking.pagefileDisabled",
    currentPath: "current.privacy.tracking.pagefileDisabled",
    enableCmd: "Disable-Pagefile",
    disableCmd: "Enable-Pagefile",
    statusCmd: "Get-PrivacyProtectionStatus",
    minExperience: "advanced",
    privacyScore: 3,
    privacyScoreCategory: "hardening",
    cleanupScore: 15,
    cleanupScoreCategory: "memory",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "prefetch",
    label: "Disable Prefetch",
    description: "Reduce app launch traces",
    impact: "Records which programs you run, when, and how often",
    section: "os",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.prefetchDisabled",
    currentPath: "current.tweaks.os.prefetchDisabled",
    enableCmd: "Disable-Prefetch",
    disableCmd: "Enable-Prefetch",
    statusCmd: "Get-PrivacyProtectionStatus",
    minExperience: "standard",
    radar: true,
    radarRequiresAntiCleanup: true,
    radarCategory: "privacy",
    radarSeverity: "info",
    cleanupScore: 12,
    cleanupScoreCategory: "traces",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "memoryCompression",
    label: "Disable Memory Compression",
    description: "Reduce CPU overhead on low-RAM systems",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.memoryCompressionDisabled",
    currentPath: "current.tweaks.os.memoryCompressionDisabled",
    enableCmd: "Disable-MemoryCompression",
    disableCmd: "Enable-MemoryCompression",
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "win32Priority",
    label: "Foreground Priority Boost",
    description: "Prioritize active window performance",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.win32PrioritySeparation",
    currentPath: "current.tweaks.os.win32PrioritySeparation",
    enableCmd: "Set-Win32PrioritySeparation",
    disableCmd: "Reset-Win32PrioritySeparation",
    minExperience: "advanced",
    impact: "Active window doesn't receive boosted CPU scheduling priority",
    radar: true,
    radarCategory: "performance",
    radarSeverity: "info",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "serviceTimeouts",
    label: "Optimize Service Timeouts",
    description: "Faster shutdown/restart kill times",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.serviceTimeoutsOptimized",
    currentPath: "current.tweaks.os.serviceTimeoutsOptimized",
    enableCmd: "Set-OptimizedTimeouts",
    disableCmd: "Reset-OptimizedTimeouts",
    minExperience: "advanced",
    impact: "Windows waits longer than needed before force-killing services on shutdown",
    radar: true,
    radarCategory: "performance",
    radarSeverity: "info",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "reservedStorage",
    label: "Disable Reserved Storage",
    description: "Reclaim 7GB+ reserved by Windows",
    section: "os",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.reservedStorageDisabled",
    currentPath: "current.tweaks.os.reservedStorageDisabled",
    enableCmd: "Disable-ReservedStorage",
    disableCmd: "Enable-ReservedStorage",
    minExperience: "standard",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "automaticMaintenance",
    label: "Disable Automatic Maintenance",
    description: "Stop Windows maintenance and scheduled diagnostics while idle",
    section: "os",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.automaticMaintenanceDisabled",
    currentPath: "current.tweaks.os.automaticMaintenanceDisabled",
    enableCmd: "Disable-AutomaticMaintenance",
    disableCmd: "Enable-AutomaticMaintenance",
    statusCmd: "Get-HardeningStatus",
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "win32LongPaths",
    label: "Enable Win32 Long Paths",
    description: "Allow compatible apps to use paths longer than 260 characters",
    section: "os",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.win32LongPathsEnabled",
    currentPath: "current.tweaks.os.win32LongPathsEnabled",
    enableCmd: "Enable-Win32LongPaths",
    disableCmd: "Disable-Win32LongPaths",
    statusCmd: "Get-HardeningStatus",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "smbBandwidthThrottling",
    label: "Disable SMB Bandwidth Throttling",
    description: "Remove the Windows SMB client throughput cap",
    section: "os",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.smbBandwidthThrottlingDisabled",
    currentPath: "current.tweaks.os.smbBandwidthThrottlingDisabled",
    enableCmd: "Disable-SmbBandwidthThrottling",
    disableCmd: "Enable-SmbBandwidthThrottling",
    statusCmd: "Get-HardeningStatus",
    minExperience: "advanced",
  },

  // ════════════════════════════════════════════════════════════════════
  //  BOOT & KERNEL — Low-level boot/kernel tweaks
  //  All HKLM / bcdedit writes — tier: "free", needsAdmin: true
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "detailedBSOD",
    label: "Enable Detailed BSOD",
    description: "Show technical crash codes instead of sad face",
    impact: "BSOD hides technical crash codes needed for debugging",
    section: "boot",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.os.detailedBsodEnabled",
    currentPath: "current.tweaks.os.detailedBsodEnabled",
    enableCmd: "Enable-DetailedBSOD",
    disableCmd: "Disable-DetailedBSOD",
    statusCmd: "Get-HardeningStatus",
    alwaysApplyOnFirstRun: true,
    minExperience: "simple",
    radar: true,
    radarCategory: "annoyance",
    radarSeverity: "info",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "tsx",
    label: "Enable Intel TSX",
    description: "Better transaction performance",
    section: "boot",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.bootKernel.tsxEnabled",
    currentPath: "current.tweaks.bootKernel.tsxEnabled",
    enableCmd: "Enable-TSX",
    disableCmd: "Disable-TSX",
    minExperience: "advanced",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "firstLogon",
    label: "Disable First Sign-In Animation",
    description: "Skip 'Hi, we're getting things ready'",
    section: "boot",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.bootKernel.firstLogonAnimationDisabled",
    currentPath: "current.tweaks.bootKernel.firstLogonAnimationDisabled",
    enableCmd: "Disable-FirstLogonAnimation",
    disableCmd: "Enable-FirstLogonAnimation",
    minExperience: "standard",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "startupSound",
    label: "Disable Startup Sound",
    description: "Silence the Windows boot chime",
    section: "boot",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.bootKernel.startupSoundDisabled",
    currentPath: "current.tweaks.bootKernel.startupSoundDisabled",
    enableCmd: "Disable-StartupSound",
    disableCmd: "Enable-StartupSound",
    minExperience: "standard",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "autoRestartSignon",
    label: "Disable Auto Restart Sign-On",
    description: "Don't resume session after restart",
    section: "boot",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.bootKernel.autoRestartSignonDisabled",
    currentPath: "current.tweaks.bootKernel.autoRestartSignonDisabled",
    enableCmd: "Disable-AutoRestartSignon",
    disableCmd: "Enable-AutoRestartSignon",
    minExperience: "standard",
    impact: "Windows resumes your session after restart, exposing recent activity",
    radar: true,
    radarRequiresAntiCleanup: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    cleanupScore: 5,
    cleanupScoreCategory: "behavior",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "autoRebootBsod",
    label: "Disable Auto-Reboot on BSOD",
    description: "Stay on blue screen to read error",
    section: "boot",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.bootKernel.autoRebootOnBsodDisabled",
    currentPath: "current.tweaks.bootKernel.autoRebootOnBsodDisabled",
    enableCmd: "Disable-AutoRebootOnBSOD",
    disableCmd: "Enable-AutoRebootOnBSOD",
    minExperience: "standard",
  },
  {
    tier: "free",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "smallMemDump",
    label: "Small Memory Dump",
    description: "Use 64KB crash dumps instead of full",
    section: "boot",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.bootKernel.smallMemoryDumpEnabled",
    currentPath: "current.tweaks.bootKernel.smallMemoryDumpEnabled",
    enableCmd: "Set-SmallMemoryDump",
    disableCmd: "Reset-SmallMemoryDump",
    minExperience: "standard",
    impact: "Full crash dumps expose passwords, encryption keys, and session tokens on disk",
    radar: true,
    radarRequiresAntiCleanup: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    cleanupScore: 5,
    cleanupScoreCategory: "memory",
  },

  // ════════════════════════════════════════════════════════════════════
  //  RDP STABILITY — Surfaced inside the Privacy panel's RDP card.
  //  These toggles live in the registry so status probing & score flow
  //  through the normal ToggleSection pipeline, but the Privacy panel
  //  renders them via <UniversalToggle> lookups rather than a Tweaks
  //  section header.
  //
  //  Tier: "paid" — moved from free per user comment. RDP stability is
  //  most valuable to admins running remote infrastructure, who can pay.
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "rdpKeepAlive",
    label: "Keep-Alive",
    description: "TCP keep-alive every 60s, one session per user",
    section: "rdp",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.rdp.keepAlive",
    currentPath: "current.tweaks.rdp.keepAlive",
    enableCmd: "Enable-RdpKeepAlive",
    disableCmd: "Disable-RdpKeepAlive",
    statusCmd: "Get-RdpKeepAliveStatus",
    minExperience: "advanced",
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "rdpNoTimeouts",
    label: "No Timeouts",
    description: "No idle / disconnected / connection time limits",
    section: "rdp",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.rdp.noTimeouts",
    currentPath: "current.tweaks.rdp.noTimeouts",
    enableCmd: "Enable-RdpNoTimeouts",
    disableCmd: "Disable-RdpNoTimeouts",
    statusCmd: "Get-RdpNoTimeoutsStatus",
    minExperience: "advanced",
  },
  {
    tier: "paid",
    needsAdmin: true,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "rdpQosPriority",
    label: "QoS Priority",
    description: "EF class on TCP 3389 in and out; runs gpupdate",
    section: "rdp",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.rdp.qosPriority",
    currentPath: "current.tweaks.rdp.qosPriority",
    enableCmd: "Enable-RdpQosPriority",
    disableCmd: "Disable-RdpQosPriority",
    statusCmd: "Get-RdpQosPriorityStatus",
    minExperience: "advanced",
  },

  // ════════════════════════════════════════════════════════════════════
  //  PERFORMANCE & GAMING
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "mmcssGaming",
    label: "MMCSS Gaming Profile",
    description: "Tunes MMCSS for low-latency foreground apps + games",
    impact: "Network throttling steals 10ms of CPU every interval — kills competitive gaming latency",
    icon: "rocket",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.performance.mmcssGamingProfile",
    currentPath: "current.tweaks.performance.mmcssGamingProfile",
    enableCmd: "Enable-MMCSSGamingProfile",
    disableCmd: "Disable-MMCSSGamingProfile",
    minExperience: "advanced",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "kbLatency",
    label: "Keyboard Latency",
    description: "Zero key-repeat delay, max repeat rate",
    icon: "key",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.performance.keyboardLatencyOptimised",
    currentPath: "current.tweaks.performance.keyboardLatencyOptimised",
    enableCmd: "Enable-KeyboardLatencyOptimised",
    disableCmd: "Disable-KeyboardLatencyOptimised",
    minExperience: "advanced",
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "numLockBoot",
    label: "Num Lock on Boot",
    description: "Always enable Num Lock at the lock screen",
    icon: "numerical",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.performance.numLockOnBoot",
    currentPath: "current.tweaks.performance.numLockOnBoot",
    enableCmd: "Enable-NumLockOnBoot",
    disableCmd: "Disable-NumLockOnBoot",
    minExperience: "standard",
    impact: "Num Lock is off at the lock screen and must be toggled manually",
    radar: true,
    radarCategory: "annoyance",
    radarSeverity: "info",
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "gpuScheduling",
    label: "Hardware-Accelerated GPU Scheduling",
    description: "Offload scheduling to the GPU (HwSchMode=2)",
    impact: "Frame pacing + low-latency rendering benefit on modern dGPUs",
    icon: "desktop",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.performance.gpuSchedulingEnabled",
    currentPath: "current.tweaks.performance.gpuSchedulingEnabled",
    enableCmd: "Enable-GpuScheduling",
    disableCmd: "Disable-GpuScheduling",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "svcHostSplit",
    label: "SvcHost Split (RAM-tuned)",
    description: "One svchost per service for RAM ≥ 3.5 GB",
    impact: "Reduces blast radius of a single faulty service process",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.performance.svcHostSplitOptimised",
    currentPath: "current.tweaks.performance.svcHostSplitOptimised",
    enableCmd: "Enable-SvcHostSplit",
    disableCmd: "Disable-SvcHostSplit",
    minExperience: "advanced",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "a11yHotkeys",
    label: "Disable Accessibility Hotkey Traps",
    description: "No more StickyKeys / ToggleKeys / FilterKeys popups",
    impact: "Five-shift / hold-shift popups break gaming flow + can be hijacked at login",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.performance.accessibilityShortcutsDisabled",
    currentPath: "current.tweaks.performance.accessibilityShortcutsDisabled",
    enableCmd: "Disable-AccessibilityShortcuts",
    disableCmd: "Enable-AccessibilityShortcuts",
    defaultOn: true,
    minExperience: "standard",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "instantMenu",
    label: "Instant Menu Delay",
    description: "MenuShowDelay=0 — menus open immediately",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.performance.instantMenuDelay",
    currentPath: "current.tweaks.performance.instantMenuDelay",
    enableCmd: "Enable-InstantMenuDelay",
    disableCmd: "Disable-InstantMenuDelay",
    minExperience: "simple",
    impact: "Menus have a built-in delay before appearing",
    radar: true,
    radarCategory: "annoyance",
    radarSeverity: "info",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "mouseAccel",
    label: "Disable Mouse Acceleration",
    description: "1:1 pointer movement (Enhance Pointer Precision off)",
    icon: "hand-up",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.performance.mouseAccelerationDisabled",
    currentPath: "current.tweaks.performance.mouseAccelerationDisabled",
    enableCmd: "Disable-MouseAcceleration",
    disableCmd: "Enable-MouseAcceleration",
    minExperience: "standard",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "autocorrect",
    label: "Disable Autocorrect / Spellcheck",
    description: "Turn off text-prediction + double-space autocorrect",
    icon: "edit",
    section: "performance",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.performance.autocorrectDisabled",
    currentPath: "current.tweaks.performance.autocorrectDisabled",
    enableCmd: "Disable-AutocorrectSpellcheck",
    disableCmd: "Enable-AutocorrectSpellcheck",
    minExperience: "standard",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "enthusiastMode",
    label: "Enthusiast Mode",
    description: "Detailed Explorer copy/move dialog with throughput graph",
    icon: "presentation",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.performance.enthusiastModeEnabled",
    currentPath: "current.tweaks.performance.enthusiastModeEnabled",
    enableCmd: "Enable-EnthusiastMode",
    disableCmd: "Disable-EnthusiastMode",
    minExperience: "advanced",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "wallpaperQual",
    label: "Full-Quality Wallpaper",
    description: "Disable JPEG re-encoding to 85% on desktop wallpaper",
    icon: "media",
    section: "ui",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.performance.wallpaperFullQuality",
    currentPath: "current.tweaks.performance.wallpaperFullQuality",
    enableCmd: "Enable-WallpaperQuality",
    disableCmd: "Disable-WallpaperQuality",
    minExperience: "standard",
  },

  // ════════════════════════════════════════════════════════════════════
  //  GPU VENDOR TWEAKS
  //  All HKLM Class\{4d36e968...} writes; require reboot.
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "amdUlps",
    label: "AMD · Disable ULPS",
    description: "Disable Ultra Low Power State (crossfire/idle stutter fix)",
    icon: "flash",
    section: "gpu",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.gpu.amdUlpsDisabled",
    currentPath: "current.tweaks.gpu.amdUlpsDisabled",
    enableCmd: "Disable-AmdUlps",
    disableCmd: "Enable-AmdUlps",
    requiresRestart: true,
    minExperience: "advanced",
    conflictsWith: ["nvDynamicPstate", "nvAsyncPstates", "intelAsyncFlips", "intelAdaptiveVsync"],
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "amdPowerGating",
    label: "AMD · Disable Power Gating",
    description: "Lock GPU power-state — avoids dynamic clock stutter",
    section: "gpu",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.gpu.amdPowerGatingDisabled",
    currentPath: "current.tweaks.gpu.amdPowerGatingDisabled",
    enableCmd: "Disable-AmdPowerGating",
    disableCmd: "Enable-AmdPowerGating",
    requiresRestart: true,
    minExperience: "advanced",
    conflictsWith: ["nvDynamicPstate", "nvAsyncPstates", "intelAsyncFlips", "intelAdaptiveVsync"],
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "amdClockGating",
    label: "AMD · Disable Video Clock Gating",
    description: "Disable UVD/VCE clock gating for consistent encode latency",
    section: "gpu",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.gpu.amdVideoClockGatingDisabled",
    currentPath: "current.tweaks.gpu.amdVideoClockGatingDisabled",
    enableCmd: "Disable-AmdVideoClockGating",
    disableCmd: "Enable-AmdVideoClockGating",
    requiresRestart: true,
    minExperience: "advanced",
    conflictsWith: ["nvDynamicPstate", "nvAsyncPstates", "intelAsyncFlips", "intelAdaptiveVsync"],
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "amdAspm",
    label: "AMD · Disable ASPM (L0s/L1)",
    description: "Disable PCIe Active State Power Management on the GPU",
    section: "gpu",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.gpu.amdAspmDisabled",
    currentPath: "current.tweaks.gpu.amdAspmDisabled",
    enableCmd: "Disable-AmdAspm",
    disableCmd: "Enable-AmdAspm",
    requiresRestart: true,
    minExperience: "advanced",
    conflictsWith: ["nvDynamicPstate", "nvAsyncPstates", "intelAsyncFlips", "intelAdaptiveVsync"],
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "nvDynamicPstate",
    label: "NVIDIA · Disable Dynamic P-State",
    description: "Stop the driver dropping clocks under light load",
    section: "gpu",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.gpu.nvidiaDynamicPstateDisabled",
    currentPath: "current.tweaks.gpu.nvidiaDynamicPstateDisabled",
    enableCmd: "Disable-NvidiaDynamicPstate",
    disableCmd: "Enable-NvidiaDynamicPstate",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "nvAsyncPstates",
    label: "NVIDIA · Disable Async P-States",
    description: "Force synchronous P-state transitions",
    section: "gpu",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.gpu.nvidiaAsyncPstatesDisabled",
    currentPath: "current.tweaks.gpu.nvidiaAsyncPstatesDisabled",
    enableCmd: "Disable-NvidiaAsyncPstates",
    disableCmd: "Enable-NvidiaAsyncPstates",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "intelAsyncFlips",
    label: "Intel · Disable Async Flips",
    description: "Disable async buffer flips for reduced tear/latency",
    section: "gpu",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.gpu.intelAsyncFlipsDisabled",
    currentPath: "current.tweaks.gpu.intelAsyncFlipsDisabled",
    enableCmd: "Disable-IntelAsyncFlips",
    disableCmd: "Enable-IntelAsyncFlips",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "intelAdaptiveVsync",
    label: "Intel · Disable Adaptive VSync",
    description: "Lock to driver VSync (deterministic frame pacing)",
    section: "gpu",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.gpu.intelAdaptiveVsyncDisabled",
    currentPath: "current.tweaks.gpu.intelAdaptiveVsyncDisabled",
    enableCmd: "Disable-IntelAdaptiveVsync",
    disableCmd: "Enable-IntelAdaptiveVsync",
    requiresRestart: true,
    minExperience: "advanced",
  },

  // ════════════════════════════════════════════════════════════════════
  //  POWER MANAGEMENT
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "usbSuspend",
    label: "Disable USB Selective Suspend",
    description: "Stop USB devices powering down on idle (audio/HID stutter fix)",
    icon: "data-connection",
    section: "power",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.power.usbSelectiveSuspendDisabled",
    currentPath: "current.tweaks.power.usbSelectiveSuspendDisabled",
    enableCmd: "Disable-UsbSelectiveSuspend",
    disableCmd: "Enable-UsbSelectiveSuspend",
    minExperience: "standard",
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "cpuThrottle",
    label: "Disable CPU Power Throttling",
    description: "Stop Windows throttling background processes by default",
    icon: "pulse",
    section: "power",
    domain: "tweaks",
    settingsPath: "ideal.tweaks.power.cpuThrottlingDisabled",
    currentPath: "current.tweaks.power.cpuThrottlingDisabled",
    enableCmd: "Disable-CpuThrottling",
    disableCmd: "Enable-CpuThrottling",
    minExperience: "advanced",
  },
  // (Ultimate Performance is exposed via the unified PowerPlanCard — a
  // 4th radio in the existing Energy & Speed picker, not a standalone
  // toggle. See src/components/tweaks/PowerPlanCard.tsx.)

  // ════════════════════════════════════════════════════════════════════
  //  UI TWEAKS — GRANULAR CONTROLS
  //  Surfaced under the existing UI section so they're discoverable.
  // ════════════════════════════════════════════════════════════════════

  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "icoThisPc", label: "Show 'This PC' on Desktop", description: "Pin This PC icon to the desktop",
    section: "ui", domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.desktopIconThisPc",
    currentPath:  "current.tweaks.ui.desktopIconThisPc",
    enableCmd: "Show-DesktopIconThisPc", disableCmd: "Hide-DesktopIconThisPc",
    minExperience: "simple",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "icoRecycle", label: "Show Recycle Bin on Desktop", description: "Pin the Recycle Bin to the desktop",
    section: "ui", domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.desktopIconRecycleBin",
    currentPath:  "current.tweaks.ui.desktopIconRecycleBin",
    enableCmd: "Show-DesktopIconRecycleBin", disableCmd: "Hide-DesktopIconRecycleBin",
    minExperience: "simple",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "icoUserFiles", label: "Show User Folder on Desktop", description: "Pin user profile to desktop",
    section: "ui", domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.desktopIconUserFiles",
    currentPath:  "current.tweaks.ui.desktopIconUserFiles",
    enableCmd: "Show-DesktopIconUserFiles", disableCmd: "Hide-DesktopIconUserFiles",
    minExperience: "standard",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "icoNetwork", label: "Show Network on Desktop", description: "Pin Network to the desktop",
    section: "ui", domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.desktopIconNetwork",
    currentPath:  "current.tweaks.ui.desktopIconNetwork",
    enableCmd: "Show-DesktopIconNetwork", disableCmd: "Hide-DesktopIconNetwork",
    minExperience: "standard",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "icoControl", label: "Show Control Panel on Desktop", description: "Pin classic Control Panel to the desktop",
    section: "ui", domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.desktopIconControlPanel",
    currentPath:  "current.tweaks.ui.desktopIconControlPanel",
    enableCmd: "Show-DesktopIconControlPanel", disableCmd: "Hide-DesktopIconControlPanel",
    minExperience: "standard",
  },
  {
    tier: "free", needsAdmin: true, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "shortcutArrow", label: "Remove Shortcut Arrow",
    description: "Hide the curved arrow overlay on shortcut icons",
    section: "ui", domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.shortcutArrowRemoved",
    currentPath:  "current.tweaks.ui.shortcutArrowRemoved",
    enableCmd: "Remove-ShortcutArrow", disableCmd: "Restore-ShortcutArrow",
    requiresRestart: true,
    minExperience: "advanced",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "snapFlyout", label: "Disable Snap-Assist Flyout",
    description: "No more snap-suggestion popup when dragging a window",
    section: "ui", domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.snapAssistFlyoutDisabled",
    currentPath:  "current.tweaks.ui.snapAssistFlyoutDisabled",
    enableCmd: "Disable-SnapAssistFlyout", disableCmd: "Enable-SnapAssistFlyout",
    minExperience: "standard",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "explorerCompact", label: "Explorer Compact Mode",
    description: "Tighter row spacing in File Explorer",
    section: "ui", domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.explorerCompactMode",
    currentPath:  "current.tweaks.ui.explorerCompactMode",
    enableCmd: "Enable-ExplorerCompactMode", disableCmd: "Disable-ExplorerCompactMode",
    minExperience: "standard",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "fileCheckboxes", label: "File Checkboxes",
    description: "Show selection checkboxes when hovering files in Explorer",
    section: "ui", domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.explorerCheckboxesEnabled",
    currentPath:  "current.tweaks.ui.explorerCheckboxesEnabled",
    enableCmd: "Enable-ExplorerCheckboxes", disableCmd: "Disable-ExplorerCheckboxes",
    minExperience: "standard",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "windowShake", label: "Disable Window Shake-to-Minimise",
    description: "Stop other windows minimising when you shake the active one",
    section: "ui", domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.windowShakeDisabled",
    currentPath:  "current.tweaks.ui.windowShakeDisabled",
    enableCmd: "Disable-WindowShake", disableCmd: "Enable-WindowShake",
    minExperience: "standard",
  },
  {
    tier: "free", needsAdmin: false, irreversible: false, reducesSecurity: false, defenderFlagged: false,
    id: "clockSeconds", label: "Show Clock Seconds",
    description: "Add seconds to the taskbar clock (HH:mm:ss)",
    section: "ui", domain: "tweaks",
    settingsPath: "ideal.tweaks.ui.clockSecondsVisible",
    currentPath:  "current.tweaks.ui.clockSecondsVisible",
    enableCmd: "Show-ClockSeconds", disableCmd: "Hide-ClockSeconds",
    requiresRestart: true,
    minExperience: "standard",
  },

  // ── Radar-only entries (no section → not rendered in any panel) ──────
  // These are managed by ContextMenuIntegrationCard via Tauri commands;
  // registry entries exist only so the cleanup radar can detect them.

  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "contextMenuShred",
    label: "Delete",
    description: "Permanent secure deletion in right-click menu",
    section: "radar-only",
    domain: "tweaks",
    settingsPath: "app.contextMenuEnabled",
    currentPath: "app.contextMenuEnabled",
    enableCmd: "Toggle-ContextMenu",
    disableCmd: "Toggle-ContextMenu",
    minExperience: "advanced",
    impact: "No secure right-click delete — deleted files may remain recoverable",
    radar: true,
    radarRequiresAntiCleanup: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    cleanupScore: 4,
    cleanupScoreCategory: "behavior",
  },
  {
    tier: "free",
    needsAdmin: false,
    irreversible: false,
    reducesSecurity: false,
    defenderFlagged: false,
    id: "contextMenuScrub",
    label: "Scrub",
    description: "Strip EXIF/GPS/author data in right-click menu",
    section: "radar-only",
    domain: "tweaks",
    settingsPath: "app.scrubContextMenuEnabled",
    currentPath: "app.scrubContextMenuEnabled",
    enableCmd: "Toggle-ScrubContextMenu",
    disableCmd: "Toggle-ScrubContextMenu",
    minExperience: "standard",
    safeDefault: true,
    impact: "Files shared without scrubbing may leak GPS, camera model, or author identity",
    radar: true,
    radarCategory: "privacy",
    radarSeverity: "warning",
    cleanupScore: 3,
    cleanupScoreCategory: "behavior",
  },
];
