// SPDX-License-Identifier: AGPL-3.0-or-later
//! WinCommander SYSTEM service (`wincommander-svc.exe`)
//!
//! # Modes
//!
//! * `--console`  — dev / debugging mode: runs a tokio multi-thread runtime
//!   directly without registering with the SCM.  Useful with `cargo run`.
//!
//! * *(no flag)*  — production mode: on Windows, hands control to the SCM
//!   dispatcher via `windows-service`; on non-Windows, prints a note and exits.
//!
//! # Phase 0 scope
//!
//! The four background loops are **stubbed** (30-second sleep bodies with doc
//! comments).  Phase 2 wires the enforcement loop; Phase 3 wires reconciler,
//! command-worker, and fleet-conn.

// ── Non-Windows stub ─────────────────────────────────────────────────────────
// On Linux CI we only need `cargo check` / `cargo build` to succeed.
// No pipe, no SCM, no windows-sys.

#[cfg(not(windows))]
fn main() {
    println!("WinCommander service: endpoint enforcement is Windows-only (build-only stub)");
    std::process::exit(0);
}

// ── Windows implementation ───────────────────────────────────────────────────

mod settings_host;

#[cfg(windows)]
mod pipe;

#[cfg(windows)]
mod pro_broker;

#[cfg(windows)]
use windows_service::{
    define_windows_service,
    service::{
        ServiceControl, ServiceControlAccept, ServiceExitCode, ServiceState, ServiceStatus,
        ServiceType,
    },
    service_control_handler::{self, ServiceControlHandlerResult},
    service_dispatcher,
};

#[cfg(windows)]
const SERVICE_NAME: &str = "WinCommanderSvc";

/// Entry point on Windows.
#[cfg(windows)]
fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.iter().any(|a| a == "--console") {
        // Dev mode: run directly without SCM.
        run_runtime();
    } else {
        // Production: hand off to the SCM dispatcher.
        // If this fails (e.g. not run as a service), fall back to console mode
        // so developers who forget `--console` get a helpful error.
        match service_dispatcher::start(SERVICE_NAME, ffi_service_main) {
            Ok(()) => {}
            Err(e) => {
                eprintln!(
                    "[wincommander-svc] SCM dispatcher failed ({}).  \
                     Try running with --console for dev mode.",
                    e
                );
                std::process::exit(1);
            }
        }
    }
}

// SCM-compatible service entry point (generated by `define_windows_service!`).
#[cfg(windows)]
define_windows_service!(ffi_service_main, service_main);

/// Called by the SCM dispatcher on service start.
#[cfg(windows)]
fn service_main(_arguments: Vec<std::ffi::OsString>) {
    // Register a minimal SCM control handler (Phase 0 — just accepts Stop).
    let status_handle = match service_control_handler::register(
        SERVICE_NAME,
        |control| -> ServiceControlHandlerResult {
            match control {
                ServiceControl::Stop | ServiceControl::Interrogate => {
                    ServiceControlHandlerResult::NoError
                }
                _ => ServiceControlHandlerResult::NotImplemented,
            }
        },
    ) {
        Ok(h) => h,
        Err(e) => {
            eprintln!("[wincommander-svc] register control handler failed: {}", e);
            return;
        }
    };

    // Tell the SCM we're running.
    let _ = status_handle.set_service_status(ServiceStatus {
        service_type: ServiceType::OWN_PROCESS,
        current_state: ServiceState::Running,
        controls_accepted: ServiceControlAccept::STOP,
        exit_code: ServiceExitCode::Win32(0),
        checkpoint: 0,
        wait_hint: std::time::Duration::default(),
        process_id: None,
    });

    // Run the actual service body.
    run_runtime();
}

/// Spawn a tokio multi-thread runtime and launch all service loops.
#[cfg(windows)]
fn run_runtime() {
    let rt = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .expect("build tokio runtime");
    rt.block_on(run());
}

/// Async service body — starts the four background loops and the pipe server.
#[cfg(windows)]
async fn run() {
    // ── Phase 2/3 background loops (stubbed for Phase 0) ────────────────
    //
    // Each loop is an independent tokio task.  Phase 2 fills in
    // `enforcement_loop`; Phase 3 fills in the remaining three.

    tokio::spawn(enforcement_loop());
    tokio::spawn(reconciler_loop());
    tokio::spawn(command_worker_loop());
    tokio::spawn(fleet_conn_loop());

    // ── Named-pipe server ────────────────────────────────────────────────
    if let Err(e) = pipe::serve().await {
        eprintln!("[wincommander-svc] pipe server exited with error: {:#}", e);
    }
}

/// Phase 2 fills this in — endpoint enforcement (policy push, rule evaluation).
#[cfg(windows)]
async fn enforcement_loop() {
    loop {
        tokio::time::sleep(std::time::Duration::from_secs(30)).await;
    }
}

/// Phase 3 fills this in — settings reconciler (drift detection, repair).
#[cfg(windows)]
async fn reconciler_loop() {
    loop {
        tokio::time::sleep(std::time::Duration::from_secs(30)).await;
    }
}

/// Phase 3 fills this in — command worker (dequeue + execute fleet commands).
#[cfg(windows)]
async fn command_worker_loop() {
    loop {
        tokio::time::sleep(std::time::Duration::from_secs(30)).await;
    }
}

/// Phase 3 fills this in — fleet connection (heartbeat + telemetry upload).
#[cfg(windows)]
async fn fleet_conn_loop() {
    loop {
        tokio::time::sleep(std::time::Duration::from_secs(30)).await;
    }
}
