// SPDX-License-Identifier: AGPL-3.0-or-later
//! WinCommander SYSTEM service (`wincommander-svc.exe`)
//!
//! # Modes
//!
//! * `--console`  — dev / debugging mode: runs a tokio multi-thread runtime
//!   directly without registering with the SCM.  Useful with `cargo run`.
//!
//! * *(no flag)*  — production mode: on Windows, hands control to the SCM
//!   dispatcher via `windows-service`; on non-Windows, prints a note and exits.
//!
//! # Phase 0 scope
//!
//! The four background loops are **stubbed** (30-second sleep bodies with doc
//! comments).  Phase 2 wires the enforcement loop; Phase 3 wires reconciler,
//! command-worker, and fleet-conn.

// ── Non-Windows stub ─────────────────────────────────────────────────────────
// On Linux CI we only need `cargo check` / `cargo build` to succeed.
// No pipe, no SCM, no windows-sys.

#[cfg(not(windows))]
fn main() {
    println!("WinCommander service: endpoint enforcement is Windows-only (build-only stub)");
    std::process::exit(0);
}

// ── Windows implementation ───────────────────────────────────────────────────

mod settings_host;

// Cross-platform by design (C2): the generic verify/version-guard/compile
// engine and every test in this module compile and run on Linux CI too;
// only its internal `WindowsPolicyFs`/`windows_acl` submodule is
// `#[cfg(windows)]`-gated. See `policy_store.rs`'s module doc.
mod policy_store;
mod vault_access;

#[cfg(windows)]
mod vault_mount;

#[cfg(windows)]
mod pipe;

#[cfg(windows)]
mod pro_broker;

#[cfg(windows)]
mod encvol_driver;

// `SessionHelper` peer authentication (D-2). Windows-only because it derives
// process/session identity and canonical image paths with Win32 APIs, matching
// `pipe.rs`'s own Windows-only stance. No Authenticode certificate is required.
#[cfg(windows)]
mod peer_auth;

#[cfg(windows)]
use std::sync::{Arc, Mutex, OnceLock};

#[cfg(windows)]
static VAULT_MOUNT_FOR_STOP: OnceLock<Arc<vault_mount::VaultMountBroker>> = OnceLock::new();
#[cfg(windows)]
static VAULT_ACCESS_FOR_STOP: OnceLock<Arc<vault_access::VaultAccessStore>> = OnceLock::new();

#[cfg(windows)]
use windows_service::{
    define_windows_service,
    service::{
        ServiceControl, ServiceControlAccept, ServiceExitCode, ServiceState, ServiceStatus,
        ServiceType, SessionChangeReason,
    },
    service_control_handler::{self, ServiceControlHandlerResult},
    service_dispatcher,
};

#[cfg(windows)]
const SERVICE_NAME: &str = "WinCommanderSvc";

#[cfg(windows)]
fn stop_pending_status() -> ServiceStatus {
    ServiceStatus {
        service_type: ServiceType::OWN_PROCESS,
        current_state: ServiceState::StopPending,
        controls_accepted: ServiceControlAccept::empty(),
        exit_code: ServiceExitCode::Win32(0),
        checkpoint: 1,
        wait_hint: std::time::Duration::from_secs(135),
        process_id: None,
    }
}

/// Entry point on Windows.
#[cfg(windows)]
fn main() {
    let args: Vec<String> = std::env::args().collect();
    if args.iter().any(|a| a == "--console") {
        // Dev mode: run directly without SCM.
        run_runtime(None);
    } else {
        // Production: hand off to the SCM dispatcher.
        // If this fails (e.g. not run as a service), fall back to console mode
        // so developers who forget `--console` get a helpful error.
        match service_dispatcher::start(SERVICE_NAME, ffi_service_main) {
            Ok(()) => {}
            Err(e) => {
                eprintln!(
                    "[wincommander-svc] SCM dispatcher failed ({}).  \
                     Try running with --console for dev mode.",
                    e
                );
                std::process::exit(1);
            }
        }
    }
}

// SCM-compatible service entry point (generated by `define_windows_service!`).
#[cfg(windows)]
define_windows_service!(ffi_service_main, service_main);

/// Called by the SCM dispatcher on service start.
#[cfg(windows)]
fn service_main(_arguments: Vec<std::ffi::OsString>) {
    let (stop_tx, stop_rx) = tokio::sync::watch::channel(false);
    let status_slot: Arc<
        Mutex<Option<windows_service::service_control_handler::ServiceStatusHandle>>,
    > = Arc::new(Mutex::new(None));
    let handler_status_slot = Arc::clone(&status_slot);
    let status_handle = match service_control_handler::register(
        SERVICE_NAME,
        move |control| -> ServiceControlHandlerResult {
            match control {
                ServiceControl::Stop => {
                    // A mounted vault can take up to the broker deadline to
                    // dismount. Tell SCM that cleanup is in progress before
                    // returning from the callback; otherwise `Stop-Service`
                    // treats the still-running process as a failed stop.
                    if let Ok(slot) = handler_status_slot.lock() {
                        if let Some(handle) = *slot {
                            let _ = handle.set_service_status(stop_pending_status());
                        }
                    }
                    // The runtime observes this channel, closes its pipe and
                    // tasks, then invokes broker cleanup before SCM sees a
                    // stopped process. Never leave an update holding the exe.
                    let _ = stop_tx.send(true);
                    ServiceControlHandlerResult::NoError
                }
                ServiceControl::Interrogate => {
                    ServiceControlHandlerResult::NoError
                }
                ServiceControl::SessionChange(change)
                    if matches!(
                        change.reason,
                        SessionChangeReason::SessionLogoff
                            | SessionChangeReason::ConsoleDisconnect
                            | SessionChangeReason::RemoteDisconnect
                            | SessionChangeReason::SessionTerminate
                    ) => {
                        if let Some(broker) = VAULT_MOUNT_FOR_STOP.get().cloned() {
                            let session_id = change.notification.session_id;
                            // SCM control callbacks must return promptly. Run
                            // the bounded signed broker dismount on a runtime
                            // worker instead of blocking the dispatcher.
                            std::thread::spawn(move || {
                                if let Ok(runtime) = tokio::runtime::Builder::new_multi_thread().enable_all().build() {
                            if let Some(store) = VAULT_ACCESS_FOR_STOP.get().cloned() {
                                runtime.block_on(async move { broker.dismount_session(&store, session_id); });
                            }
                                }
                            });
                        }
                        ServiceControlHandlerResult::NoError
                    }
                _ => ServiceControlHandlerResult::NotImplemented,
            }
        },
    ) {
        Ok(h) => h,
        Err(e) => {
            eprintln!("[wincommander-svc] register control handler failed: {}", e);
            return;
        }
    };
    if let Ok(mut slot) = status_slot.lock() {
        *slot = Some(status_handle);
    }

    // Tell the SCM we're running.
    let _ = status_handle.set_service_status(ServiceStatus {
        service_type: ServiceType::OWN_PROCESS,
        current_state: ServiceState::Running,
        controls_accepted: ServiceControlAccept::STOP | ServiceControlAccept::SESSION_CHANGE,
        exit_code: ServiceExitCode::Win32(0),
        checkpoint: 0,
        wait_hint: std::time::Duration::default(),
        process_id: None,
    });

    // Run the actual service body.
    run_runtime(Some(stop_rx));

    let _ = status_handle.set_service_status(ServiceStatus {
        service_type: ServiceType::OWN_PROCESS,
        current_state: ServiceState::Stopped,
        controls_accepted: ServiceControlAccept::empty(),
        exit_code: ServiceExitCode::Win32(0),
        checkpoint: 0,
        wait_hint: std::time::Duration::default(),
        process_id: None,
    });
}

/// Spawn a tokio multi-thread runtime and launch all service loops.
#[cfg(windows)]
fn run_runtime(stop_rx: Option<tokio::sync::watch::Receiver<bool>>) {
    let rt = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .expect("build tokio runtime");
    rt.block_on(run(stop_rx));
}

/// Async service body — starts the four background loops and the pipe server.
#[cfg(windows)]
async fn run(mut stop_rx: Option<tokio::sync::watch::Receiver<bool>>) {
    // ── Durable policy store (plan §3: "the SYSTEM service owns durable
    // state") ────────────────────────────────────────────────────────────
    //
    // Opening the store enforces the policy directory's DACL
    // (SYSTEM/Administrators-only) — see `policy_store::WindowsPolicyFs::
    // ensure_dir_secure`. A service that cannot prove that directory is
    // locked down must not pretend its policy state is trustworthy, so a
    // failure here is a genuine "the service should not start" condition,
    // not something to swallow and continue past.
    let policy_store = Arc::new(
        match policy_store::PolicyStore::open(
            Box::new(policy_store::WindowsPolicyFs),
            Box::new(policy_store::SystemClock),
            policy_store::default_policy_dir(),
            pinned_fleet_signing_key(),
        ) {
            Ok(store) => store,
            Err(e) => {
                // `PolicyStoreError`'s `Display` is content-free by
                // construction (see that type's doc) — safe to log as-is.
                eprintln!(
                    "[wincommander-svc] policy store failed to open securely ({e}) — refusing to start"
                );
                std::process::exit(1);
            }
        },
    );

    // Re-verify and load whatever was last durably installed (if
    // anything) before accepting any pipe connections. `StartupOutcome`'s
    // `Debug` output is content-free (see `PolicyStoreError`'s doc) — safe
    // to log directly.
    let startup_report = policy_store.load_at_startup();
    eprintln!(
        "[wincommander-svc] policy store startup: clipboard={:?} ink_receipt={:?}",
        startup_report.clipboard, startup_report.ink_receipt
    );

    // Vault access is a separate, service-owned last-valid policy under the
    // already SYSTEM/Administrators-protected policy directory.
    let vault_access = Arc::new(vault_access::VaultAccessStore::open_with_groups(
        Box::new(vault_access::WindowsVaultFs),
        Box::new(vault_access::WindowsPrincipalResolver),
        Box::new(vault_access::WindowsAclApplier),
        Box::new(vault_access::WindowsLocalGroupReconciler),
        policy_store::default_policy_dir(),
    ));
    vault_access.load_at_startup();
    let vault_mount = Arc::new(vault_mount::VaultMountBroker::new());
    let _ = VAULT_ACCESS_FOR_STOP.set(Arc::clone(&vault_access));
    let _ = VAULT_MOUNT_FOR_STOP.set(Arc::clone(&vault_mount));
    // Service restarts must not leave an untracked broker-owned mount behind.
    // The fixed broker performs this best-effort cleanup without receiving a
    // path or password from this process.
    if vault_mount.load_and_cleanup(&vault_access).is_err() {
        eprintln!("[wincommander-svc] vault mount recovery requires administrator repair");
    }

    // ── SessionHelper peer gate (D-2) ────────────────────────────────────
    //
    // ONE gate for the service's lifetime — its rate limiter's state must
    // outlive individual pipe connections to mean anything.
    let session_helper_gate = Arc::new(peer_auth::SessionHelperGate::new(Arc::new(
        peer_auth::WinPeerAuthProbe,
    )));

    // ── Clipboard Guard shared state (event queue + health + local toggle) ─
    let clipboard_state = Arc::new(pipe::ClipboardGuardState::new());

    // ── Phase 2/3 background loops ───────────────────────────────────────
    //
    // Each loop is an independent tokio task. `enforcement_loop` is now the
    // first real one (Phase 2); the remaining three stay Phase-0 stubs —
    // Phase 3 fills them in.

    tokio::spawn(enforcement_loop(
        Arc::clone(&policy_store),
        Arc::clone(&clipboard_state),
    ));
    tokio::spawn(reconciler_loop());
    tokio::spawn(command_worker_loop());
    tokio::spawn(fleet_conn_loop());
    // Pro can extract the engine after this service has already started.
    // Poll only the fixed payload: the helper is private, accepts no renderer
    // arguments, and fails closed until its signer/ownership/ACL checks pass.
    tokio::spawn(async {
        loop {
            let delay = if !encvol_driver::fixed_payload_present() {
                // Pro's extraction window is short; observe it quickly without
                // doing an expensive signature/ACL check while absent.
                std::time::Duration::from_secs(1)
            } else {
                let ensured = tokio::task::spawn_blocking(encvol_driver::ensure_for_vault_mount)
                    .await
                    .map(|result| result.is_ok())
                    .unwrap_or(false);
                if ensured {
                    break;
                }
                std::time::Duration::from_secs(5)
            };
            tokio::time::sleep(delay).await;
        }
    });

    // ── Named-pipe server ────────────────────────────────────────────────
    let pipe_server = pipe::serve(policy_store, session_helper_gate, clipboard_state, Arc::clone(&vault_access), Arc::clone(&vault_mount));
    if let Some(receiver) = stop_rx.as_mut() {
        tokio::select! {
            result = pipe_server => {
                if let Err(e) = result { eprintln!("[wincommander-svc] pipe server exited with error: {:#}", e); }
            }
            changed = receiver.changed() => {
                if changed.is_ok() && *receiver.borrow() { let _ = vault_mount.dismount_all(&vault_access); }
            }
        }
    } else if let Err(e) = pipe_server.await {
        eprintln!("[wincommander-svc] pipe server exited with error: {:#}", e);
    }
}

/// Read the fleet signing key svc pins `svc.policy.install_epoch` against,
/// from the same `%ProgramData%\WinCommander\svc-settings.json` blob
/// `settings_host.rs` already reads/writes as an untyped
/// `serde_json::Value` (see that module's doc: "no coupling to
/// commander-free's encrypted datastore ... deferred to a later Phase-1
/// step"). Nothing populates a `fleet_signing_key` field there yet as of
/// this task — see the handoff note. Absence degrades safely: every
/// `install_epoch` call is rejected with `SignerKeyMismatch` (fail closed)
/// until that field exists, never silently trusted.
#[cfg(windows)]
fn pinned_fleet_signing_key() -> String {
    extract_pinned_fleet_signing_key(&settings_host::get_settings())
}

/// Pure half of [`pinned_fleet_signing_key`] — split out so the field
/// lookup itself is unit-testable without touching the real settings file.
#[cfg(windows)]
fn extract_pinned_fleet_signing_key(settings: &serde_json::Value) -> String {
    settings
        .get("fleet_signing_key")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string()
}

/// Run `f`, catching any panic instead of letting it unwind past the
/// caller — the "must not panic the service on any single iteration
/// failure" contract every background loop needs. Returns `true` if `f`
/// completed without panicking. Logs a stable, content-free code (just
/// `loop_name`, never the panic payload, which could in principle carry
/// arbitrary data) so an operator can see a loop is degrading without a
/// panic message potentially leaking anything into service logs.
///
/// Uses `AssertUnwindSafe` rather than requiring `F: UnwindSafe` from
/// callers: `enforcement_loop`'s real closure captures `Arc<PolicyStore>`,
/// and `PolicyStore` holds `Box<dyn PolicyFs>`/`Box<dyn Clock>` fields the
/// compiler cannot automatically prove `RefUnwindSafe` for (trait objects
/// don't propagate auto traits they didn't explicitly declare). The assert
/// is sound here regardless: every piece of state a panic mid-iteration
/// could leave "torn" is behind a `Mutex` or an atomic, both of which are
/// `RefUnwindSafe` unconditionally and are already read through
/// poison-recovering locks (`unwrap_or_else(|p| p.into_inner())`)
/// throughout `pipe.rs`/`policy_store.rs`.
#[cfg(windows)]
fn run_iteration_catching_panics<F>(loop_name: &str, f: F) -> bool
where
    F: FnOnce(),
{
    match std::panic::catch_unwind(std::panic::AssertUnwindSafe(f)) {
        Ok(()) => true,
        Err(_) => {
            eprintln!("[wincommander-svc] {loop_name}: iteration panicked, continuing");
            false
        }
    }
}

/// Clipboard Guard's enforcement loop (Phase 2 — plan §9's "the first real
/// `commander-svc` loop"): each tick refreshes the policy-health flags,
/// prunes aged-out queued clipboard events, and derives the
/// clipboard-specific health flags (see [`pipe::enforcement_tick`] for
/// exactly how). Cancellation-aware via `tokio::time::sleep` (a normal
/// async yield point — the task is dropped cleanly if the runtime shuts
/// down while sleeping) and never panics the service on a single bad
/// iteration: [`run_iteration_catching_panics`] is defensive-in-depth on
/// top of `enforcement_tick`'s own no-panic design (poison-recovering
/// locks, no `unwrap`/`expect`, no unchecked indexing).
#[cfg(windows)]
async fn enforcement_loop(
    policy_store: Arc<policy_store::PolicyStore>,
    clipboard_state: Arc<pipe::ClipboardGuardState>,
) {
    loop {
        let ps = Arc::clone(&policy_store);
        let state = Arc::clone(&clipboard_state);
        run_iteration_catching_panics("enforcement_loop", move || {
            pipe::enforcement_tick(&ps, &state, std::time::Instant::now());
        });
        tokio::time::sleep(std::time::Duration::from_secs(30)).await;
    }
}

/// Phase 3 fills this in — settings reconciler (drift detection, repair).
#[cfg(windows)]
async fn reconciler_loop() {
    loop {
        tokio::time::sleep(std::time::Duration::from_secs(30)).await;
    }
}

/// Phase 3 fills this in — command worker (dequeue + execute fleet commands).
#[cfg(windows)]
async fn command_worker_loop() {
    loop {
        tokio::time::sleep(std::time::Duration::from_secs(30)).await;
    }
}

/// Phase 3 fills this in — fleet connection (heartbeat + telemetry upload).
#[cfg(windows)]
async fn fleet_conn_loop() {
    loop {
        tokio::time::sleep(std::time::Duration::from_secs(30)).await;
    }
}

// ── Tests ────────────────────────────────────────────────────────────────────

#[cfg(all(test, windows))]
mod tests {
    use super::*;

    #[test]
    fn extract_pinned_fleet_signing_key_reads_expected_field() {
        let v = serde_json::json!({ "fleet_signing_key": "abc123==" });
        assert_eq!(extract_pinned_fleet_signing_key(&v), "abc123==");
    }

    #[test]
    fn extract_pinned_fleet_signing_key_defaults_to_empty_when_absent() {
        let v = serde_json::json!({});
        assert_eq!(extract_pinned_fleet_signing_key(&v), "");
    }

    #[test]
    fn extract_pinned_fleet_signing_key_defaults_to_empty_on_wrong_type() {
        // A non-string value must degrade to "" (fail closed via
        // SignerKeyMismatch downstream), never panic on an `as_str()` that
        // returns `None`.
        let v = serde_json::json!({ "fleet_signing_key": 12345 });
        assert_eq!(extract_pinned_fleet_signing_key(&v), "");
    }

    #[test]
    fn stop_status_allows_bounded_vault_cleanup() {
        let status = stop_pending_status();
        assert_eq!(status.current_state, ServiceState::StopPending);
        assert_eq!(status.controls_accepted, ServiceControlAccept::empty());
        assert_eq!(status.checkpoint, 1);
        assert_eq!(status.wait_hint, std::time::Duration::from_secs(135));
    }

    // ── run_iteration_catching_panics: the loop-resilience contract ──────

    #[test]
    fn run_iteration_catching_panics_survives_a_panicking_iteration_and_reports_false() {
        let survived = run_iteration_catching_panics("test_loop", || {
            panic!("boom");
        });
        assert!(
            !survived,
            "a panicking iteration must report false, not propagate"
        );

        // A subsequent, non-panicking call succeeds — proves the earlier
        // panic didn't poison anything that would break later iterations,
        // i.e. the loop genuinely "survives" rather than merely delaying
        // the crash by one tick.
        let ok = run_iteration_catching_panics("test_loop", || {});
        assert!(ok);
    }

    #[test]
    fn run_iteration_catching_panics_does_not_swallow_a_clean_run() {
        let mut ran = false;
        let ok = run_iteration_catching_panics("test_loop", || {
            ran = true;
        });
        assert!(ok);
        assert!(ran);
    }
}
