// SPDX-License-Identifier: AGPL-3.0-or-later
//! Binding requirement #8 ("serde on all policy types"): every `MatchKind`
//! variant must actually round-trip through JSON, and the adjacently-
//! tagged shape (`{"kind": ..., "params": ...}`) must be what a TypeScript
//! consumer generated by `ts-codegen` would actually receive over the
//! wire — not just something that happens to derive without error.

mod common;

use wincmd_clip_rules::{Action, BuiltinPattern, MatchKind, Rule, Severity, StructuredKind};

fn round_trip(rule: Rule) -> Rule {
    let json = serde_json::to_string(&rule).expect("Rule must serialize");
    serde_json::from_str(&json).expect("Rule must deserialize from its own JSON")
}

#[test]
fn phrase_match_kind_round_trips() {
    let rule = common::rule(1, 1, MatchKind::Phrase { value: "abc".into(), case_sensitive: false });
    let back = round_trip(rule.clone());
    assert!(matches!(
        back.matcher,
        MatchKind::Phrase { ref value, case_sensitive: false } if value == "abc"
    ));
}

#[test]
fn regex_match_kind_round_trips() {
    let rule = common::rule(
        1,
        1,
        MatchKind::Regex { pattern: r"\d+".into(), case_sensitive: true },
    );
    let back = round_trip(rule);
    assert!(matches!(
        back.matcher,
        MatchKind::Regex { ref pattern, case_sensitive: true } if pattern == r"\d+"
    ));
}

#[test]
fn structured_match_kind_round_trips() {
    let rule = common::rule(1, 1, MatchKind::Structured(StructuredKind::Iban));
    let back = round_trip(rule);
    assert!(matches!(back.matcher, MatchKind::Structured(StructuredKind::Iban)));
}

#[test]
fn builtin_match_kind_round_trips() {
    let rule = common::rule(1, 1, MatchKind::Builtin(BuiltinPattern::AnthropicApiKey));
    let back = round_trip(rule);
    assert!(matches!(back.matcher, MatchKind::Builtin(BuiltinPattern::AnthropicApiKey)));
}

/// Spot-check the actual JSON shape a console/TS consumer would see for
/// each of the four `MatchKind` variants — adjacently tagged as
/// `{"kind": "...", "params": ...}`, including the two variants
/// (`Structured`/`Builtin`) that wrap another plain-string enum, which
/// internally-tagged serde cannot represent at all (see `rule.rs`'s doc
/// comment on `MatchKind` for why adjacent tagging was chosen).
#[test]
fn adjacent_tagging_shape_is_kind_and_params() {
    let phrase = serde_json::to_value(MatchKind::Phrase { value: "x".into(), case_sensitive: true }).unwrap();
    assert_eq!(phrase["kind"], "phrase");
    assert_eq!(phrase["params"]["value"], "x");
    assert_eq!(phrase["params"]["case_sensitive"], true);

    let structured = serde_json::to_value(MatchKind::Structured(StructuredKind::PaymentCard)).unwrap();
    assert_eq!(structured["kind"], "structured");
    assert_eq!(structured["params"], "payment_card");

    let builtin = serde_json::to_value(MatchKind::Builtin(BuiltinPattern::NpmToken)).unwrap();
    assert_eq!(builtin["kind"], "builtin");
    assert_eq!(builtin["params"], "npm_token");
}

#[test]
fn rule_level_fields_round_trip_including_actions_and_severity() {
    let mut rule = common::rule(0x42, 777, MatchKind::Builtin(BuiltinPattern::Jwt));
    rule.severity = Severity::Critical;
    rule.actions = vec![Action::ClearClipboard, Action::ReportFleet, Action::AlertAdmin];
    rule.cooldown_seconds = 120;

    let back = round_trip(rule.clone());
    assert_eq!(back.id, rule.id);
    assert_eq!(back.priority, 777);
    assert_eq!(back.severity, Severity::Critical);
    assert_eq!(back.actions, vec![Action::ClearClipboard, Action::ReportFleet, Action::AlertAdmin]);
    assert_eq!(back.cooldown_seconds, 120);
}
