import { useEffect, useState } from "react";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "../../components/ui/alert-dialog";
import { Badge } from "../../components/ui/badge";
import { Button } from "../../components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../../components/ui/card";
import { Icon } from "../../components/ui/icon";
import { formatBytes } from "./routineCleanerHelpers";
import { usePerformanceTools } from "./usePerformanceTools";

export function PerformanceTools() {
  const tools = usePerformanceTools();
  const { refresh } = tools;
  const [pending, setPending] = useState<"apply" | "restore">();
  useEffect(() => {
    if (!tools.snapshot && !tools.gameMode && !tools.busy && !tools.error) void refresh();
  }, [refresh, tools.busy, tools.error, tools.gameMode, tools.snapshot]);
  return <div className="flex flex-col gap-4">
    <Card><CardHeader><CardTitle>Performance snapshot</CardTitle><CardDescription>Bounded local snapshot of system, disks, network interfaces, and top resource consumers.</CardDescription></CardHeader><CardContent className="flex flex-wrap items-center gap-2"><Button size="icon" variant="primary" disabled={tools.busy} onClick={() => void tools.refresh()} title={tools.snapshot ? "Refresh performance snapshot" : "Scan performance snapshot"} aria-label={tools.snapshot ? "Refresh performance snapshot" : "Scan performance snapshot"}><Icon icon={tools.snapshot ? "refresh" : "search"} className={tools.busy ? "animate-spin" : undefined} /></Button>{tools.snapshot && <><Badge tone="accent">CPU {tools.snapshot.cpuUsagePercent.toFixed(1)}%</Badge><Badge tone="accent">RAM {formatBytes(tools.snapshot.memoryUsedBytes)} / {formatBytes(tools.snapshot.memoryTotalBytes)}</Badge><Badge tone="accent">{tools.snapshot.logicalCores} logical cores</Badge></>}</CardContent></Card>
    {tools.error && <Card><CardContent className="flex items-center gap-3 py-4"><Badge tone="danger">error</Badge><p className="text-sm text-[var(--text-dim)]">{tools.error}</p></CardContent></Card>}
    {tools.gameMode && <Card><CardHeader><div className="flex items-center justify-between gap-2"><CardTitle>Reversible Game Mode</CardTitle><Badge tone={tools.gameMode.profileActive ? "success" : "warning"}>{tools.gameMode.profileActive ? "active" : "inactive"}</Badge></div><CardDescription>Only Windows Game Mode registry values are changed. Security, updates, services, and power policy are untouched; exact prior values are journaled for restore.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{tools.gameMode.changes.map((change) => <div key={change.name} className="flex items-center justify-between gap-3 rounded-[var(--r)] border border-[var(--border)] px-3 py-2"><span className="font-mono text-xs text-[var(--text)]">{change.name}</span><Badge tone={change.willChange ? "warning" : "success"}>{change.willChange ? "will change" : "already enabled"}</Badge></div>)}<div className="flex flex-wrap justify-end gap-2">{tools.gameMode.restoreAvailable && <Button variant="outline" disabled={tools.busy} onClick={() => setPending("restore")}>Restore prior state</Button>}<Button variant="primary" disabled={tools.busy || tools.gameMode.profileActive} onClick={() => setPending("apply")}>Apply Game Mode</Button></div></CardContent></Card>}
    {tools.snapshot && <div className="grid gap-4 xl:grid-cols-2"><ProcessCard title="Top CPU" rows={tools.snapshot.topCpuProcesses.map((process) => ({ id: process.pid, name: process.name, detail: `${process.cpuUsagePercent.toFixed(1)}% · ${formatBytes(process.memoryBytes)}` }))} /><ProcessCard title="Top memory" rows={tools.snapshot.topMemoryProcesses.map((process) => ({ id: process.pid, name: process.name, detail: `${formatBytes(process.memoryBytes)} · CPU ${process.cpuUsagePercent.toFixed(1)}%` }))} /></div>}
    {tools.snapshot && <Card><CardHeader><CardTitle>Disks and network</CardTitle></CardHeader><CardContent className="grid gap-2 xl:grid-cols-2">{tools.snapshot.disks.map((disk) => <MetricRow key={disk.mountPoint} title={`${disk.name} ${disk.mountPoint}`} detail={`${disk.usedPercent.toFixed(1)}% used · ${formatBytes(disk.availableBytes)} free`} />)}{tools.snapshot.networkInterfaces.map((network) => <MetricRow key={network.name} title={network.name} detail={`↓ ${formatBytes(network.receivedBytesSinceLastRefresh)} · ↑ ${formatBytes(network.transmittedBytesSinceLastRefresh)}`} />)}</CardContent></Card>}
    <AlertDialog open={pending !== undefined} onOpenChange={(open) => { if (!open) setPending(undefined); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{pending === "restore" ? "Restore pre-Game Mode state?" : "Apply Game Mode?"}</AlertDialogTitle><AlertDialogDescription>{pending === "restore" ? "The exact registry values journaled before activation will be restored." : "WinCommander will snapshot the current allowlisted values, enable Windows Game Mode, and retain a restore journal."}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Back</AlertDialogCancel><AlertDialogAction onClick={() => { const action = pending; setPending(undefined); if (action === "restore") void tools.restore(); else if (action === "apply") void tools.apply(); }}>Continue</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}

function ProcessCard({ title, rows }: { title: string; rows: Array<{ id: number; name: string; detail: string }> }) { return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent className="flex flex-col gap-2">{rows.slice(0, 8).map((row) => <MetricRow key={`${row.id}-${row.name}`} title={`${row.name} · PID ${row.id}`} detail={row.detail} />)}</CardContent></Card>; }
function MetricRow({ title, detail }: { title: string; detail: string }) { return <div className="rounded-[var(--r)] border border-[var(--border)] px-3 py-2"><p className="truncate text-sm text-[var(--text)]">{title}</p><p className="font-mono text-[11px] text-[var(--text-mute)]">{detail}</p></div>; }
