// tools/gen-types.ts
//
// ═══════════════════════════════════════════════════════════════════════
// SSOT codegen — Rust wire types → TypeScript
// ═══════════════════════════════════════════════════════════════════════
//
// The wire types shared between the Rust side and the frontend are defined
// ONCE in Rust and derived into TypeScript via ts-rs (gated behind the
// `ts-codegen` Cargo feature). Three crates own wire types:
//   - `fleet-proto`      — fleet.ts (extracted SSOT for the fleet wire
//                          protocol; also consumed by
//                          fleet-server/TuxCommander/secureOS).
//   - `wincmd-clip-rules` — ALSO contributes to fleet.ts: the clipboard-guard
//                          policy types (Rule, MatchKind, Severity, Action,
//                          StructuredKind, BuiltinPattern, RuleSetLimits,
//                          RuleId, ...) are defined physically in this crate
//                          and merely re-exported by `fleet-proto`. ts-rs
//                          resolves `export_to` against the CARGO_MANIFEST_DIR
//                          of the crate that OWNS the derive, not the crate
//                          under test, so these land in
//                          `wincmd-clip-rules/bindings/fleet.ts` — a SEPARATE
//                          file from fleet-proto's own `bindings/fleet.ts` —
//                          even though both declare `export_to = "fleet.ts"`.
//                          A couple of them (Action, Severity) also get
//                          incidentally pulled into fleet-proto's own copy as
//                          a dependency of ClipboardEventReport/
//                          InkReceiptReport, but the rest (Rule, MatchKind,
//                          ...) are never referenced as a field of any
//                          fleet-proto-native type, so nothing chases them in
//                          — running THIS crate's own ts-codegen tests is the
//                          only way they get emitted at all. Both fragments
//                          are merged (deduped by exported identifier) below.
//   - `wincmd-shared`    — ipc.ts (Free<->Pro IPC envelope) + serde_json's
//                          JsonValue.ts (emitted as a side effect of any
//                          `serde_json::Value` field in its types).
// This script runs codegen for all three crates, normalizes + merges the raw
// ts-rs output, and writes the single tracked copy into
// `src/types/generated/` — the only location the frontend imports from.
//
//   bun run gen:types          # regenerate src/types/generated/*
//   bun run gen:types:check    # exit 1 if the committed output is stale
//
// `bindings/` (ts-rs's own output dir, one per crate) is a gitignored build
// artifact; this tool is the only thing that reads it. The --check mode is
// wired into CI by .github/workflows/invariants.yml (codegen-drift job) so a
// Rust wire-type change that isn't accompanied by a regenerate fails the merge.

import { spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const SRC_TAURI = join(ROOT, "src-tauri");
const FLEET_PROTO_BINDINGS = join(SRC_TAURI, "fleet-proto", "bindings");
const WINCMD_CLIP_RULES_BINDINGS = join(SRC_TAURI, "wincmd-clip-rules", "bindings");
const WINCMD_SHARED_BINDINGS = join(SRC_TAURI, "wincmd-shared", "bindings");
const OUT_DIR = join(ROOT, "src", "types", "generated");

// Files ts-rs emits, each paired with the bindings dir(s) (crate(s)) it comes
// from. Keep in sync with the `ts(export, export_to = "…")` attributes in
// fleet-proto / wincmd-clip-rules / wincmd-shared. `fleet.ts` lists TWO
// bindings dirs because `wincmd-clip-rules` physically owns some of the
// types re-exported through `fleet-proto` (see the header comment above) —
// its fragment is merged with fleet-proto's own before being written out.
const FILES = [
  { rel: "fleet.ts", bindingsDirs: [FLEET_PROTO_BINDINGS, WINCMD_CLIP_RULES_BINDINGS] },
  { rel: "ipc.ts", bindingsDirs: [WINCMD_SHARED_BINDINGS] },
  { rel: "serde_json/JsonValue.ts", bindingsDirs: [WINCMD_SHARED_BINDINGS] },
] as const;

const TSRS_HEADER_PREFIX = "// This file was generated by";
const REGEN_HINT = "// Regenerate: bun run gen:types  (do not edit by hand)";

function runCargoTest(pkg: string): void {
  const res = spawnSync(
    "cargo",
    ["test", "-p", pkg, "--features", "ts-codegen", "--quiet"],
    { cwd: SRC_TAURI, stdio: "inherit" },
  );
  if (res.status !== 0) {
    console.error(
      `✖ ts-rs codegen failed (cargo test -p ${pkg} --features ts-codegen).`,
    );
    process.exit(1);
  }
}

function runCodegen(): void {
  runCargoTest("fleet-proto");
  // Must run as its own `-p` target: its ts-codegen export tests are
  // compiled into ITS OWN test binary, not fleet-proto's, even though
  // fleet-proto enables `wincmd-clip-rules/ts-codegen` and re-exports its
  // types — feature unification makes the derive compile, but a dependency
  // crate's `#[test]` functions never run just because the crate depending
  // on it is under test. Skipping this silently drops Rule/MatchKind/
  // StructuredKind/BuiltinPattern/RuleSetLimits/RuleId from fleet.ts.
  runCargoTest("wincmd-clip-rules");
  runCargoTest("wincmd-shared");
}

// Canonical committed form, applied identically to raw ts-rs output AND to an
// already-committed file (so it is idempotent and the --check comparison is
// robust to CRLF/LF and trailing-whitespace noise):
//   • LF line endings
//   • per-line trailing whitespace trimmed
//   • the machine-independent regen hint inserted right after the ts-rs header
//   • exactly one trailing newline
function canonical(raw: string): string {
  const lines = raw
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((l) => l.replace(/[ \t]+$/g, ""));
  while (lines.length && lines[lines.length - 1] === "") lines.pop();
  if (lines.length && lines[0].startsWith(TSRS_HEADER_PREFIX)) {
    if (lines[1] !== REGEN_HINT) lines.splice(1, 0, REGEN_HINT);
  } else {
    lines.unshift(REGEN_HINT);
  }
  return lines.join("\n") + "\n";
}

// ts-rs writes crate-local binding files as a side effect of both generation
// and --check. Keep those emitted files whitespace-clean too; one of them is a
// tracked compatibility artifact and otherwise makes `git diff --check` fail
// immediately after a successful generated-type check.
function canonicalEmitted(raw: string): string {
  const lines = raw
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((l) => l.replace(/[ \t]+$/g, ""));
  while (lines.length && lines[lines.length - 1] === "") lines.pop();
  return lines.join("\n") + "\n";
}

// Merges ts-rs output fragments that legitimately share one `export_to`
// filename but land in different crates' `bindings/` dirs (see the header
// comment's `wincmd-clip-rules` note). Each fragment is a full ts-rs file:
// a one-line banner, optional `import type` lines, then blank-line-separated
// top-level `export type`/`export interface` declarations. Preamble lines
// are unioned (deduped verbatim, first-seen order); declarations are deduped
// by exported identifier (fragments that legitimately share a type — e.g.
// `Action`/`Severity`, emitted both by fleet-proto's dependency chase AND
// wincmd-clip-rules' own direct export test — produce byte-identical text,
// so keeping the first occurrence is safe) and re-sorted alphabetically to
// match ts-rs's own within-file ordering convention.
function mergeFleetFragments(fragments: string[]): string {
  const preambleLines: string[] = [];
  const seenPreambleLines = new Set<string>();
  const seenNames = new Set<string>();
  const named: { name: string; block: string }[] = [];

  for (const raw of fragments) {
    const normalized = raw.replace(/\r\n/g, "\n").trimEnd();
    const splitAt = normalized.indexOf("\n\n");
    const preamble = splitAt === -1 ? normalized : normalized.slice(0, splitAt);
    const rest = splitAt === -1 ? "" : normalized.slice(splitAt + 2);

    for (const line of preamble.split("\n")) {
      if (!seenPreambleLines.has(line)) {
        seenPreambleLines.add(line);
        preambleLines.push(line);
      }
    }

    for (const block of rest.split(/\n\n+/)) {
      if (block.trim() === "") continue;
      const m = block.match(/^export (?:type|interface) (\w+)/m);
      // No declaration name found (shouldn't happen for a well-formed ts-rs
      // fragment) — fall back to the block text itself so it still gets
      // deduped against a byte-identical repeat rather than dropped/thrown.
      const name = m ? m[1] : block;
      if (seenNames.has(name)) continue;
      seenNames.add(name);
      named.push({ name, block });
    }
  }

  named.sort((a, b) => a.name.localeCompare(b.name));
  return [preambleLines.join("\n"), ...named.map((n) => n.block)].join("\n\n") + "\n";
}

const check = process.argv.includes("--check");

const emittedSnapshots = new Map<string, string | null>();
if (check) {
  for (const { rel, bindingsDirs } of FILES) {
    for (const bindingsDir of bindingsDirs) {
      const emittedPath = join(bindingsDir, rel);
      emittedSnapshots.set(
        emittedPath,
        existsSync(emittedPath) ? readFileSync(emittedPath, "utf8") : null,
      );
    }
  }
  process.on("exit", () => {
    for (const [emittedPath, original] of emittedSnapshots) {
      if (original === null) {
        if (existsSync(emittedPath)) unlinkSync(emittedPath);
      } else {
        mkdirSync(dirname(emittedPath), { recursive: true });
        writeFileSync(emittedPath, original);
      }
    }
  });
}

runCodegen();

let drift = false;
for (const { rel, bindingsDirs } of FILES) {
  const emittedPaths = bindingsDirs.map((dir) => join(dir, rel));
  for (const emittedPath of emittedPaths) {
    if (!existsSync(emittedPath)) {
      console.error(`✖ expected ts-rs to emit ${rel} but it is missing at ${emittedPath}.`);
      process.exit(1);
    }
  }
  const emittedFragments = emittedPaths.map((emittedPath) => {
    const raw = readFileSync(emittedPath, "utf8");
    const normalized = canonicalEmitted(raw);
    if (!check && raw !== normalized) writeFileSync(emittedPath, normalized);
    return normalized;
  });
  const raw =
    emittedFragments.length === 1
      ? emittedFragments[0]
      : mergeFleetFragments(emittedFragments);
  const want = canonical(raw);
  const outPath = join(OUT_DIR, rel);

  if (check) {
    const got = existsSync(outPath)
      ? canonical(readFileSync(outPath, "utf8"))
      : "";
    if (got !== want) {
      drift = true;
      console.error(`✖ drift: src/types/generated/${rel} is out of sync with the Rust source.`);
    } else {
      console.log(`✓ ${rel}`);
    }
  } else {
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, want);
    console.log(`wrote src/types/generated/${rel}`);
  }
}

if (check) {
  if (drift) {
    console.error("\nA Rust wire type changed without regenerating its TS. Run `bun run gen:types` and commit the result.");
    process.exit(1);
  }
  console.log("\n✓ generated TS types are in sync with the Rust source.");
}
