// tools/gen-types.ts
//
// ═══════════════════════════════════════════════════════════════════════
// SSOT codegen — Rust wire types → TypeScript
// ═══════════════════════════════════════════════════════════════════════
//
// The wire types shared between the Rust side and the frontend are defined
// ONCE in Rust and derived into TypeScript via ts-rs (gated behind the
// `ts-codegen` Cargo feature). Two crates own wire types:
//   - `fleet-proto`   — fleet.ts (extracted SSOT for the fleet wire protocol;
//                       also consumed by fleet-server/TuxCommander/secureOS).
//   - `wincmd-shared` — ipc.ts (Free<->Pro IPC envelope) + serde_json's
//                       JsonValue.ts (emitted as a side effect of any
//                       `serde_json::Value` field in its types).
// This script runs codegen for BOTH crates, normalizes the raw ts-rs output,
// and writes the single tracked copy into `src/types/generated/` — the only
// location the frontend imports from.
//
//   bun run gen:types          # regenerate src/types/generated/*
//   bun run gen:types:check    # exit 1 if the committed output is stale
//
// `bindings/` (ts-rs's own output dir, one per crate) is a gitignored build
// artifact; this tool is the only thing that reads it. The --check mode is
// wired into CI by .github/workflows/invariants.yml (codegen-drift job) so a
// Rust wire-type change that isn't accompanied by a regenerate fails the merge.

import { spawnSync } from "node:child_process";
import {
  existsSync,
  mkdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const SRC_TAURI = join(ROOT, "src-tauri");
const FLEET_PROTO_BINDINGS = join(SRC_TAURI, "fleet-proto", "bindings");
const WINCMD_SHARED_BINDINGS = join(SRC_TAURI, "wincmd-shared", "bindings");
const OUT_DIR = join(ROOT, "src", "types", "generated");

// Files ts-rs emits, each paired with the bindings dir (crate) it comes from.
// Keep in sync with the `ts(export, export_to = "…")` attributes in
// fleet-proto / wincmd-shared.
const FILES = [
  { rel: "fleet.ts", bindings: FLEET_PROTO_BINDINGS },
  { rel: "ipc.ts", bindings: WINCMD_SHARED_BINDINGS },
  { rel: "serde_json/JsonValue.ts", bindings: WINCMD_SHARED_BINDINGS },
] as const;

const TSRS_HEADER_PREFIX = "// This file was generated by";
const REGEN_HINT = "// Regenerate: bun run gen:types  (do not edit by hand)";

function runCargoTest(pkg: string): void {
  const res = spawnSync(
    "cargo",
    ["test", "-p", pkg, "--features", "ts-codegen", "--quiet"],
    { cwd: SRC_TAURI, stdio: "inherit" },
  );
  if (res.status !== 0) {
    console.error(
      `✖ ts-rs codegen failed (cargo test -p ${pkg} --features ts-codegen).`,
    );
    process.exit(1);
  }
}

function runCodegen(): void {
  runCargoTest("fleet-proto");
  runCargoTest("wincmd-shared");
}

// Canonical committed form, applied identically to raw ts-rs output AND to an
// already-committed file (so it is idempotent and the --check comparison is
// robust to CRLF/LF and trailing-whitespace noise):
//   • LF line endings
//   • per-line trailing whitespace trimmed
//   • the machine-independent regen hint inserted right after the ts-rs header
//   • exactly one trailing newline
function canonical(raw: string): string {
  const lines = raw
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((l) => l.replace(/[ \t]+$/g, ""));
  while (lines.length && lines[lines.length - 1] === "") lines.pop();
  if (lines.length && lines[0].startsWith(TSRS_HEADER_PREFIX)) {
    if (lines[1] !== REGEN_HINT) lines.splice(1, 0, REGEN_HINT);
  } else {
    lines.unshift(REGEN_HINT);
  }
  return lines.join("\n") + "\n";
}

const check = process.argv.includes("--check");

runCodegen();

let drift = false;
for (const { rel, bindings } of FILES) {
  const emittedPath = join(bindings, rel);
  if (!existsSync(emittedPath)) {
    console.error(`✖ expected ts-rs to emit ${rel} but it is missing.`);
    process.exit(1);
  }
  const want = canonical(readFileSync(emittedPath, "utf8"));
  const outPath = join(OUT_DIR, rel);

  if (check) {
    const got = existsSync(outPath)
      ? canonical(readFileSync(outPath, "utf8"))
      : "";
    if (got !== want) {
      drift = true;
      console.error(`✖ drift: src/types/generated/${rel} is out of sync with the Rust source.`);
    } else {
      console.log(`✓ ${rel}`);
    }
  } else {
    mkdirSync(dirname(outPath), { recursive: true });
    writeFileSync(outPath, want);
    console.log(`wrote src/types/generated/${rel}`);
  }
}

if (check) {
  if (drift) {
    console.error("\nA Rust wire type changed without regenerating its TS. Run `bun run gen:types` and commit the result.");
    process.exit(1);
  }
  console.log("\n✓ generated TS types are in sync with the Rust source.");
}
