// tools/inline-logo.mjs
//
// Reads assets/products/wincommander/logo.png and writes a base64 data URL
// constant to src/assets/logoData.ts. Run after replacing the logo:
//
//     node tools/inline-logo.mjs
//
// The splash screen imports LOGO_DATA_URL and uses it directly as the
// img src. Inlining avoids the first-install "blank logo plate" failure
// mode where the WebView's asset cache is cold and the PNG takes too
// long to load before the splash dismisses.

import { readFileSync, writeFileSync, statSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const src = resolve(root, "assets/products/wincommander/logo.png");
const dst = resolve(root, "src/assets/logoData.ts");

const bytes = readFileSync(src);
const dataUrl = "data:image/png;base64," + bytes.toString("base64");

const banner = [
    "// AUTO-GENERATED by tools/inline-logo.mjs — do not edit by hand.",
    "//",
    "// Re-generate after replacing assets/products/wincommander/logo.png:",
    "//   node tools/inline-logo.mjs",
    "//",
    "// Why inline? The splash screen showed a blank logo plate on first",
    "// install when Defender was scanning the bundle and the PNG disk",
    "// read took longer than the splash's safety timer. Inlining the",
    "// image as a base64 data URL puts the bytes in the JS bundle so",
    "// they're in memory the instant React mounts. No disk read, no",
    "// asset-protocol round-trip, no first-install cache cold start.",
    "",
].join("\n");

writeFileSync(
    dst,
    banner + "export const LOGO_DATA_URL = " + JSON.stringify(dataUrl) + ";\n",
);

const kb = (dataUrl.length / 1024).toFixed(1);
console.log(`✓ wrote ${dst}`);
console.log(`  source: ${src} (${(statSync(src).size / 1024).toFixed(1)} KB raw → ${kb} KB base64)`);
