// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

/**
 * Risk tier of a remote action — drives the safety-gate ladder in the fleet
 * server (Milestone 3) and tells the admin panel which confirmation UI to
 * render. Contains no command strings.
 */
export type ActionClass = "safe" | "destructive" | "irreversible";

/**
 * One admin account as listed by the admin-management UI. Carries `admin_id`
 * (needed to update/delete), unlike `AdminView` (the "who am I" shape).
 */
export type AdminAccount = { admin_id: string, email: string, role: AdminRole, };

/**
 * Admin authority levels, ascending. The fleet server enforces a minimum role
 * per privileged action; the admin panel uses it to show/hide controls (UI is
 * not a security control — the server re-checks every request).
 */
export type AdminRole = "viewer" | "operator" | "admin" | "super_admin";

/**
 * Non-secret view of the authenticated admin (the panel's "who am I").
 */
export type AdminView = { email: string, role: AdminRole, };

/**
 * Latest framework-authoritative Android status exposed to fleet operators.
 */
export type AndroidFleetStatus = { framework_key_fingerprint: string, deadman_ladder_step: number, authoritative_last_contact_age_seconds: bigint, audit_ledger_count: bigint, audit_ledger_head_hash: string, reported_at: string, };

/**
 * Per-(kind) breakdown within a device's Argus rollup — a severity-aware,
 * unit-consistent bucket. Every signal in a bucket shares one `kind`, so their
 * `magnitude` is commensurable (bytes with bytes, pages with pages) — unlike
 * the flat `total_magnitude`, which mixes incommensurable units. Aggregate
 * scalars only — no filenames, paths, URLs, printer/document names, or
 * usernames (the Argus privacy invariant).
 */
export type ArgusKindBucket = { 
/**
 * High-level category: "dlp_exfil" | "tamper" | "print" | "removable_media" | "tripwire" | "access".
 */
kind: string, 
/**
 * Single sub-type label shared by every signal in the bucket, or `None`
 * when the kind spans multiple classes (mixed → collapse to kind level).
 */
class: string | null, 
/**
 * Number of signal records in this bucket.
 */
count: bigint, 
/**
 * Sum of magnitude within this single-kind bucket (commensurable units).
 */
magnitude: bigint, 
/**
 * Highest severity seen, ordered info < warn < critical.
 */
max_severity: string, };

/**
 * Argus security-signal sample sent by an agent. Carries NO filenames, paths,
 * URLs, printer names, document names, or usernames — only kind + class +
 * magnitude + severity + a disclosure-notice version. `consent_version` is
 * vestigial (hardcoded `1`, never read) — there is no consent gate; ingest is
 * never refused for a disclosure_version mismatch, only recorded as one.
 * kind ∈ {"dlp_exfil","tamper","print","removable_media"}.
 * class = sub-type label (e.g. "usb_large_transfer", "log_cleared").
 * magnitude = aggregate scalar (bytes / pages / count).
 */
export type ArgusSignal = { window_start: string, window_end: string, 
/**
 * High-level category: "dlp_exfil" | "tamper" | "print" | "removable_media" | "tripwire" | "access"
 */
kind: string, 
/**
 * Sub-type label within the kind (no PII — e.g. "usb_large_transfer").
 */
class: string, 
/**
 * Aggregate scalar for this window (bytes transferred, pages printed, count).
 */
magnitude: bigint, 
/**
 * "info" | "warn" | "critical"
 */
severity: string, consent_version: number, disclosure_version: number, };

/**
 * One raw Argus signal record in a device's drill-down window (Feature C). The
 * per-signal row behind the aggregated `DeviceArgusSummary` — still PII-free.
 */
export type ArgusSignalDetail = { window_start: string, window_end: string, kind: string, class: string, magnitude: bigint, severity: string, consent_version: number, disclosure_version: number, };

/**
 * Assign (or, with `None`, clear) a device's group (Admin+).
 */
export type AssignGroupRequest = { group_id: string | null, };

/**
 * One audit-log entry as returned to the admin panel. Shared so the server and
 * the panel agree on the shape (SSOT) — RFC 3339 `at`.
 */
export type AuditEntry = { actor: string, action: string, target: string | null, outcome: string, detail: JsonValue, at: string, };

/**
 * Discoverable, AV-safe catalog metadata for one remote command. Mirrors an
 * entry in commander-pro's `fleet_dispatch::COMMAND_CATALOG` but deliberately
 * excludes `feature_id` (the AV-flagged Pro handler name) — only
 * `catalog_id` + `action_class` + a human-safe `summary` + an optional
 * hand-authored `payload_schema` cross the wire to integrators.
 */
export type CommandMeta = { catalog_id: string, action_class: ActionClass, summary: string, 
/**
 * Compact JSON-Schema-ish literal string, or `None` for parameterless
 * commands. Kept as a JSON *string* (not a parsed `Value`) so this
 * struct — and the `COMMAND_METADATA` table below — stays a `const`.
 */
payload_schema: string | null, };

/**
 * Admin request to create a remote command. `catalog_id` references a
 * COMMAND_CATALOG entry — NEVER a raw command string. `confirmation_token` is
 * required for irreversible actions (obtained from the confirm-token endpoint).
 */
export type CommandRequest = { device_id: DeviceId, catalog_id: string, action_class: ActionClass, payload: JsonValue, idempotency_key: string, confirmation_token: string | null, };

/**
 * Lifecycle of a remote command. `pending` awaits multi-party approval;
 * `approved` is signed and pollable; `dispatched` was handed to the agent;
 * `acked`/`failed` are terminal results.
 */
export type CommandStatus = "pending" | "approved" | "dispatched" | "acked" | "failed" | "rejected" | "expired";

/**
 * Admin-facing view of a command and its gate state.
 */
export type CommandView = { command_id: string, device_id: DeviceId, catalog_id: string, action_class: ActionClass, status: CommandStatus, approvals: number, required_approvals: number, requested_by: string, created_at: string, 
/**
 * Command payload — included so the admin panel can reconstruct current
 * per-capability state from command history without a separate endpoint.
 */
payload: JsonValue, };

/**
 * A signed, versioned configuration snapshot. Append-only and monotonic per
 * org; agents reject any epoch whose `version` is <= the one they hold
 * (anti-rollback). `config_json` is `AppSettings`-shaped policy.
 *
 * Fleet Control Plane P2 adds **targeting** + **locks**: an epoch is scoped to
 * a target (org / group / device) and carries the settings paths the device
 * must not let the local user change (`locked_paths`). The signature binds ALL
 * of these via [`epoch_signing_envelope`] so a device cannot replay another
 * scope's policy (target spoofing) or strip the locks (downgrade).
 */
export type ConfigEpoch = { org_id: OrgId, version: bigint, config_json: JsonValue, 
/**
 * Scope this epoch applies to: "org" | "group" | "device". Defaults to
 * "org" for epochs published before targeting existed.
 */
target_kind: string, 
/**
 * Target id within the kind (group_id / device_id). `None` for org-wide.
 */
target_id: string | null, 
/**
 * Settings dot-paths the device must keep at the published value — locked
 * against local edits while the device is fleet-managed.
 */
locked_paths: Array<string>, 
/**
 * P5 enrollment lock: when true the device should refuse a local unenroll
 * without admin approval. Carried here (signed) so it can't be spoofed.
 */
managed: boolean, 
/**
 * Base64 Ed25519 signature over [`canonical_epoch_bytes`]`(version,
 * epoch_signing_envelope(config_json, locked_paths, managed, target))`.
 */
signature: string, 
/**
 * Base64 of the public key that produced `signature` (lets agents pin the
 * fleet signing key and detect rotation).
 */
signer_key: string, };

/**
 * Admin request to publish new policy. The server assigns the next monotonic
 * version and signs it; the admin never supplies version or signature.
 */
export type ConfigPushRequest = { config_json: JsonValue, 
/**
 * Scope: "org" (default) | "group" | "device".
 */
target_kind: string, 
/**
 * group_id / device_id for a scoped push; ignored for "org".
 */
target_id: string | null, 
/**
 * Settings dot-paths to lock on the targeted devices.
 */
locked_paths: Array<string>, 
/**
 * Mark the targeted devices enrollment-locked (P5).
 */
managed: boolean, };

/**
 * Request a single-use confirmation token for an irreversible action.
 */
export type ConfirmTokenRequest = { device_id: DeviceId, catalog_id: string, };

/**
 * Issued confirmation token (single-use, short-lived, bound to device+catalog).
 */
export type ConfirmTokenResponse = { token: string, expires_at: string, };

/**
 * Create a new admin (super_admin only). The password is hashed server-side
 * (argon2id) and never stored or echoed in plaintext.
 */
export type CreateAdminRequest = { email: string, password: string, role: AdminRole, };

/**
 * Create a device group (Admin+).
 */
export type CreateGroupRequest = { name: string, };

/**
 * Per-device Argus monitoring-coverage view for the admin (Feature B —
 * transparency). Tells the admin whether Argus is actually observing a device,
 * under which disclosure version, whether disclosure is in good standing (no
 * recent disclosure-mismatch ingest denial in the audit log), and which signal
 * kinds have been seen. Aggregate/opaque scalars only — no PII.
 */
export type DeviceArgusCoverage = { device_id: DeviceId, hostname: string | null, 
/**
 * True when ≥1 Argus signal was ingested for this device within the window.
 */
monitoring_active: boolean, 
/**
 * RFC 3339 window_end of the most recent ingested signal, else `None`.
 */
last_signal_at: string | null, 
/**
 * Disclosure version of the most recent ingested signal, else `None`.
 * (Ingested signals always satisfy consent_version == disclosure_version.)
 */
disclosure_version: number | null, 
/**
 * Distinct signal kinds observed for this device in the window, sorted asc.
 */
kinds_observed: Array<string>, 
/**
 * Number of signal records ingested for this device in the window.
 */
signal_count: bigint, 
/**
 * False when a disclosure-mismatch ingest denial was recorded for this
 * device in the audit log within the window.
 */
disclosure_in_good_standing: boolean, 
/**
 * RFC 3339 timestamp of the most recent disclosure-mismatch denial, else `None`.
 */
last_disclosure_mismatch_at: string | null, };

/**
 * Per-device Argus signal rollup for the admin dashboard.
 */
export type DeviceArgusSummary = { device_id: DeviceId, hostname: string | null, 
/**
 * Total number of signal records for this device in the window.
 */
signal_count: bigint, 
/**
 * Sum of magnitude across all signals. NOTE: mixes incommensurable units
 * (bytes + pages + counts) — kept for back-compat; prefer `by_kind` and
 * `risk_score` for a meaningful read.
 */
total_magnitude: bigint, 
/**
 * RFC 3339 timestamp of the most recent signal window end.
 */
last_window_end: string | null, 
/**
 * Per-kind severity-aware breakdown (additive). Sorted by `kind`. Each
 * bucket aggregates one commensurable signal family so magnitudes never mix.
 */
by_kind: Array<ArgusKindBucket>, 
/**
 * Normalised insider-risk score (additive). Severity-weighted signal
 * volume, unit-independent — see `store::argus_risk_score` for the model.
 */
risk_score: bigint, };

/**
 * Per-device drift view (F7): how the device's applied epoch compares to the
 * org's latest published policy epoch.
 */
export type DeviceDrift = { device_id: DeviceId, hostname: string | null, applied_epoch: bigint, latest_epoch: bigint, drifted: boolean, last_reported: string | null, };

/**
 * A device group — a named bucket of devices within an org (F4). Membership is
 * 1:1 (a device is in at most one group) and stored separately from `devices`.
 */
export type DeviceGroup = { group_id: string, org_id: OrgId, name: string, };

/**
 * Device identifier — the agent's `settings.device_id` (a UUID) carried as a
 * string on the wire so this crate stays dependency-light (no `uuid`). The
 * fleet server parses it to a real UUID at the storage boundary.
 */
export type DeviceId = string;

/**
 * Explicit lifecycle state of an enrolled device. `pending` is reserved for a
 * future approve-before-active enrollment flow; devices enrolled today start
 * `active`. `suspended` is reversible (temporary hold — no re-enroll needed to
 * lift it); `revoked` and `decommissioned` are terminal (all credential
 * material is invalidated; the device must re-enroll to rejoin, subject to the
 * blocklist). A `suspended` or `revoked` device is denied config resolution and
 * command polling.
 */
export type DeviceLifecycle = "pending" | "active" | "suspended" | "revoked" | "decommissioned";

/**
 * Per-device productivity rollup for the admin dashboard.
 */
export type DeviceProductivity = { device_id: DeviceId, hostname: string | null, active_seconds: bigint, idle_seconds: bigint, sample_count: bigint, last_window_end: string | null, 
/**
 * Per-category weighted totals folded from each sample's `category_scores`
 * (each score weighted by that sample's `active_seconds`), e.g.
 * `{"productive": 135.0, "distracting": 20.0}`. Aggregate scalars only — no
 * PII. Empty object when no samples carried category scores.
 */
category_totals: JsonValue, };

/**
 * Agent → server live resource telemetry, folded into the SAME check-in
 * round-trip as `posture`/`productivity`/`argus`. Always-on (no consent
 * gate) — this is aggregate device-health data, not user-activity data,
 * treated the same as `PostureReport`. Latest-snapshot-only: the server
 * overwrites the prior sample rather than accumulating history. No process
 * list, no filenames — aggregate scalars only.
 */
export type DeviceResourceSample = { 
/**
 * 0.0–100.0, whole-system CPU utilization.
 */
cpu_usage_pct: number, ram_used_gb: number, ram_total_gb: number, disks: Array<DiskMetric>, net_up_bytes_per_sec: number, net_down_bytes_per_sec: number, 
/**
 * RFC3339, set by the agent at sample time (not the server's receipt time).
 */
sampled_at: string, };

/**
 * A device as shown in the admin panel's fleet view. `online` is computed by
 * the server from `last_seen` against a freshness window.
 */
export type DeviceSummary = { device_id: DeviceId, device_hash: string,
/**
 * Enrolled agent class (`wincommander`, `tuxcommander`, or `android`).
 * Additive/defaulted so older cached API responses still deserialize.
 */
device_kind: string, hostname: string | null, os_version: string | null, agent_version: string, enrolled_at: string, last_seen_at: string | null, online: boolean,
/**
 * Group this device is assigned to, if any (F4 device groups).
 */
group_id: string | null, 
/**
 * Latest live resource sample (F-metrics), if the device has ever
 * reported one. `None` for a device on an agent build predating this
 * field, or one that simply hasn't checked in yet.
 */
resources: DeviceResourceSample | null,
/**
 * Framework-authoritative Android fleet state from the latest check-in.
 */
android_fleet_status: AndroidFleetStatus | null, };

/**
 * One local drive/volume's capacity, sampled by the agent's existing
 * `sysinfo`-backed local dashboard collector. Reused verbatim for the fleet
 * resource sample below — same shape, no PII (mount point / drive letter
 * only, never file contents or names).
 */
export type DiskMetric = { name: string, total_gb: number, free_gb: number, };

/**
 * `files.fetch_content` command payload. `path` must be echoed from a prior
 * `files.search`/`files.recent_downloads` result for the SAME device — never
 * admin-typed free text (closes off an arbitrary-path read/enumeration
 * primitive). `transfer_token` is minted server-side, injected into the
 * payload BEFORE the command is signed (so it travels under the same
 * signature as `path`, no second unsigned side-channel) — the admin never
 * supplies it.
 */
export type FetchContentPayload = { path: string, transfer_token: string, };

/**
 * One row of a `files.list_dir` result — metadata only, never content.
 */
export type FileEntry = { name: string, path: string, is_dir: boolean, size_bytes: bigint, 
/**
 * RFC3339 last-modified time, or `None` if unavailable.
 */
modified_at: string | null, };

/**
 * Result of a `files.*` MUTATION (mkdir / rename / move / copy / recycle /
 * delete_permanent / shred / write_content). `ok` is ALWAYS derived from a
 * post-op re-stat of the effect on the device — never hardcoded — so a
 * denied / locked / still-present target reports `ok:false` with `detail`.
 */
export type FileOpResult = { ok: boolean, path: string, detail: string | null, };

/**
 * `files.stat` result — size / timestamps / attributes for one path.
 */
export type FileStatResult = { ok: boolean, path: string, detail: string | null, is_dir: boolean, size_bytes: bigint, 
/**
 * RFC3339 last-modified time, or `None` if unavailable.
 */
modified_at: string | null, 
/**
 * RFC3339 creation time, or `None` if the platform doesn't record it.
 */
created_at: string | null, 
/**
 * Windows file-attribute bitmask (0 on non-Windows agents).
 */
attributes: number, };

/**
 * Typed failure surface shared with the admin panel so the UI can branch on
 * the kind rather than parsing error strings.
 */
export type FleetError = "not_found" | "stale_epoch" | "bad_signature" | "bad_request" | "conflict" | "unauthorized" | "forbidden" | "rate_limited" | "internal";

/**
 * One admin-facing notification (P3). Currently emitted for config DRIFT — a
 * device running behind its resolved policy epoch (and, when the device reports
 * `toggle_states`, the specific toggles that diverged). `detail` is PII-free.
 */
export type FleetNotification = { id: bigint, 
/**
 * Notification class — "drift" (config drift) or "insider_risk" (a critical
 * Argus DLP/tamper/tripwire signal); extensible (e.g. "device_dark").
 */
kind: string, 
/**
 * "info" | "warn" | "critical".
 */
severity: string, 
/**
 * One-line human summary (no PII).
 */
summary: string, 
/**
 * Structured PII-free detail (e.g. drifted toggle paths + desired values).
 */
detail: JsonValue, device_id: DeviceId | null, hostname: string | null, read: boolean, created_at: string, };

/**
 * `files.hash` result — a content digest (currently SHA-256 only).
 */
export type HashResult = { ok: boolean, path: string, detail: string | null, algo: string, hex: string, size_bytes: bigint, };

/**
 * `files.list_dir` result — a bounded directory listing (see the handler's
 * entry cap). `entries` is empty when `ok` is false.
 */
export type ListDirResult = { ok: boolean, path: string, detail: string | null, entries: Array<FileEntry>, };

/**
 * Agent → server report of ONE local Windows notification the agent already
 * showed the user (screen-capture-tool detected, CPU/RAM/network threshold
 * exceeded, ...), forwarded to the fleet console only when the corresponding
 * per-type `notifications.<type>.reportToFleet` setting is on (agent-side
 * gate — the server stores whatever it is sent). Carries the SAME concrete
 * detail the local toast already showed, so the console can render a
 * specific message instead of a generic "alert" line. PII-free: `detail`
 * must contain only scalars/process-executable-names/metric values, never
 * window titles, file contents, or free-text.
 */
export type LocalAlertReport = {
/**
 * `"screen_capture" | "cpu_usage" | "ram_usage" | "network_usage"`.
 */
alert_type: string,
/**
 * e.g. `{"detected":"OBS Studio","process":"obs64.exe"}` or
 * `{"metric":"cpu","value_pct":94,"threshold_pct":85,"duration_s":300}`.
 */
detail: JsonValue,
/**
 * RFC3339, set by the agent at the moment the local notification fired.
 */
occurred_at: string | null, };

/**
 * Admin login credentials. Transport security (Tailscale/TLS) protects these.
 */
export type LoginRequest = { email: string, password: string, };

/**
 * Issued session. `token` is an opaque bearer the panel sends as
 * `Authorization: Bearer <token>`; the server resolves it to the admin + role
 * (re-read from the DB) on every request.
 */
export type LoginResponse = { token: string, role: AdminRole, expires_at: string, };

/**
 * Tenant identifier. `"local"` for single-tenant self-host installs; real
 * org slugs once multi-tenancy is enabled.
 */
export type OrgId = string;

/**
 * The per-key intent published within one policy layer.  Each intent binds
 * a policy key to a desired value, an enforcement mode, and an optional TTL.
 * The server normalises and signs an ordered slice of these in
 * [`ResolvedPolicy`]; the agent enforces them in `mode` order.
 *
 * Wire type — shared with the fleet server and the admin panel.  All fields
 * are serialised; none are optional except `ttl_secs` (absent = no expiry).
 */
export type PolicyIntent = { 
/**
 * Dot-path policy key, e.g. `"privacy.telemetry"` or `"fleet.enabled"`.
 */
key: string, 
/**
 * Desired value — matches the AppSettings field type on the wire.
 */
value: JsonValue, 
/**
 * Enforcement mode: `"off"` | `"report"` | `"heal"` | `"hard-lock"`.
 * Unknown modes are treated as `"off"` by the agent (fail-safe).
 */
mode: string, 
/**
 * How long (seconds) this intent is valid for.  `None` = no expiry.
 * The agent re-fetches policy before acting on an expired intent.
 */
ttl_secs: bigint | null, };

/**
 * One layer of the policy stack as stored and served by the fleet server.
 * Layers are merged by the server (priority ascending) into a
 * [`ResolvedPolicy`] that is signed and handed to the agent.
 */
export type PolicyLayer = { 
/**
 * Scope of this layer: `"org"` | `"group"` | `"device"`.
 */
layer_kind: string, 
/**
 * Scope identifier within the kind (group_id / device_id). `None` for
 * org-wide layers.
 */
layer_id: string | null, 
/**
 * Priority used when merging layers.  Higher priority wins on conflict.
 * Conventional values: org=0, group=100, device=200.
 */
priority: bigint, 
/**
 * The intents this layer declares.  The server deduplicates by `key`
 * (highest-priority wins) before producing [`ResolvedPolicy`].
 */
intents: Array<PolicyIntent>, };

/**
 * Agent → server applied-posture report (F6/F7). The agent reports the config
 * epoch it currently holds + a hash of its applied settings, so the server can
 * compute drift (behind the latest epoch) and compliance. No PII.
 */
export type PostureReport = { applied_epoch: bigint, settings_hash: string, 
/**
 * Optional PII-free map of `settings-dot-path → applied value` (booleans /
 * scalars only — never names/paths/URLs). When present the server diffs it
 * against the resolved epoch's desired config to surface PER-TOGGLE drift
 * (P3). Absent (`null`) → drift is computed at epoch granularity only.
 */
toggle_states: JsonValue | null,
/**
 * Whether the Privacy Shield is ACTUALLY running on the device right
 * now, self-reported at posture time. Compared against the resolved
 * `ShieldDesiredState` (a SEPARATE, non-epoch-versioned channel — see
 * that type's doc) to raise real shield drift, independent of
 * `applied_epoch`/`toggle_states`. `None` on any pre-shield-drift agent
 * build, or when the agent has no shield status to report this cycle.
 */
shield_running: boolean | null, };

/**
 * Aggregate productivity sample sent by an agent. Carries NO raw titles, URLs,
 * or keystrokes — only scalars + category scores (raw signals stay AES-GCM
 * encrypted on the device). Ingest is rejected unless `consent_version` matches
 * `disclosure_version` (the monitored user's consent must match the active
 * disclosure). Disclosed/consent-gated — never coupled to covert features.
 */
export type ProductivitySample = { window_start: string, window_end: string, active_seconds: number, idle_seconds: number, 
/**
 * Aggregate category → score map, e.g. `{"productive": 0.8}`. Aggregate only.
 */
category_scores: JsonValue, consent_version: number, disclosure_version: number, };

/**
 * One entry in a device's Downloads folder, returned by the
 * `files.recent_downloads` command. Metadata only (name/path/size/mtime) —
 * same disclosure boundary as `RemoteSearchResultRow`: an explicit,
 * audited, admin-triggered listing, never passive/automatic collection.
 */
export type RecentDownloadEntry = { name: string, path: string, size_bytes: bigint, 
/**
 * RFC3339 last-modified time.
 */
modified_at: string, };

/**
 * `files.recent_downloads` command result — newest-first, capped at a
 * device-side limit (see the handler).
 */
export type RecentDownloadsResult = { entries: Array<RecentDownloadEntry>, };

/**
 * Reserved seam for future remote file-search; carried in a command payload +
 * returned via the command result endpoint. Not yet wired to any catalog entry
 * or handler.
 */
export type RemoteSearchRequest = { terms: string, 
/**
 * Roots to walk. Omitted/empty ⇒ the device uses a bounded default scope
 * (the common user-profile dirs). `#[serde(default)]` so the payload can
 * omit it and the JSON-Schema `required` stays `[terms, mode]`.
 */
scope: Array<string>, mode: SearchMode, 
/**
 * Device-side filters applied before the row cap. `#[serde(default)]` keeps
 * the JSON-Schema `required` at `[terms, mode]`, so an older console that
 * omits this is unaffected.
 */
predicates: SearchPredicates, rank: SearchRank, };

/**
 * Cross-device file search result, returned via the command result endpoint
 * (§3.4) / the search fan-out aggregation route.
 */
export type RemoteSearchResult = { command_id: string, rows: Array<RemoteSearchResultRow>, index_status: JsonValue | null, 
/**
 * Whether this device actually evaluated `RemoteSearchRequest::predicates`.
 *
 * Serde ignores unknown fields, so an agent older than the predicate
 * contract accepts a filtered search and answers with UNFILTERED rows. The
 * console would then render an arbitrary capped sample as though it were
 * the filtered answer — a wrong result presented as a right one. Agents
 * that honour predicates set this true; `#[serde(default)]` makes every
 * older ack read false, so the console can say "this device ignored your
 * filters" instead of quietly lying.
 *
 * False is also correct for a request that carried no predicates at all;
 * the console only surfaces the warning when it actually sent some.
 */
predicates_applied: boolean, };

/**
 * Cross-device file search — one result row. Wired to `FILES_SEARCH_CATALOG_ID`
 * and commander-pro's `fleet_file_search` handler; dispatched via
 * `routes::search`'s fan-out endpoint. Name/path/size/mtime metadata only —
 * never content (see `NON-GOALS.md`'s "aggregate scalars, not raw filenames"
 * boundary — that boundary is about PASSIVE telemetry; this is an explicit,
 * audited, admin-triggered pull, the same distinction `files.recent_downloads`
 * below draws).
 */
export type RemoteSearchResultRow = { doc_id: string, path: string, name: string, ext: string, mtime: bigint, size: bigint, score: number, match_kind: string, snippet: string, };

/**
 * The signed, per-device policy projection delivered to the agent.  Produced
 * by the fleet server after merging all applicable [`PolicyLayer`]s.
 *
 * The agent verifies the signature over [`policy_preimage`]`(version, org_id,
 * device_id, intents)` using the fleet signing key pinned at enroll time, then
 * applies the intents in priority order.
 *
 * `version` is monotonically increasing per org (same anti-rollback rule as
 * [`ConfigEpoch`]).  Agents reject any `ResolvedPolicy` whose `version` is ≤
 * the last applied version.
 */
export type ResolvedPolicy = { 
/**
 * Monotonically increasing policy version for this org.
 */
version: bigint, org_id: OrgId, device_id: DeviceId, 
/**
 * Merged, deduplicated intents (sorted by `key` in the preimage — see
 * [`policy_preimage`]).
 */
intents: Array<PolicyIntent>, };

/**
 * Search backend a remote file-search request should use. Open/extensible —
 * new variants may be added as backends are built (Keyword ships first).
 */
export type SearchMode = "keyword" | "semantic" | "forensic";

/**
 * Result predicates evaluated ON THE DEVICE, during the walk and *before* the
 * row cap.
 *
 * This exists because the cap truncates, it does not rank: `fleet_search_walk`
 * returns the moment it reaches `FLEET_SEARCH_MAX_ROWS` in depth-first
 * traversal order. Filtering those rows in the console therefore filters an
 * arbitrary sample — a search for spreadsheets could return none while the
 * device holds hundreds, because the cap was spent on rows the operator was
 * about to discard. Pushing the predicate down makes the capped set 200
 * *relevant* rows.
 *
 * Every field is `#[serde(default)]`: the whole struct is optional in a signed
 * payload, and an omitted predicate means "no constraint", never "match
 * nothing".
 */
export type SearchPredicates = { 
/**
 * Lowercase extensions WITHOUT the leading dot (`["xlsx", "csv"]`).
 * Empty ⇒ any extension.
 */
ext_in: Array<string>, 
/**
 * Inclusive size bounds in bytes.
 */
size_min: bigint | null, size_max: bigint | null, 
/**
 * Inclusive mtime bounds, Unix seconds.
 */
modified_after: bigint | null, modified_before: bigint | null, 
/**
 * Case-insensitive path substrings to skip (e.g. `node_modules`). Applied
 * to the full path, and used to prune directory recursion where possible.
 */
path_exclude: Array<string>, };

/**
 * Which rows survive the cap when more match than it allows. `TraversalOrder`
 * is the pre-predicate behaviour, kept so an explicit request can still get it;
 * `ModifiedDesc` is the default because "what changed most recently" is the
 * question an operator is nearly always actually asking.
 */
export type SearchRank = "ModifiedDesc" | "SizeDesc" | "TraversalOrder";

/**
 * One bounded listening-port row from `endpoint.security_snapshot`.
 */
export type SecuritySnapshotListeningPort = { pid: number | null, protocol: SecuritySnapshotProtocol, local_address: string, local_port: number, process_name: string | null, process_path: string | null, };

/**
 * One bounded process row from `endpoint.security_snapshot`.
 */
export type SecuritySnapshotProcess = { pid: number, parent_pid: number | null, name: string, path: string | null, };

/**
 * Transport protocol for a listening socket. Snapshot v1 intentionally
 * excludes connection history and remote peers.
 */
export type SecuritySnapshotProtocol = "tcp" | "udp";

/**
 * Typed result for `endpoint.security_snapshot`. Version 1 contains exactly
 * processes, listening ports, and services; it deliberately excludes files,
 * scheduled tasks, startup items, hashes, and connection history. `truncated`
 * is true whenever an endpoint reached a collection bound, so an incomplete
 * result must never be rendered as a full inventory.
 */
export type SecuritySnapshotResult = { processes: Array<SecuritySnapshotProcess>, listening_ports: Array<SecuritySnapshotListeningPort>, services: Array<SecuritySnapshotService>, truncated: boolean, };

/**
 * One bounded Windows service row from `endpoint.security_snapshot`.
 */
export type SecuritySnapshotService = { name: string, start_type: string, status: string, path: string | null, };

/**
 * Privacy Shield's admin-desired on/off + mode, resolved device > group > org
 * (same precedence as `ConfigEpoch`) but stored and versioned SEPARATELY from
 * the policy `config_epochs` chain. Toggling the shield from the console
 * must NEVER advance `ConfigEpoch.version` — that chain is for actual policy
 * edits, and every version bump makes every OTHER device look momentarily
 * "behind" in `routes::posture::drift` (which compares against the org's
 * single highest version regardless of target). Delivered to the agent on
 * the same fast `/v1/agents/checkin` round-trip as `config_epoch`, via
 * `CheckinResponse.shield_state`.
 */
export type ShieldDesiredState = { enabled: boolean,
/**
 * `"blur_notify"` (blur/black-out the screen AND notify) | `"notify_only"`
 * (notification only, no visual blur). Mutually exclusive — see the
 * Privacy Shield card's segmented toggle.
 */
mode: string,
/**
 * RFC3339, set by the server when this desired state was last written.
 * Informational only (no anti-rollback gate — latest write always wins,
 * unlike `ConfigEpoch`).
 */
updated_at: string, };

/**
 * What an agent receives when it polls — the signed, executable envelope. The
 * agent verifies `signature` against `signer_key` and checks `epoch_version`
 * (anti-rollback) before executing the `catalog_id` action.
 *
 * # `idempotency_key` — the actual signed id (P0 fix)
 *
 * The operator (offline signing tool `sign-duress-command.rs`) signs
 * `canonical_command_bytes(command_id = idempotency_key, …)` because the
 * server-assigned UUID does not exist yet at signing time. `command_id` on
 * this struct is the server-assigned UUID (delivery/dedup/ack id) — it is
 * NOT what was signed. Every verifier (fleet-agent-core, Android) MUST
 * rebuild the preimage using `idempotency_key`, never `command_id`, or
 * signature verification silently fails and the command (including
 * `duress_wipe`) never executes. See `canonical_command_bytes`'s doc.
 */
export type SignedCommand = { command_id: string, 
/**
 * The stable id the signer actually signed over (operator-signed
 * commands: the offline tool's `--idempotency-key`; server-signed
 * commands: the same `idempotency_key` the caller supplied at creation —
 * see `finalize_if_ready`). Verifiers must use THIS field, not
 * `command_id`, when rebuilding `canonical_command_bytes`.
 */
idempotency_key: string, device_id: DeviceId, catalog_id: string, action_class: ActionClass, payload: JsonValue, epoch_version: bigint, signature: string, signer_key: string, };

/**
 * Change an admin's role (super_admin only).
 */
export type UpdateAdminRoleRequest = { role: AdminRole, };
