// lucide-react-backed drop-in replacement for BlueprintJS's <Icon>.
//
// WinCommander V2 migrates off @blueprintjs/core. Blueprint exposed a single
// <Icon icon="kebab-name" /> component backed by its own icon set; lucide-react
// uses PascalCase named component exports. This shim keeps the existing call
// sites unchanged — `<Icon icon="warning-sign" size={16} className=... />` —
// by translating each Blueprint icon-name string used anywhere in src/ to the
// closest real lucide-react icon component.
//
// To add a new Blueprint name: import a VERIFIED lucide export (confirm it
// exists in node_modules/lucide-react/dist/lucide-react.d.ts — a wrong name
// breaks the build) and add a "blueprint-name": Component entry to ICON_MAP.
// Every imported icon must appear in the map (noUnusedLocals is on). Unknown
// names fall back to Circle at runtime.

import * as React from "react";
import type { LucideProps } from "lucide-react";
import {
  Activity,
  Antenna,
  AppWindow,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpFromLine,
  BadgeCheck,
  Ban,
  Bell,
  Brain,
  Building2,
  Bug,
  Cable,
  Calendar,
  Camera,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleHelp,
  CircleSlash,
  CircleX,
  Clipboard,
  Clock,
  Cloud,
  CloudDownload,
  CloudOff,
  CloudUpload,
  Code,
  Command,
  Copy,
  Database,
  DollarSign,
  Dot,
  Download,
  Eraser,
  Eye,
  EyeOff,
  ExternalLink,
  FileArchive,
  FileInput,
  FileOutput,
  FileSearch,
  FileText,
  Filter,
  Fingerprint,
  Flame,
  FolderClock,
  FolderClosed,
  FolderInput,
  FolderOpen,
  FolderPlus,
  FolderSearch,
  GitBranch,
  GitFork,
  Globe,
  GraduationCap,
  Grid2x2,
  Grid3x3,
  Hand,
  Hash,
  History,
  Hourglass,
  House,
  IdCard,
  Image,
  Info,
  Key,
  KeyRound,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  ListChecks,
  Locate,
  Lock,
  MapPin,
  MessageSquare,
  Mic,
  Minus,
  Monitor,
  Moon,
  Sun,
  MoreHorizontal,
  Music,
  Network,
  Package,
  PackageMinus,
  Palette,
  Pencil,
  Phone,
  Pill,
  Plane,
  Play,
  Plus,
  Power,
  Presentation,
  Printer,
  RadioTower,
  RefreshCw,
  Repeat,
  Rocket,
  RotateCcw,
  Rss,
  Satellite,
  Save,
  ScanSearch,
  Scissors,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Shuffle,
  Smartphone,
  Snowflake,
  Sparkles,
  Square,
  SquareCheck,
  Stethoscope,
  StickyNote,
  Target,
  Terminal,
  Trash2,
  TriangleAlert,
  Undo2,
  Unlock,
  Upload,
  User,
  Users,
  Video,
  Workflow,
  Wrench,
  X,
  XCircle,
  Zap,
  ZoomIn,
} from "lucide-react";

type LucideIcon = React.ComponentType<LucideProps>;

// Blueprint icon-name (kebab-case) → closest lucide-react component.
const ICON_MAP: Record<string, LucideIcon> = {
  // ── Status / feedback ──
  "tick": Check,
  "small-tick": Check,
  "confirm": CheckCircle2,
  "tick-circle": CheckCircle2,
  "endorsed": BadgeCheck,
  "badge": BadgeCheck,
  "error": XCircle,
  "issue": TriangleAlert,
  "warning-sign": TriangleAlert,
  "info-sign": Info,
  "ban-circle": Ban,
  "disable": CircleSlash,
  "cross": X,
  "cross-circle": CircleX,
  "circle": Circle,
  "dot": Dot,
  "pulse": Activity,
  "diagnosis": Stethoscope,
  "notifications": Bell,

  // ── Security / privacy ──
  "shield": Shield,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "lock": Lock,
  "unlock": Unlock,
  "key": Key,
  "key-tab": KeyRound,
  "key-command": Command,
  "fingerprint": Fingerprint,
  "clean": Sparkles,
  "eraser": Eraser,
  "flame": Flame,
  "bug": Bug,
  "pill": Pill,
  "eye-open": Eye,
  "eye-off": EyeOff,
  "id-number": IdCard,

  // ── Navigation / chevrons / arrows ──
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "caret-up": ChevronUp,
  "caret-down": ChevronDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up": ArrowUp,
  "more": MoreHorizontal,

  // ── Actions ──
  "plus": Plus,
  "add": Plus,
  "minus": Minus,
  "trash": Trash2,
  "delete": Trash2,
  "duplicate": Copy,
  "edit": Pencil,
  "undo": Undo2,
  "reset": RotateCcw,
  "refresh": RefreshCw,
  "refresh-cw": RefreshCw,
  "automatic-updates": RefreshCw,
  "repeat": Repeat,
  "play": Play,
  "stop": Square,
  "search": Search,
  "search-around": ScanSearch,
  "search-text": FileSearch,
  "search-template": FileSearch,
  "filter": Filter,
  "cut": Scissors,
  "zoom-in": ZoomIn,
  "selection": SquareCheck,
  "share": Share2,
  "external-link": ExternalLink,
  "log-in": Download,
  "hand": Hand,
  "hand-up": Hand,
  "locate": Locate,
  "geolocation": MapPin,
  "map-marker": MapPin,
  "target": Target,
  "random": Shuffle,

  // ── Files / folders / documents ──
  "document": FileText,
  "document-open": FileOutput,
  "document-share": FileInput,
  "folder-open": FolderOpen,
  "folder-close": FolderClosed,
  "folder-new": FolderPlus,
  "folder-shared": FolderSearch,
  "folder-shared-open": FolderInput,
  "floppy-disk": Save,
  "media": Image,
  "video": Video,
  "music": Music,
  "compressed": FileArchive,
  "archive": Archive,
  "code": Code,
  "th": Grid3x3,
  "heat-grid": Grid2x2,
  "properties": ListChecks,
  "list-detail-view": ListChecks,
  "annotation": StickyNote,
  "drive-time": FolderClock,
  "import": Download,
  "export": Upload,

  // ── Apps / system ──
  "application": AppWindow,
  "applications": LayoutGrid,
  "cube": Package,
  "cube-remove": PackageMinus,
  "cog": Settings,
  "settings": Settings,
  "style": Palette,
  "dashboard": LayoutDashboard,
  "desktop": Monitor,
  "console": Terminal,
  "build": Wrench,
  "wrench": Wrench,
  "power": Power,
  "offline": CloudOff,
  "rocket": Rocket,
  "rocket-slant": Rocket,
  "home": House,
  "office": Building2,
  "people": Users,
  "user": User,
  "history": History,
  "clipboard": Clipboard,
  "database": Database,
  "fork": GitFork,
  "flow-branch": GitBranch,
  "data-lineage": Workflow,
  "data-connection": Cable,
  "predictive-analysis": Brain,
  "numerical": Hash,
  "presentation": Presentation,
  "shopping-cart": ShoppingCart,
  "print": Printer,
  "learning": GraduationCap,
  "lightbulb": Lightbulb,
  "snowflake": Snowflake,
  "timeline-events": Activity,
  "symbol-square": Square,
  "square": Square,

  // ── Network / connectivity ──
  "globe": Globe,
  "globe-network": Globe,
  "ip-address": Network,
  "cell-tower": RadioTower,
  "antenna": Antenna,
  "satellite": Satellite,
  "cloud": Cloud,
  "cloud-download": CloudDownload,
  "cloud-upload": CloudUpload,
  "download": Download,
  "upload": Upload,
  "feed": Rss,
  "feed-subscribed": Rss,
  "chat": MessageSquare,
  "phone": Phone,
  "mobile-phone": Smartphone,
  "microphone": Mic,
  "camera": Camera,

  // ── Time ──
  "time": Clock,
  "stopwatch": Hourglass,

  // ── Calendar ──
  "calendar": Calendar,

  // ── Misc / window / themes ──
  "moon": Moon,
  "sun": Sun,
  "flash": Zap,
  "dollar": DollarSign,
  "eject": ArrowUpFromLine,
  "airplane": Plane,
  "layout-grid": LayoutGrid,
  "help": CircleHelp,
};

export type IconName = keyof typeof ICON_MAP | (string & {});

type Intent = "success" | "warning" | "danger" | "primary" | "none" | string;

export interface IconProps extends Omit<LucideProps, "ref"> {
  icon: IconName;
  /** Pixel size; maps to lucide's numeric `size`. */
  size?: number;
  /** Tooltip/native title (Blueprint Icon accepted this). */
  title?: string;
  /** Blueprint-compatibility prop; mapped to a CSS color var. */
  intent?: Intent;
  /** Explicit color; takes precedence when no intent is given. */
  color?: string;
}

const INTENT_COLOR: Record<string, string> = {
  success: "var(--ok)",
  warning: "var(--warn)",
  danger: "var(--danger)",
  primary: "var(--accent)",
  none: "currentColor",
};

export function Icon({ icon, size = 16, intent, color, ...props }: IconProps) {
  const Cmp = ICON_MAP[icon] ?? Circle;
  const resolvedColor =
    intent != null ? (INTENT_COLOR[intent] ?? color) : color;
  // `intent` is destructured out above so it is never forwarded onto the
  // underlying SVG as an unknown DOM attribute.
  return <Cmp size={size} color={resolvedColor} {...props} />;
}

export default Icon;
